$axure.loadCurrentPage({
  "url":"others.html",
  "generationDate":new Date(1402535716189.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"43bc7e239e084fcb9105035167c77d6a",
    "type":"Axure:Page",
    "name":"others",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"115f907faf3a4212818328ef4fb9e44d",
          "label":"手机",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":754,
              "height":1478}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49442bda98ed4a828c6bd7f705c8addd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":754,
                  "height":1478}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/手机_u0.png"}},
{
          "id":"71bf53d145ce4d258fc44f9e8af7f044",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":260},
            "size":{
              "width":640,
              "height":960}},
          "adaptiveStyles":{
}},
{
          "id":"02308b426f2b43fbbdce2c4cf9a82363",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":260},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3efcd92381284a68b2aa0467acfc8146",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":260},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u3.png"}},
{
          "id":"59b49d2f0b1d4636af43f9c1b594c768",
          "label":"name",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":270},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"388e0319799243109fd1d37b482d77da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":270},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"0e716f30b0754b1fb72c0896010b0c7c",
          "label":"coin",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":320},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"933a45c69509439e95348a84d12ade2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":320},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"1730c3b9937649a8bf2f2aa212da8580",
          "label":"tips",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":270},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf8033fba3fb45998feff1bdbf875f8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":270},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"34676bc26e9c4b368f9e22c96bc86d12",
          "label":"magic stone",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":320},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beddb423a0944d67a568b19d68feb133",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":320},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If visibility of 不明 = 假 和 visibility of 不明 = 假 和 visibility of 不明 = 假 和 visibility of 不明 = 假)",
                  "isNewIfGroup":true,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetVisibility",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["25ec19a28c7744728ad0de069038b9ca"]}]},
                      "rightExpr":{
                        "exprType":"booleanLiteral",
                        "value":false}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"&&",
                      "leftExpr":{
                        "exprType":"binaryOp",
                        "op":"==",
                        "leftExpr":{
                          "exprType":"fcall",
                          "functionName":"GetWidgetVisibility",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["0639f3573115435e864d84df1f81802b"]}]},
                        "rightExpr":{
                          "exprType":"booleanLiteral",
                          "value":false}},
                      "rightExpr":{
                        "exprType":"binaryOp",
                        "op":"&&",
                        "leftExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetWidgetVisibility",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["6f7fba5a795346079703d0ab05bacc0d"]}]},
                          "rightExpr":{
                            "exprType":"booleanLiteral",
                            "value":false}},
                        "rightExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetWidgetVisibility",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["2bd36408615f46a6bc227ccb20e7e2ce"]}]},
                          "rightExpr":{
                            "exprType":"booleanLiteral",
                            "value":false}}}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]},
{
                  "description":"用例 2<br> (Else If visibility of 不明 = 真 和 visibility of 不明 = 真 和 visibility of 不明 = 真 和 visibility of 不明 = 真)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetVisibility",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["25ec19a28c7744728ad0de069038b9ca"]}]},
                      "rightExpr":{
                        "exprType":"booleanLiteral",
                        "value":true}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"&&",
                      "leftExpr":{
                        "exprType":"binaryOp",
                        "op":"==",
                        "leftExpr":{
                          "exprType":"fcall",
                          "functionName":"GetWidgetVisibility",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["0639f3573115435e864d84df1f81802b"]}]},
                        "rightExpr":{
                          "exprType":"booleanLiteral",
                          "value":true}},
                      "rightExpr":{
                        "exprType":"binaryOp",
                        "op":"&&",
                        "leftExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetWidgetVisibility",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["6f7fba5a795346079703d0ab05bacc0d"]}]},
                          "rightExpr":{
                            "exprType":"booleanLiteral",
                            "value":true}},
                        "rightExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetWidgetVisibility",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["2bd36408615f46a6bc227ccb20e7e2ce"]}]},
                          "rightExpr":{
                            "exprType":"booleanLiteral",
                            "value":true}}}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"ed501b765e224daf80fcdf8681e23d9e",
          "label":"add more magic stone",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":320},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55217d86e2c34deca49718cd3c309043",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":320},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/add_more_magic_stone_u13.png"}},
{
          "id":"b12348cb66f94dccb3362f2a36cdbe23",
          "label":"friends",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":525,
              "y":270},
            "size":{
              "width":160,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5f24403cb8a453d9b5124e77ea20512",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":525,
                  "y":270},
                "size":{
                  "width":160,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Friends",
                      "target":{
                        "targetType":"page",
                        "url":"friends.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/friends_u15.png"}},
{
          "id":"a2e43479a4b5432ea14a53e6bc1e739f",
          "label":"actor scene",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":360},
            "size":{
              "width":640,
              "height":730}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"050a55908d5846e28faea53a3b481dd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":360},
                "size":{
                  "width":640,
                  "height":730}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/actor_scene_u17.png"}},
{
          "id":"402a8ab8802e4c5db281ac7e8ae83e4a",
          "label":"optional bar",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":1090},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6b73491537047539502e65b53c3a67d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":1090},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/optional_bar_u19.png"}},
{
          "id":"a3546a77032f4e14ad10813b105ad8e6",
          "label":"monster",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":1100},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"598fff3917634ec29806e76c681ec759",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 monster",
                      "target":{
                        "targetType":"page",
                        "url":"monster.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"32d3416cc1bd4d8ba89fd1ffcb8b5e88",
          "label":"knapsack",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":1100},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07605281390949799a13163b05ce481b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"ed27b13ac4234940865a2b542df9444f",
          "label":"fighting",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":1100},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"513484ca83c843cfb6c81313a2f19ac5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"d799ea9592c746debcc1b1edfb5d007a",
          "label":"schedule",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":1100},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af68a9c62bd4483ba19480dd5a4f23c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 schedule",
                      "target":{
                        "targetType":"page",
                        "url":"schedule.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"dc98b814d4b241609283c553036f609d",
          "label":"others",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":574.5,
              "y":1100},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"620c9e90c50f472c800b1297686d3b54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":574.5,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 others",
                      "target":{
                        "targetType":"page",
                        "url":"others.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"f04b33b0138446c1b72ce56e75d07fd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":390},
            "size":{
              "width":15,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1739187973a4423b2e14dbc88c36986",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":820,
                  "y":390},
                "size":{
                  "width":15,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u39.png"}},
{
          "id":"a6834ae9678542cda6185b6979713aa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":520},
            "size":{
              "width":200,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2db78cb44512441d914a745b55a0d608",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":800,
                  "y":520},
                "size":{
                  "width":200,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u41.png"}},
{
          "id":"35ba8d7764ca42b4b4a3ee932bb92232",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":370},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"42de145cabd94b41854b6a3f6e8f9d19",
              "label":"other",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"589fd7c710764fee8ad95a3911a03136",
                  "label":"Friends list",
                  "parentDynamicPanel":"35ba8d7764ca42b4b4a3ee932bb92232",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":270,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c3d71e4027ea46809685148e69791bd5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"35ba8d7764ca42b4b4a3ee932bb92232",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":270,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/monster_box/check_information_optation_u125.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"4f97aaebefee4052aab2af6896bc8ec6",
              "label":"news",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a19aa271977f43e0be95f77422bcc9f7",
                  "label":"",
                  "parentDynamicPanel":"35ba8d7764ca42b4b4a3ee932bb92232",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":270,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"158c3f83008042baafc9d275100b8667",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"35ba8d7764ca42b4b4a3ee932bb92232",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":270,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/monster_box/check_information_optation_u125.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"2bb1e613ac08486f9c756c6c31c26823",
              "label":"moster book",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6e8c87c96230400eaa962053ccc8fbd6",
                  "label":"",
                  "parentDynamicPanel":"35ba8d7764ca42b4b4a3ee932bb92232",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":270,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"659e08125b304d128dc66ae2a26e1370",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"35ba8d7764ca42b4b4a3ee932bb92232",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":270,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/monster_box/check_information_optation_u125.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"b37a29ddbc9f4537ab3ddea6c2712791",
              "label":"options",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"beaa1a57bc5846f4ba26b48de7fbec81",
                  "label":"",
                  "parentDynamicPanel":"35ba8d7764ca42b4b4a3ee932bb92232",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":270,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9538764a710d477fbf2f9a409d1f4c52",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"35ba8d7764ca42b4b4a3ee932bb92232",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":270,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/monster_box/check_information_optation_u125.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"ed108b2572bf429881cca189ca2206d7",
              "label":"help",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e540534b1fc64929a359d2591e6b8849",
                  "label":"",
                  "parentDynamicPanel":"35ba8d7764ca42b4b4a3ee932bb92232",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":270,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"097db68a52e74aa9a5ebb2eca05b5b1c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"35ba8d7764ca42b4b4a3ee932bb92232",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":270,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/monster_box/check_information_optation_u125.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"d03d49d3f1ef433c997c27ddfffb815d",
          "label":"news",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":520},
            "size":{
              "width":500,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4c9379592c74bc592cd7abede92c512",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":520},
                "size":{
                  "width":500,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 ok （news）,<br>back to others,<br>news bar",
                      "objectsToFades":[{
                          "objectPath":["143e9a7ea77a402796a22512328be461"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ff1aa7906cab40539506371fb6e8fb61"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["d86b821a54cf44518a70d7464c98719d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelState",
                      "description":"设置 (动态面板) to news",
                      "panelsToStates":[{
                          "panelPath":["35ba8d7764ca42b4b4a3ee932bb92232"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/monster/moster_box_u33.png"}},
{
          "id":"095fc9818f574c6f8f78d7fee1493e29",
          "label":"monster book",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":640},
            "size":{
              "width":500,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfa4f32bcb284d7e83d7a5db31503ab8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":640},
                "size":{
                  "width":500,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/monster/moster_box_u33.png"}},
{
          "id":"a05223af59ca418dbe1c108af9e3fc4e",
          "label":"options",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":760},
            "size":{
              "width":500,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a7961eabeea48c1bf19283b4971c58e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":760},
                "size":{
                  "width":500,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/monster/moster_box_u33.png"}},
{
          "id":"7a9951a6db2b4332897a965afd690007",
          "label":"Sell monsters",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":880},
            "size":{
              "width":500,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a1229da6ba342a58abb053425e0a608",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":880},
                "size":{
                  "width":500,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/monster/moster_box_u33.png"}},
{
          "id":"d79055192d554c1699b0c22993fb8f26",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":370},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c07a52b34c724d998c828154e0800805",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":370},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 HOME",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/world_boss/u73.png"}},
{
          "id":"d86b821a54cf44518a70d7464c98719d",
          "label":"news bar",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":130,
              "y":520},
            "size":{
              "width":500,
              "height":460},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a15bafb58152404f907a21a0bf6dc255",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":130,
                  "y":520},
                "size":{
                  "width":500,
                  "height":460},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/others/news_bar_u56.png"}},
{
          "id":"143e9a7ea77a402796a22512328be461",
          "label":"ok （news）",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":330,
              "y":910},
            "size":{
              "width":100,
              "height":50},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e246121d2fb4ff8b8e85d6f3c5912c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":330,
                  "y":910},
                "size":{
                  "width":100,
                  "height":50},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If visibility of This = 真)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetVisibility",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":true}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 ok （news）,<br>back to others,<br>news bar",
                      "objectsToFades":[{
                          "objectPath":["143e9a7ea77a402796a22512328be461"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ff1aa7906cab40539506371fb6e8fb61"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["d86b821a54cf44518a70d7464c98719d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelState",
                      "description":"设置 (动态面板) to other",
                      "panelsToStates":[{
                          "panelPath":["35ba8d7764ca42b4b4a3ee932bb92232"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/monster_box/yes_u137.png"}},
{
          "id":"ff1aa7906cab40539506371fb6e8fb61",
          "label":"back to others",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":75,
              "y":370},
            "size":{
              "width":60,
              "height":60},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"193430ba58b24febbfee85ad03582111",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":75,
                  "y":370},
                "size":{
                  "width":60,
                  "height":60},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If visibility of This = 真)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetVisibility",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":true}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 news bar,<br>ok （news）,<br>back to others",
                      "objectsToFades":[{
                          "objectPath":["d86b821a54cf44518a70d7464c98719d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["143e9a7ea77a402796a22512328be461"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ff1aa7906cab40539506371fb6e8fb61"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelState",
                      "description":"设置 (动态面板) to other",
                      "panelsToStates":[{
                          "panelPath":["35ba8d7764ca42b4b4a3ee932bb92232"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/world_boss/u73.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "115f907faf3a4212818328ef4fb9e44d":{
      "scriptId":"u0"},
    "49442bda98ed4a828c6bd7f705c8addd":{
      "scriptId":"u1"},
    "71bf53d145ce4d258fc44f9e8af7f044":{
      "scriptId":"u2"},
    "02308b426f2b43fbbdce2c4cf9a82363":{
      "scriptId":"u3"},
    "3efcd92381284a68b2aa0467acfc8146":{
      "scriptId":"u4"},
    "59b49d2f0b1d4636af43f9c1b594c768":{
      "scriptId":"u5"},
    "388e0319799243109fd1d37b482d77da":{
      "scriptId":"u6"},
    "0e716f30b0754b1fb72c0896010b0c7c":{
      "scriptId":"u7"},
    "933a45c69509439e95348a84d12ade2f":{
      "scriptId":"u8"},
    "1730c3b9937649a8bf2f2aa212da8580":{
      "scriptId":"u9"},
    "bf8033fba3fb45998feff1bdbf875f8b":{
      "scriptId":"u10"},
    "34676bc26e9c4b368f9e22c96bc86d12":{
      "scriptId":"u11"},
    "beddb423a0944d67a568b19d68feb133":{
      "scriptId":"u12"},
    "ed501b765e224daf80fcdf8681e23d9e":{
      "scriptId":"u13"},
    "55217d86e2c34deca49718cd3c309043":{
      "scriptId":"u14"},
    "b12348cb66f94dccb3362f2a36cdbe23":{
      "scriptId":"u15"},
    "f5f24403cb8a453d9b5124e77ea20512":{
      "scriptId":"u16"},
    "a2e43479a4b5432ea14a53e6bc1e739f":{
      "scriptId":"u17"},
    "050a55908d5846e28faea53a3b481dd1":{
      "scriptId":"u18"},
    "402a8ab8802e4c5db281ac7e8ae83e4a":{
      "scriptId":"u19"},
    "a6b73491537047539502e65b53c3a67d":{
      "scriptId":"u20"},
    "a3546a77032f4e14ad10813b105ad8e6":{
      "scriptId":"u21"},
    "598fff3917634ec29806e76c681ec759":{
      "scriptId":"u22"},
    "32d3416cc1bd4d8ba89fd1ffcb8b5e88":{
      "scriptId":"u23"},
    "07605281390949799a13163b05ce481b":{
      "scriptId":"u24"},
    "ed27b13ac4234940865a2b542df9444f":{
      "scriptId":"u25"},
    "513484ca83c843cfb6c81313a2f19ac5":{
      "scriptId":"u26"},
    "d799ea9592c746debcc1b1edfb5d007a":{
      "scriptId":"u27"},
    "af68a9c62bd4483ba19480dd5a4f23c0":{
      "scriptId":"u28"},
    "dc98b814d4b241609283c553036f609d":{
      "scriptId":"u29"},
    "620c9e90c50f472c800b1297686d3b54":{
      "scriptId":"u30"},
    "f04b33b0138446c1b72ce56e75d07fd8":{
      "scriptId":"u31"},
    "f1739187973a4423b2e14dbc88c36986":{
      "scriptId":"u32"},
    "a6834ae9678542cda6185b6979713aa8":{
      "scriptId":"u33"},
    "2db78cb44512441d914a745b55a0d608":{
      "scriptId":"u34"},
    "35ba8d7764ca42b4b4a3ee932bb92232":{
      "scriptId":"u35"},
    "589fd7c710764fee8ad95a3911a03136":{
      "scriptId":"u36"},
    "c3d71e4027ea46809685148e69791bd5":{
      "scriptId":"u37"},
    "a19aa271977f43e0be95f77422bcc9f7":{
      "scriptId":"u38"},
    "158c3f83008042baafc9d275100b8667":{
      "scriptId":"u39"},
    "6e8c87c96230400eaa962053ccc8fbd6":{
      "scriptId":"u40"},
    "659e08125b304d128dc66ae2a26e1370":{
      "scriptId":"u41"},
    "beaa1a57bc5846f4ba26b48de7fbec81":{
      "scriptId":"u42"},
    "9538764a710d477fbf2f9a409d1f4c52":{
      "scriptId":"u43"},
    "e540534b1fc64929a359d2591e6b8849":{
      "scriptId":"u44"},
    "097db68a52e74aa9a5ebb2eca05b5b1c":{
      "scriptId":"u45"},
    "d03d49d3f1ef433c997c27ddfffb815d":{
      "scriptId":"u46"},
    "b4c9379592c74bc592cd7abede92c512":{
      "scriptId":"u47"},
    "095fc9818f574c6f8f78d7fee1493e29":{
      "scriptId":"u48"},
    "cfa4f32bcb284d7e83d7a5db31503ab8":{
      "scriptId":"u49"},
    "a05223af59ca418dbe1c108af9e3fc4e":{
      "scriptId":"u50"},
    "5a7961eabeea48c1bf19283b4971c58e":{
      "scriptId":"u51"},
    "7a9951a6db2b4332897a965afd690007":{
      "scriptId":"u52"},
    "9a1229da6ba342a58abb053425e0a608":{
      "scriptId":"u53"},
    "d79055192d554c1699b0c22993fb8f26":{
      "scriptId":"u54"},
    "c07a52b34c724d998c828154e0800805":{
      "scriptId":"u55"},
    "d86b821a54cf44518a70d7464c98719d":{
      "scriptId":"u56"},
    "a15bafb58152404f907a21a0bf6dc255":{
      "scriptId":"u57"},
    "143e9a7ea77a402796a22512328be461":{
      "scriptId":"u58"},
    "4e246121d2fb4ff8b8e85d6f3c5912c0":{
      "scriptId":"u59"},
    "ff1aa7906cab40539506371fb6e8fb61":{
      "scriptId":"u60"},
    "193430ba58b24febbfee85ad03582111":{
      "scriptId":"u61"}}});