$axure.loadCurrentPage({
  "url":"fusion.html",
  "generationDate":new Date(1402535712252.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f727db2e91104e19a8406e0a98dd901a",
    "type":"Axure:Page",
    "name":"fusion",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"115f907faf3a4212818328ef4fb9e44d",
          "label":"手机",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":754,
              "height":1478}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49442bda98ed4a828c6bd7f705c8addd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":754,
                  "height":1478}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/手机_u0.png"}},
{
          "id":"71bf53d145ce4d258fc44f9e8af7f044",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":260},
            "size":{
              "width":640,
              "height":960}},
          "adaptiveStyles":{
}},
{
          "id":"02308b426f2b43fbbdce2c4cf9a82363",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":260},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3efcd92381284a68b2aa0467acfc8146",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":260},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u3.png"}},
{
          "id":"59b49d2f0b1d4636af43f9c1b594c768",
          "label":"name",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":270},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"388e0319799243109fd1d37b482d77da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":270},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"0e716f30b0754b1fb72c0896010b0c7c",
          "label":"coin",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":320},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"933a45c69509439e95348a84d12ade2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":320},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"1730c3b9937649a8bf2f2aa212da8580",
          "label":"tips",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":270},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf8033fba3fb45998feff1bdbf875f8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":270},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"34676bc26e9c4b368f9e22c96bc86d12",
          "label":"magic stone",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":320},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beddb423a0944d67a568b19d68feb133",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":320},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If visibility of shopping bar = 假 和 visibility of shopping bar option 1 = 假 和 visibility of shopping bar option 2 = 假 和 visibility of shopping&nbsp; bar option 3 = 假)",
                  "isNewIfGroup":true,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetVisibility",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["25ec19a28c7744728ad0de069038b9ca"]}]},
                      "rightExpr":{
                        "exprType":"booleanLiteral",
                        "value":false}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"&&",
                      "leftExpr":{
                        "exprType":"binaryOp",
                        "op":"==",
                        "leftExpr":{
                          "exprType":"fcall",
                          "functionName":"GetWidgetVisibility",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["0639f3573115435e864d84df1f81802b"]}]},
                        "rightExpr":{
                          "exprType":"booleanLiteral",
                          "value":false}},
                      "rightExpr":{
                        "exprType":"binaryOp",
                        "op":"&&",
                        "leftExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetWidgetVisibility",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["6f7fba5a795346079703d0ab05bacc0d"]}]},
                          "rightExpr":{
                            "exprType":"booleanLiteral",
                            "value":false}},
                        "rightExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetWidgetVisibility",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["2bd36408615f46a6bc227ccb20e7e2ce"]}]},
                          "rightExpr":{
                            "exprType":"booleanLiteral",
                            "value":false}}}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 shopping bar,<br>shopping bar option 1,<br>shopping bar option 2,<br>shopping&nbsp; bar option 3",
                      "objectsToFades":[{
                          "objectPath":["25ec19a28c7744728ad0de069038b9ca"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0639f3573115435e864d84df1f81802b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6f7fba5a795346079703d0ab05bacc0d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2bd36408615f46a6bc227ccb20e7e2ce"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"用例 2<br> (Else If visibility of shopping bar = 真 和 visibility of shopping bar option 1 = 真 和 visibility of shopping bar option 2 = 真 和 visibility of shopping&nbsp; bar option 3 = 真)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetVisibility",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["25ec19a28c7744728ad0de069038b9ca"]}]},
                      "rightExpr":{
                        "exprType":"booleanLiteral",
                        "value":true}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"&&",
                      "leftExpr":{
                        "exprType":"binaryOp",
                        "op":"==",
                        "leftExpr":{
                          "exprType":"fcall",
                          "functionName":"GetWidgetVisibility",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["0639f3573115435e864d84df1f81802b"]}]},
                        "rightExpr":{
                          "exprType":"booleanLiteral",
                          "value":true}},
                      "rightExpr":{
                        "exprType":"binaryOp",
                        "op":"&&",
                        "leftExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetWidgetVisibility",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["6f7fba5a795346079703d0ab05bacc0d"]}]},
                          "rightExpr":{
                            "exprType":"booleanLiteral",
                            "value":true}},
                        "rightExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetWidgetVisibility",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["2bd36408615f46a6bc227ccb20e7e2ce"]}]},
                          "rightExpr":{
                            "exprType":"booleanLiteral",
                            "value":true}}}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 shopping bar,<br>shopping bar option 1,<br>shopping bar option 2,<br>shopping&nbsp; bar option 3",
                      "objectsToFades":[{
                          "objectPath":["25ec19a28c7744728ad0de069038b9ca"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0639f3573115435e864d84df1f81802b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6f7fba5a795346079703d0ab05bacc0d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2bd36408615f46a6bc227ccb20e7e2ce"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"ed501b765e224daf80fcdf8681e23d9e",
          "label":"add more magic stone",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":320},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55217d86e2c34deca49718cd3c309043",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":320},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/add_more_magic_stone_u13.png"}},
{
          "id":"b12348cb66f94dccb3362f2a36cdbe23",
          "label":"friends",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":525,
              "y":270},
            "size":{
              "width":160,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5f24403cb8a453d9b5124e77ea20512",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":525,
                  "y":270},
                "size":{
                  "width":160,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Friends",
                      "target":{
                        "targetType":"page",
                        "url":"friends.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/friends_u15.png"}},
{
          "id":"a2e43479a4b5432ea14a53e6bc1e739f",
          "label":"actor scene",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":360},
            "size":{
              "width":640,
              "height":730}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"050a55908d5846e28faea53a3b481dd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":360},
                "size":{
                  "width":640,
                  "height":730}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/actor_scene_u17.png"}},
{
          "id":"897ffad8ebe040e8b9f1ee01ae1d7831",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":460},
            "size":{
              "width":300,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd1a87cba21f428895bb73b2bc4f8d92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":460},
                "size":{
                  "width":300,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fusion/u19.png"}},
{
          "id":"402a8ab8802e4c5db281ac7e8ae83e4a",
          "label":"optional bar",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":1090},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6b73491537047539502e65b53c3a67d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":1090},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/optional_bar_u19.png"}},
{
          "id":"a3546a77032f4e14ad10813b105ad8e6",
          "label":"monster",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":1100},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"598fff3917634ec29806e76c681ec759",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 monster",
                      "target":{
                        "targetType":"page",
                        "url":"monster.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"32d3416cc1bd4d8ba89fd1ffcb8b5e88",
          "label":"knapsack",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":1100},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07605281390949799a13163b05ce481b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 fusion",
                      "target":{
                        "targetType":"page",
                        "url":"fusion.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"ed27b13ac4234940865a2b542df9444f",
          "label":"fighting",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":1100},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"513484ca83c843cfb6c81313a2f19ac5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"d799ea9592c746debcc1b1edfb5d007a",
          "label":"schedule",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":1100},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af68a9c62bd4483ba19480dd5a4f23c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 schedule",
                      "target":{
                        "targetType":"page",
                        "url":"schedule.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"dc98b814d4b241609283c553036f609d",
          "label":"others",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":574.5,
              "y":1100},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"620c9e90c50f472c800b1297686d3b54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":574.5,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 others",
                      "target":{
                        "targetType":"page",
                        "url":"others.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"25ec19a28c7744728ad0de069038b9ca",
          "label":"shopping bar",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":60,
              "y":600},
            "size":{
              "width":640,
              "height":250},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52567f36c2cf4986ae62885485d5b80c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":60,
                  "y":600},
                "size":{
                  "width":640,
                  "height":250},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/shopping_bar_u95.png"}},
{
          "id":"0639f3573115435e864d84df1f81802b",
          "label":"shopping bar option 1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":75,
              "y":615},
            "size":{
              "width":180,
              "height":220},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3875cfd0e1f4f6d9bb986ad40f376f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":75,
                  "y":615},
                "size":{
                  "width":180,
                  "height":220},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/shopping_bar_option_1_u97.png"}},
{
          "id":"6f7fba5a795346079703d0ab05bacc0d",
          "label":"shopping bar option 2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":270,
              "y":615},
            "size":{
              "width":180,
              "height":220},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e8a8e0bec0e4a7ab5218bc23d363c7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":270,
                  "y":615},
                "size":{
                  "width":180,
                  "height":220},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/shopping_bar_option_1_u97.png"}},
{
          "id":"2bd36408615f46a6bc227ccb20e7e2ce",
          "label":"shopping  bar option 3",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":465,
              "y":615},
            "size":{
              "width":180,
              "height":220},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44e690f7acbe4e979e86d22d1ca79835",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":465,
                  "y":615},
                "size":{
                  "width":180,
                  "height":220},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/shopping_bar_option_1_u97.png"}},
{
          "id":"fded63e23e7542519efa72f261046895",
          "label":"Friends list",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":370},
            "size":{
              "width":270,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"646a7f7f5a9049a5887c7dddf18ce62b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":370},
                "size":{
                  "width":270,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/monster_box/check_information_optation_u125.png"}},
{
          "id":"fed5393b28594c61938099ecc70efce4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":370},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13408e9b55324ca6b746511fc8394cc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":370},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Euo Fusion",
                      "target":{
                        "targetType":"page",
                        "url":"euo_fusion.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/world_boss/u73.png"}},
{
          "id":"a32b99a0ae004357975523760104a5e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":460},
            "size":{
              "width":96,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4db077705654cfc834dba8bccd15c56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":460},
                "size":{
                  "width":96,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fusion/u45.png"}},
{
          "id":"01240bf259d44a4f997351e2938ba3ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":880},
            "size":{
              "width":300,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d72e0ca334d041388aeee22651ea2fe0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":880},
                "size":{
                  "width":300,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fusion/u19.png"}},
{
          "id":"7ead0314f29244dcb044972a5e26a0dd",
          "label":"experience",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":531},
            "size":{
              "width":195,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fda7f74cee6474083147cbd4e3747f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":531},
                "size":{
                  "width":195,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fusion/experience_u49.png"}},
{
          "id":"6acc81744d8148debe3a5f3a3b3a1d3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":323,
              "y":460},
            "size":{
              "width":204,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd46e4fb9e644752aa1041dabd3cf633",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":323,
                  "y":460},
                "size":{
                  "width":204,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fusion/u51.png"}},
{
          "id":"a3c089afcd9346dcaf343f416c9a2cb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"13px",
            "location":{
              "x":330,
              "y":473},
            "size":{
              "width":38,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd8d2313a23442aa83b6dfc7d7907f3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"13px",
                "location":{
                  "x":330,
                  "y":473},
                "size":{
                  "width":38,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2752bd3bdb9547a0a162f78590440528",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":376,
              "y":460},
            "size":{
              "width":38,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2badef1f045547538993cd9b79b09cbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":376,
                  "y":460},
                "size":{
                  "width":38,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21cf77c4df6e4deca3bffa2038102a31",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":376,
              "y":488},
            "size":{
              "width":38,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3488e2871cd64ddb99504a2ede569266",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":376,
                  "y":488},
                "size":{
                  "width":38,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8fe2e16bbe674516abfcefe7f4775399",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":421,
              "y":491},
            "size":{
              "width":38,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f66d413d53040ba9d4451bb5816e3a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":421,
                  "y":491},
                "size":{
                  "width":38,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a1ff4eefe474b2687edb515899b9b8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":421,
              "y":460},
            "size":{
              "width":38,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e26dd73102f14ed0b3dbed0b3619ba0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":421,
                  "y":460},
                "size":{
                  "width":38,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"360d02cee890428bbb619bd93992813a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":467,
              "y":491},
            "size":{
              "width":53,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4db8ddb4b3e4ab9b238194a33a707f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":467,
                  "y":491},
                "size":{
                  "width":53,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"751dd2acae4b4b2fa71d5860ec648695",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":467,
              "y":460},
            "size":{
              "width":53,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1ff7686bdde4d408432aa153755070f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":467,
                  "y":460},
                "size":{
                  "width":53,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b52aae9ab914caabf5720732597b619",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":880},
            "size":{
              "width":96,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a336c75a5a6475eb7a7fc0400c39a10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":880},
                "size":{
                  "width":96,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fusion/u45.png"}},
{
          "id":"fb44cf8695b145699b346b8f250b12b8",
          "label":"experience",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":951},
            "size":{
              "width":195,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"368c3993aaeb467e9c5fd06af1af4b6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":951},
                "size":{
                  "width":195,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fusion/experience_u49.png"}},
{
          "id":"c3f193eb76004bdc95f57a77c46f4d44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":323,
              "y":880},
            "size":{
              "width":204,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b46f2ed01bfb4660833e2b9cf68bf995",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":323,
                  "y":880},
                "size":{
                  "width":204,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fusion/u51.png"}},
{
          "id":"1766919edf1449459b8f2170d7a5fcda",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"13px",
            "location":{
              "x":330,
              "y":893},
            "size":{
              "width":38,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24ee3fb6976044308a7b3f24a7fd2945",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"13px",
                "location":{
                  "x":330,
                  "y":893},
                "size":{
                  "width":38,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af153bb73bfa49d2a2e3e93edc463548",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":376,
              "y":880},
            "size":{
              "width":38,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1111ff1e33c4b8ba2eee93295f6104b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":376,
                  "y":880},
                "size":{
                  "width":38,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"602a34d176d3450cb5e9934cfeb95146",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":376,
              "y":908},
            "size":{
              "width":38,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"033b5f56951841a7bf90f6f00cc3dcf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":376,
                  "y":908},
                "size":{
                  "width":38,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d05ba9e5bed442418573a513b463fb52",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":421,
              "y":911},
            "size":{
              "width":38,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36babdfa3f434e7b93a386e07a296e7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":421,
                  "y":911},
                "size":{
                  "width":38,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68b55a1dc8cb4e02a7c74cf99b538c19",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":421,
              "y":880},
            "size":{
              "width":38,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"162d80f8521a4ec58b052036be81dca0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":421,
                  "y":880},
                "size":{
                  "width":38,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb42a9d2bf344048906121a7a73806a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":467,
              "y":911},
            "size":{
              "width":53,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82a4a057c45d4a82ba1a3cd50745f1b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":467,
                  "y":911},
                "size":{
                  "width":53,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ca36725ed764f8a80174e67ff1d41d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":467,
              "y":880},
            "size":{
              "width":53,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f05c248426ed4b3891b21c92a9b17214",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":467,
                  "y":880},
                "size":{
                  "width":53,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bcade75486f46b2944f578145592efa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":900},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"616859eec05b4354aa7a35e0fe82fb9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":900},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/monster_box/u47.png"}},
{
          "id":"b1f911fc32c44cb59089a1886637fcd9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":480},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b420fee030a149e684635e478dde3f39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":480},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fighting/u4.png"}},
{
          "id":"36ee4594dc254585a3825a036a68905d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":212,
              "y":650},
            "size":{
              "width":330,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80eac26e632540d6a2a03c5255299871",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":212,
                  "y":650},
                "size":{
                  "width":330,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fusion/u91.png"}},
{
          "id":"bdac98cdb4174b19b4d8a3ea237e3320",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":670},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a95bcac0bba478481cab5c780467080",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":232,
                  "y":670},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u65.png"}},
{
          "id":"febb5e48f16947fba98edf8b23761a02",
          "label":"fusion",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":720},
            "size":{
              "width":100,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f90262cafd1498998643d1321ce7028",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":387,
                  "y":720},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If visibility of animation = 假)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetVisibility",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["e64bef9112e748c2a57ad4fabeb82389"]}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":false}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]},
{
                      "action":"fadeWidget",
                      "description":"显示 animation",
                      "objectsToFades":[{
                          "objectPath":["e64bef9112e748c2a57ad4fabeb82389"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/monster_box/yes_u137.png"}},
{
          "id":"c68eb04ebf964335a056fa5014e63686",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":352,
              "y":670},
            "size":{
              "width":170,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"726025adf96d415cb396671e84545eaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":352,
                  "y":670},
                "size":{
                  "width":170,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fusion/u97.png"}},
{
          "id":"e64bef9112e748c2a57ad4fabeb82389",
          "label":"animation",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":60,
              "y":360},
            "size":{
              "width":640,
              "height":860},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4260bbbec34343489db5dcdfe1db24b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":60,
                  "y":360},
                "size":{
                  "width":640,
                  "height":860},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 HOME",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/fusion/animation_u99.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "115f907faf3a4212818328ef4fb9e44d":{
      "scriptId":"u0"},
    "49442bda98ed4a828c6bd7f705c8addd":{
      "scriptId":"u1"},
    "71bf53d145ce4d258fc44f9e8af7f044":{
      "scriptId":"u2"},
    "02308b426f2b43fbbdce2c4cf9a82363":{
      "scriptId":"u3"},
    "3efcd92381284a68b2aa0467acfc8146":{
      "scriptId":"u4"},
    "59b49d2f0b1d4636af43f9c1b594c768":{
      "scriptId":"u5"},
    "388e0319799243109fd1d37b482d77da":{
      "scriptId":"u6"},
    "0e716f30b0754b1fb72c0896010b0c7c":{
      "scriptId":"u7"},
    "933a45c69509439e95348a84d12ade2f":{
      "scriptId":"u8"},
    "1730c3b9937649a8bf2f2aa212da8580":{
      "scriptId":"u9"},
    "bf8033fba3fb45998feff1bdbf875f8b":{
      "scriptId":"u10"},
    "34676bc26e9c4b368f9e22c96bc86d12":{
      "scriptId":"u11"},
    "beddb423a0944d67a568b19d68feb133":{
      "scriptId":"u12"},
    "ed501b765e224daf80fcdf8681e23d9e":{
      "scriptId":"u13"},
    "55217d86e2c34deca49718cd3c309043":{
      "scriptId":"u14"},
    "b12348cb66f94dccb3362f2a36cdbe23":{
      "scriptId":"u15"},
    "f5f24403cb8a453d9b5124e77ea20512":{
      "scriptId":"u16"},
    "a2e43479a4b5432ea14a53e6bc1e739f":{
      "scriptId":"u17"},
    "050a55908d5846e28faea53a3b481dd1":{
      "scriptId":"u18"},
    "897ffad8ebe040e8b9f1ee01ae1d7831":{
      "scriptId":"u19"},
    "fd1a87cba21f428895bb73b2bc4f8d92":{
      "scriptId":"u20"},
    "402a8ab8802e4c5db281ac7e8ae83e4a":{
      "scriptId":"u21"},
    "a6b73491537047539502e65b53c3a67d":{
      "scriptId":"u22"},
    "a3546a77032f4e14ad10813b105ad8e6":{
      "scriptId":"u23"},
    "598fff3917634ec29806e76c681ec759":{
      "scriptId":"u24"},
    "32d3416cc1bd4d8ba89fd1ffcb8b5e88":{
      "scriptId":"u25"},
    "07605281390949799a13163b05ce481b":{
      "scriptId":"u26"},
    "ed27b13ac4234940865a2b542df9444f":{
      "scriptId":"u27"},
    "513484ca83c843cfb6c81313a2f19ac5":{
      "scriptId":"u28"},
    "d799ea9592c746debcc1b1edfb5d007a":{
      "scriptId":"u29"},
    "af68a9c62bd4483ba19480dd5a4f23c0":{
      "scriptId":"u30"},
    "dc98b814d4b241609283c553036f609d":{
      "scriptId":"u31"},
    "620c9e90c50f472c800b1297686d3b54":{
      "scriptId":"u32"},
    "25ec19a28c7744728ad0de069038b9ca":{
      "scriptId":"u33"},
    "52567f36c2cf4986ae62885485d5b80c":{
      "scriptId":"u34"},
    "0639f3573115435e864d84df1f81802b":{
      "scriptId":"u35"},
    "f3875cfd0e1f4f6d9bb986ad40f376f8":{
      "scriptId":"u36"},
    "6f7fba5a795346079703d0ab05bacc0d":{
      "scriptId":"u37"},
    "2e8a8e0bec0e4a7ab5218bc23d363c7d":{
      "scriptId":"u38"},
    "2bd36408615f46a6bc227ccb20e7e2ce":{
      "scriptId":"u39"},
    "44e690f7acbe4e979e86d22d1ca79835":{
      "scriptId":"u40"},
    "fded63e23e7542519efa72f261046895":{
      "scriptId":"u41"},
    "646a7f7f5a9049a5887c7dddf18ce62b":{
      "scriptId":"u42"},
    "fed5393b28594c61938099ecc70efce4":{
      "scriptId":"u43"},
    "13408e9b55324ca6b746511fc8394cc4":{
      "scriptId":"u44"},
    "a32b99a0ae004357975523760104a5e0":{
      "scriptId":"u45"},
    "a4db077705654cfc834dba8bccd15c56":{
      "scriptId":"u46"},
    "01240bf259d44a4f997351e2938ba3ad":{
      "scriptId":"u47"},
    "d72e0ca334d041388aeee22651ea2fe0":{
      "scriptId":"u48"},
    "7ead0314f29244dcb044972a5e26a0dd":{
      "scriptId":"u49"},
    "3fda7f74cee6474083147cbd4e3747f4":{
      "scriptId":"u50"},
    "6acc81744d8148debe3a5f3a3b3a1d3d":{
      "scriptId":"u51"},
    "cd46e4fb9e644752aa1041dabd3cf633":{
      "scriptId":"u52"},
    "a3c089afcd9346dcaf343f416c9a2cb8":{
      "scriptId":"u53"},
    "dd8d2313a23442aa83b6dfc7d7907f3a":{
      "scriptId":"u54"},
    "2752bd3bdb9547a0a162f78590440528":{
      "scriptId":"u55"},
    "2badef1f045547538993cd9b79b09cbf":{
      "scriptId":"u56"},
    "21cf77c4df6e4deca3bffa2038102a31":{
      "scriptId":"u57"},
    "3488e2871cd64ddb99504a2ede569266":{
      "scriptId":"u58"},
    "8fe2e16bbe674516abfcefe7f4775399":{
      "scriptId":"u59"},
    "1f66d413d53040ba9d4451bb5816e3a2":{
      "scriptId":"u60"},
    "3a1ff4eefe474b2687edb515899b9b8a":{
      "scriptId":"u61"},
    "e26dd73102f14ed0b3dbed0b3619ba0b":{
      "scriptId":"u62"},
    "360d02cee890428bbb619bd93992813a":{
      "scriptId":"u63"},
    "b4db8ddb4b3e4ab9b238194a33a707f6":{
      "scriptId":"u64"},
    "751dd2acae4b4b2fa71d5860ec648695":{
      "scriptId":"u65"},
    "b1ff7686bdde4d408432aa153755070f":{
      "scriptId":"u66"},
    "1b52aae9ab914caabf5720732597b619":{
      "scriptId":"u67"},
    "7a336c75a5a6475eb7a7fc0400c39a10":{
      "scriptId":"u68"},
    "fb44cf8695b145699b346b8f250b12b8":{
      "scriptId":"u69"},
    "368c3993aaeb467e9c5fd06af1af4b6f":{
      "scriptId":"u70"},
    "c3f193eb76004bdc95f57a77c46f4d44":{
      "scriptId":"u71"},
    "b46f2ed01bfb4660833e2b9cf68bf995":{
      "scriptId":"u72"},
    "1766919edf1449459b8f2170d7a5fcda":{
      "scriptId":"u73"},
    "24ee3fb6976044308a7b3f24a7fd2945":{
      "scriptId":"u74"},
    "af153bb73bfa49d2a2e3e93edc463548":{
      "scriptId":"u75"},
    "c1111ff1e33c4b8ba2eee93295f6104b":{
      "scriptId":"u76"},
    "602a34d176d3450cb5e9934cfeb95146":{
      "scriptId":"u77"},
    "033b5f56951841a7bf90f6f00cc3dcf2":{
      "scriptId":"u78"},
    "d05ba9e5bed442418573a513b463fb52":{
      "scriptId":"u79"},
    "36babdfa3f434e7b93a386e07a296e7a":{
      "scriptId":"u80"},
    "68b55a1dc8cb4e02a7c74cf99b538c19":{
      "scriptId":"u81"},
    "162d80f8521a4ec58b052036be81dca0":{
      "scriptId":"u82"},
    "cb42a9d2bf344048906121a7a73806a0":{
      "scriptId":"u83"},
    "82a4a057c45d4a82ba1a3cd50745f1b8":{
      "scriptId":"u84"},
    "2ca36725ed764f8a80174e67ff1d41d3":{
      "scriptId":"u85"},
    "f05c248426ed4b3891b21c92a9b17214":{
      "scriptId":"u86"},
    "5bcade75486f46b2944f578145592efa":{
      "scriptId":"u87"},
    "616859eec05b4354aa7a35e0fe82fb9b":{
      "scriptId":"u88"},
    "b1f911fc32c44cb59089a1886637fcd9":{
      "scriptId":"u89"},
    "b420fee030a149e684635e478dde3f39":{
      "scriptId":"u90"},
    "36ee4594dc254585a3825a036a68905d":{
      "scriptId":"u91"},
    "80eac26e632540d6a2a03c5255299871":{
      "scriptId":"u92"},
    "bdac98cdb4174b19b4d8a3ea237e3320":{
      "scriptId":"u93"},
    "0a95bcac0bba478481cab5c780467080":{
      "scriptId":"u94"},
    "febb5e48f16947fba98edf8b23761a02":{
      "scriptId":"u95"},
    "1f90262cafd1498998643d1321ce7028":{
      "scriptId":"u96"},
    "c68eb04ebf964335a056fa5014e63686":{
      "scriptId":"u97"},
    "726025adf96d415cb396671e84545eaa":{
      "scriptId":"u98"},
    "e64bef9112e748c2a57ad4fabeb82389":{
      "scriptId":"u99"},
    "4260bbbec34343489db5dcdfe1db24b9":{
      "scriptId":"u100"}}});