$axure.loadCurrentPage({
  "url":"进入游戏.html",
  "generationDate":new Date(1393973822209.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"da6964772807409d839d03089d0cd513",
    "type":"Axure:Page",
    "name":"进入游戏",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c32c37c47fbb4f28871ac2230867836b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF996633},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8325c1399c54673be6716aed7416613",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF996633},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/进入游戏/u0.png"}},
{
          "id":"605e8f5172624e638613dd8429a5e62a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":568},
            "size":{
              "width":520,
              "height":122},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ed806aed5124b35833a56945f31b35b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":568},
                "size":{
                  "width":520,
                  "height":122},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/进入游戏/u2.png"}},
{
          "id":"057c0d0cbe6a4c5e8a9e02915b57bbb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC33FF}}},
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF990066},
            "location":{
              "x":200,
              "y":800},
            "size":{
              "width":250,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF990033},
            "cornerRadiusTopLeft":"9"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a18b5cc646bb4c849b7bfc0e6dbbeec6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCC33FF}}},
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF990066},
                "location":{
                  "x":200,
                  "y":800},
                "size":{
                  "width":250,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF990033},
                "cornerRadiusTopLeft":"9"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 第一次登陆",
                      "target":{
                        "targetType":"page",
                        "url":"第一次登陆.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/进入游戏/u4.png",
            "mouseDown~":"images/进入游戏/u4_mouseDown.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c32c37c47fbb4f28871ac2230867836b":{
      "scriptId":"u0"},
    "d8325c1399c54673be6716aed7416613":{
      "scriptId":"u1"},
    "605e8f5172624e638613dd8429a5e62a":{
      "scriptId":"u2"},
    "5ed806aed5124b35833a56945f31b35b":{
      "scriptId":"u3"},
    "057c0d0cbe6a4c5e8a9e02915b57bbb5":{
      "scriptId":"u4"},
    "a18b5cc646bb4c849b7bfc0e6dbbeec6":{
      "scriptId":"u5"}}});