$axure.loadCurrentPage({
  "url":"战斗页面.html",
  "generationDate":new Date(1393973833212.52),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3366ad5b3e344defacc4b65176d77969",
    "type":"Axure:Page",
    "name":"战斗页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4d1791fff6314fc7a1915bae2961d9dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF996633},
            "size":{
              "width":640,
              "height":1136},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9d119321f86417c9c89f418782b1b01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF996633},
                "size":{
                  "width":640,
                  "height":1136},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物1/u0.png"}},
{
          "id":"a20ff0c79beb4d36afc66f531bc51a38",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":850,
              "y":1036},
            "size":{
              "width":2,
              "height":3},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97cb91ee461047d29a0cbc30c29b3d66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":850,
                  "y":1036},
                "size":{
                  "width":2,
                  "height":3},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u22.png"}},
{
          "id":"6d05e91faba24f7d99ed7e33f772fa85",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":852,
              "y":1036},
            "size":{
              "width":57,
              "height":3},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f11f7841eda4985b29b040c64b0eadf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":852,
                  "y":1036},
                "size":{
                  "width":57,
                  "height":3},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u24.png"}},
{
          "id":"ea911512bf8946dda7ee416ef75c40b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":0,
              "y":138},
            "size":{
              "width":640,
              "height":860}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbd1ea449b334b618673ef59f5e38725",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":138},
                "size":{
                  "width":640,
                  "height":860}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u6.png"}},
{
          "id":"24701599699e4de1bf6b546513c9ae13",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":956},
            "size":{
              "width":180,
              "height":180},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae3e84349f634018ba7e725c5e6aace2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":956},
                "size":{
                  "width":180,
                  "height":180},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u8.png"}},
{
          "id":"301cee2e091745898d47ec11a6eb7f3a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":0},
            "size":{
              "width":180,
              "height":180},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db6e80a71b5947d9a54a656b533e55af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":0},
                "size":{
                  "width":180,
                  "height":180},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u10.png"}},
{
          "id":"44ddc18ab3c14a1291c13dd0909b33b2",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF00},
            "location":{
              "x":350,
              "y":270},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dec10d243a64507b4402a05634bf9cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00},
                "location":{
                  "x":350,
                  "y":270},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u12.png"}},
{
          "id":"07aed11762c343f1bd159ef7fbfb47b3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "opacity":"0.4",
            "location":{
              "x":157,
              "y":877},
            "size":{
              "width":106,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"165372e2c7e1484f8396c91bf49ec9af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.4",
                "location":{
                  "x":157,
                  "y":877},
                "size":{
                  "width":106,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u14.png"}},
{
          "id":"3f7f6d13f5d2496b99d6ae043b63a00c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":900},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0307e1fa83464d5593825bab7e42fb01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":900},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u16.png"}},
{
          "id":"86241f3238164dfba572c6164ce7ee7a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":273,
              "y":390},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"916da5f98ccb4be8a22a8bcb0ac6bb84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":273,
                  "y":390},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u16.png"}},
{
          "id":"d957df083c6f46f18960734111f2e33a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF006600},
            "location":{
              "x":320,
              "y":538},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b528830cf96f40a3b761e2ac71fa70a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006600},
                "location":{
                  "x":320,
                  "y":538},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u20.png"}},
{
          "id":"016fc576928c408eb7a87699c02cf019",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF00},
            "location":{
              "x":203,
              "y":450},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50d37af3aefc40348206aea74a14b239",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00},
                "location":{
                  "x":203,
                  "y":450},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u12.png"}},
{
          "id":"c4f604cb628d427a93073e3ca0a18d9e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":120,
              "y":520},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6453ec78c724941bb073a1720ee1c75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":120,
                  "y":520},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u24.png"}},
{
          "id":"7093586145ab4359bf5e762bf6ff1edd",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF993300},
            "location":{
              "x":450,
              "y":460},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9125c9f20002484d819f745e84844254",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF993300},
                "location":{
                  "x":450,
                  "y":460},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u26.png"}},
{
          "id":"9caec3f3810b45ffb59746d425f94f21",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":203,
              "y":270},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afa1317f78854b828196e4128461c841",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":203,
                  "y":270},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u28.png"}},
{
          "id":"1bdcbe30d34d4cfab67a5ce9456d3d64",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF006600},
            "location":{
              "x":70,
              "y":350},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d9698dbac46496a9450c29f08245b39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006600},
                "location":{
                  "x":70,
                  "y":350},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u20.png"}},
{
          "id":"605b11178b5142849d1611f4bc536cb8",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":140,
              "y":650},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c2ecc7b8a3149379974587fa129db3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":140,
                  "y":650},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u28.png"}},
{
          "id":"7f4e62dee9fb45a3b8a35c08ad033493",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":480.000030517578,
              "y":600},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c7885ac635c4ae3a0d128b545c7a36e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":480.000030517578,
                  "y":600},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u24.png"}},
{
          "id":"4fa6d07f06c24365a469662b5e855e5b",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF993300},
            "location":{
              "x":320,
              "y":710},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4169caec17f4f5391becd6f9464dc8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF993300},
                "location":{
                  "x":320,
                  "y":710},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u26.png"}},
{
          "id":"1407116aa9a14843b09f96fe0ee40d67",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":400,
              "y":180},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4cf6259b75e4d31afef4635a085bfcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":400,
                  "y":180},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u16.png"}},
{
          "id":"59d299f2b43c4da5a975d14e99391fb0",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":640},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e683536861ad4572857dce42efa2ab29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":640},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u16.png"}},
{
          "id":"3990f89d03d54b8f844799efa6d9564a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":0},
            "size":{
              "width":361,
              "height":90},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffeb3048acd2443ba4dd8bd3fbf98784",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":0},
                "size":{
                  "width":361,
                  "height":90},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u42.png"}},
{
          "id":"2ae0584059f7492e8d6f098fa22a014c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":90},
            "size":{
              "width":209,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91c366df15924e8799d7d01362fd6817",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":209,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u44.png"}},
{
          "id":"ff9c857df11042b6b34496c31b59fe2a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":179,
              "y":1048},
            "size":{
              "width":351,
              "height":82},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfb7980d29f0491691c1c8cd12cd0a25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":179,
                  "y":1048},
                "size":{
                  "width":351,
                  "height":82},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u42.png"}},
{
          "id":"7f5cf0342ae54c8ea5e5595441ea9f07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":431,
              "y":998.000061035156},
            "size":{
              "width":209,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"504378a6c7dc46e58d65daefdc1a644e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":431,
                  "y":998.000061035156},
                "size":{
                  "width":209,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u48.png"}},
{
          "id":"a312e15a608e4d74931548a481dd0b92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":209,
              "y":90},
            "size":{
              "width":250,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8c61de71d8142948e599655d7cc109c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":209,
                  "y":90},
                "size":{
                  "width":250,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u50.png"}},
{
          "id":"b34eacdaf87c491ebd78fe3d5e0054ce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-16},
            "size":{
              "width":106,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0e26126e19d41588d926595b99fb049",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-16},
                "size":{
                  "width":106,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 暂停页面",
                      "target":{
                        "targetType":"page",
                        "url":"暂停页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/战斗页面/u52.png"}},
{
          "id":"bb621e6d226544ee880c83e3eab11c29",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":998},
            "size":{
              "width":250,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad937fda5a5c4e759f764a19e7407f1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":998},
                "size":{
                  "width":250,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u50.png"}},
{
          "id":"84187b3761ab4297a535fdd49c26d1f1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":1036},
            "size":{
              "width":106,
              "height":104}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57ff4715a452478fa9810d73a1492bb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":1036},
                "size":{
                  "width":106,
                  "height":104}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 暂停页面",
                      "target":{
                        "targetType":"page",
                        "url":"暂停页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/战斗页面/u52.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4d1791fff6314fc7a1915bae2961d9dc":{
      "scriptId":"u0"},
    "b9d119321f86417c9c89f418782b1b01":{
      "scriptId":"u1"},
    "a20ff0c79beb4d36afc66f531bc51a38":{
      "scriptId":"u2"},
    "97cb91ee461047d29a0cbc30c29b3d66":{
      "scriptId":"u3"},
    "6d05e91faba24f7d99ed7e33f772fa85":{
      "scriptId":"u4"},
    "8f11f7841eda4985b29b040c64b0eadf":{
      "scriptId":"u5"},
    "ea911512bf8946dda7ee416ef75c40b2":{
      "scriptId":"u6"},
    "dbd1ea449b334b618673ef59f5e38725":{
      "scriptId":"u7"},
    "24701599699e4de1bf6b546513c9ae13":{
      "scriptId":"u8"},
    "ae3e84349f634018ba7e725c5e6aace2":{
      "scriptId":"u9"},
    "301cee2e091745898d47ec11a6eb7f3a":{
      "scriptId":"u10"},
    "db6e80a71b5947d9a54a656b533e55af":{
      "scriptId":"u11"},
    "44ddc18ab3c14a1291c13dd0909b33b2":{
      "scriptId":"u12"},
    "4dec10d243a64507b4402a05634bf9cd":{
      "scriptId":"u13"},
    "07aed11762c343f1bd159ef7fbfb47b3":{
      "scriptId":"u14"},
    "165372e2c7e1484f8396c91bf49ec9af":{
      "scriptId":"u15"},
    "3f7f6d13f5d2496b99d6ae043b63a00c":{
      "scriptId":"u16"},
    "0307e1fa83464d5593825bab7e42fb01":{
      "scriptId":"u17"},
    "86241f3238164dfba572c6164ce7ee7a":{
      "scriptId":"u18"},
    "916da5f98ccb4be8a22a8bcb0ac6bb84":{
      "scriptId":"u19"},
    "d957df083c6f46f18960734111f2e33a":{
      "scriptId":"u20"},
    "b528830cf96f40a3b761e2ac71fa70a7":{
      "scriptId":"u21"},
    "016fc576928c408eb7a87699c02cf019":{
      "scriptId":"u22"},
    "50d37af3aefc40348206aea74a14b239":{
      "scriptId":"u23"},
    "c4f604cb628d427a93073e3ca0a18d9e":{
      "scriptId":"u24"},
    "e6453ec78c724941bb073a1720ee1c75":{
      "scriptId":"u25"},
    "7093586145ab4359bf5e762bf6ff1edd":{
      "scriptId":"u26"},
    "9125c9f20002484d819f745e84844254":{
      "scriptId":"u27"},
    "9caec3f3810b45ffb59746d425f94f21":{
      "scriptId":"u28"},
    "afa1317f78854b828196e4128461c841":{
      "scriptId":"u29"},
    "1bdcbe30d34d4cfab67a5ce9456d3d64":{
      "scriptId":"u30"},
    "3d9698dbac46496a9450c29f08245b39":{
      "scriptId":"u31"},
    "605b11178b5142849d1611f4bc536cb8":{
      "scriptId":"u32"},
    "2c2ecc7b8a3149379974587fa129db3b":{
      "scriptId":"u33"},
    "7f4e62dee9fb45a3b8a35c08ad033493":{
      "scriptId":"u34"},
    "1c7885ac635c4ae3a0d128b545c7a36e":{
      "scriptId":"u35"},
    "4fa6d07f06c24365a469662b5e855e5b":{
      "scriptId":"u36"},
    "e4169caec17f4f5391becd6f9464dc8f":{
      "scriptId":"u37"},
    "1407116aa9a14843b09f96fe0ee40d67":{
      "scriptId":"u38"},
    "d4cf6259b75e4d31afef4635a085bfcf":{
      "scriptId":"u39"},
    "59d299f2b43c4da5a975d14e99391fb0":{
      "scriptId":"u40"},
    "e683536861ad4572857dce42efa2ab29":{
      "scriptId":"u41"},
    "3990f89d03d54b8f844799efa6d9564a":{
      "scriptId":"u42"},
    "ffeb3048acd2443ba4dd8bd3fbf98784":{
      "scriptId":"u43"},
    "2ae0584059f7492e8d6f098fa22a014c":{
      "scriptId":"u44"},
    "91c366df15924e8799d7d01362fd6817":{
      "scriptId":"u45"},
    "ff9c857df11042b6b34496c31b59fe2a":{
      "scriptId":"u46"},
    "cfb7980d29f0491691c1c8cd12cd0a25":{
      "scriptId":"u47"},
    "7f5cf0342ae54c8ea5e5595441ea9f07":{
      "scriptId":"u48"},
    "504378a6c7dc46e58d65daefdc1a644e":{
      "scriptId":"u49"},
    "a312e15a608e4d74931548a481dd0b92":{
      "scriptId":"u50"},
    "b8c61de71d8142948e599655d7cc109c":{
      "scriptId":"u51"},
    "b34eacdaf87c491ebd78fe3d5e0054ce":{
      "scriptId":"u52"},
    "e0e26126e19d41588d926595b99fb049":{
      "scriptId":"u53"},
    "bb621e6d226544ee880c83e3eab11c29":{
      "scriptId":"u54"},
    "ad937fda5a5c4e759f764a19e7407f1b":{
      "scriptId":"u55"},
    "84187b3761ab4297a535fdd49c26d1f1":{
      "scriptId":"u56"},
    "57ff4715a452478fa9810d73a1492bb4":{
      "scriptId":"u57"}}});