$axure.loadCurrentPage({
  "url":"check_monster_infor_2.html",
  "generationDate":new Date(1402535712863.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2ebf695c1ec94252917c688d62b14dde",
    "type":"Axure:Page",
    "name":"check monster infor 2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"115f907faf3a4212818328ef4fb9e44d",
          "label":"手机",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":754,
              "height":1478}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49442bda98ed4a828c6bd7f705c8addd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":754,
                  "height":1478}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/手机_u0.png"}},
{
          "id":"71bf53d145ce4d258fc44f9e8af7f044",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":260},
            "size":{
              "width":640,
              "height":960}},
          "adaptiveStyles":{
}},
{
          "id":"02308b426f2b43fbbdce2c4cf9a82363",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":260},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3efcd92381284a68b2aa0467acfc8146",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":260},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u3.png"}},
{
          "id":"59b49d2f0b1d4636af43f9c1b594c768",
          "label":"name",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":270},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"388e0319799243109fd1d37b482d77da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":270},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"0e716f30b0754b1fb72c0896010b0c7c",
          "label":"coin",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":320},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"933a45c69509439e95348a84d12ade2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":320},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"1730c3b9937649a8bf2f2aa212da8580",
          "label":"tips",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":270},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf8033fba3fb45998feff1bdbf875f8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":270},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"34676bc26e9c4b368f9e22c96bc86d12",
          "label":"magic stone",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":320},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beddb423a0944d67a568b19d68feb133",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":320},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If visibility of shopping bar = 假 和 visibility of shopping bar option 1 = 假 和 visibility of shopping bar option 2 = 假 和 visibility of shopping&nbsp; bar option 3 = 假)",
                  "isNewIfGroup":true,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetVisibility",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["25ec19a28c7744728ad0de069038b9ca"]}]},
                      "rightExpr":{
                        "exprType":"booleanLiteral",
                        "value":false}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"&&",
                      "leftExpr":{
                        "exprType":"binaryOp",
                        "op":"==",
                        "leftExpr":{
                          "exprType":"fcall",
                          "functionName":"GetWidgetVisibility",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["0639f3573115435e864d84df1f81802b"]}]},
                        "rightExpr":{
                          "exprType":"booleanLiteral",
                          "value":false}},
                      "rightExpr":{
                        "exprType":"binaryOp",
                        "op":"&&",
                        "leftExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetWidgetVisibility",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["6f7fba5a795346079703d0ab05bacc0d"]}]},
                          "rightExpr":{
                            "exprType":"booleanLiteral",
                            "value":false}},
                        "rightExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetWidgetVisibility",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["2bd36408615f46a6bc227ccb20e7e2ce"]}]},
                          "rightExpr":{
                            "exprType":"booleanLiteral",
                            "value":false}}}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 shopping bar,<br>shopping bar option 1,<br>shopping bar option 2,<br>shopping&nbsp; bar option 3",
                      "objectsToFades":[{
                          "objectPath":["25ec19a28c7744728ad0de069038b9ca"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0639f3573115435e864d84df1f81802b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6f7fba5a795346079703d0ab05bacc0d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2bd36408615f46a6bc227ccb20e7e2ce"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"用例 2<br> (Else If visibility of shopping bar = 真 和 visibility of shopping bar option 1 = 真 和 visibility of shopping bar option 2 = 真 和 visibility of shopping&nbsp; bar option 3 = 真)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetVisibility",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["25ec19a28c7744728ad0de069038b9ca"]}]},
                      "rightExpr":{
                        "exprType":"booleanLiteral",
                        "value":true}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"&&",
                      "leftExpr":{
                        "exprType":"binaryOp",
                        "op":"==",
                        "leftExpr":{
                          "exprType":"fcall",
                          "functionName":"GetWidgetVisibility",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["0639f3573115435e864d84df1f81802b"]}]},
                        "rightExpr":{
                          "exprType":"booleanLiteral",
                          "value":true}},
                      "rightExpr":{
                        "exprType":"binaryOp",
                        "op":"&&",
                        "leftExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetWidgetVisibility",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["6f7fba5a795346079703d0ab05bacc0d"]}]},
                          "rightExpr":{
                            "exprType":"booleanLiteral",
                            "value":true}},
                        "rightExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetWidgetVisibility",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["2bd36408615f46a6bc227ccb20e7e2ce"]}]},
                          "rightExpr":{
                            "exprType":"booleanLiteral",
                            "value":true}}}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 shopping bar,<br>shopping bar option 1,<br>shopping bar option 2,<br>shopping&nbsp; bar option 3",
                      "objectsToFades":[{
                          "objectPath":["25ec19a28c7744728ad0de069038b9ca"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0639f3573115435e864d84df1f81802b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6f7fba5a795346079703d0ab05bacc0d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2bd36408615f46a6bc227ccb20e7e2ce"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"ed501b765e224daf80fcdf8681e23d9e",
          "label":"add more magic stone",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":320},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55217d86e2c34deca49718cd3c309043",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":320},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/add_more_magic_stone_u13.png"}},
{
          "id":"b12348cb66f94dccb3362f2a36cdbe23",
          "label":"friends",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":525,
              "y":270},
            "size":{
              "width":160,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5f24403cb8a453d9b5124e77ea20512",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":525,
                  "y":270},
                "size":{
                  "width":160,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Friends",
                      "target":{
                        "targetType":"page",
                        "url":"friends.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/friends_u15.png"}},
{
          "id":"3583d50ee46c46aeaba6675643678574",
          "label":"actor",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":255,
              "y":615},
            "size":{
              "width":250,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e38294ae3854f168d9029d9fef394b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":255,
                  "y":615},
                "size":{
                  "width":250,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/check_monster_infor_1/actor_u17.png"}},
{
          "id":"25ec19a28c7744728ad0de069038b9ca",
          "label":"shopping bar",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":60,
              "y":600},
            "size":{
              "width":640,
              "height":250},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52567f36c2cf4986ae62885485d5b80c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":60,
                  "y":600},
                "size":{
                  "width":640,
                  "height":250},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/shopping_bar_u95.png"}},
{
          "id":"0639f3573115435e864d84df1f81802b",
          "label":"shopping bar option 1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":75,
              "y":615},
            "size":{
              "width":180,
              "height":220},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3875cfd0e1f4f6d9bb986ad40f376f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":75,
                  "y":615},
                "size":{
                  "width":180,
                  "height":220},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/shopping_bar_option_1_u97.png"}},
{
          "id":"6f7fba5a795346079703d0ab05bacc0d",
          "label":"shopping bar option 2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":270,
              "y":615},
            "size":{
              "width":180,
              "height":220},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e8a8e0bec0e4a7ab5218bc23d363c7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":270,
                  "y":615},
                "size":{
                  "width":180,
                  "height":220},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/shopping_bar_option_1_u97.png"}},
{
          "id":"2bd36408615f46a6bc227ccb20e7e2ce",
          "label":"shopping  bar option 3",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":465,
              "y":615},
            "size":{
              "width":180,
              "height":220},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44e690f7acbe4e979e86d22d1ca79835",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":465,
                  "y":615},
                "size":{
                  "width":180,
                  "height":220},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/shopping_bar_option_1_u97.png"}},
{
          "id":"f04b33b0138446c1b72ce56e75d07fd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":775,
              "y":834},
            "size":{
              "width":15,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1739187973a4423b2e14dbc88c36986",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":775,
                  "y":834},
                "size":{
                  "width":15,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u39.png"}},
{
          "id":"a6834ae9678542cda6185b6979713aa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":860,
              "y":717.5},
            "size":{
              "width":200,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2db78cb44512441d914a745b55a0d608",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":860,
                  "y":717.5},
                "size":{
                  "width":200,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u41.png"}},
{
          "id":"4577efe51faa416fb69e04b0e257f666",
          "label":"buff1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":635,
              "y":465},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f91514369e374e9f9431096de0a4f66b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":635,
                  "y":465},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]},
{
                      "action":"fadeWidget",
                      "description":"显示 information of buff",
                      "objectsToFades":[{
                          "objectPath":["59a26ed7858c404c821be23dbf2c70bc"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1<br> (If visibility of information of buff = 真)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetVisibility",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["59a26ed7858c404c821be23dbf2c70bc"]}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":true}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 information of buff",
                      "objectsToFades":[{
                          "objectPath":["59a26ed7858c404c821be23dbf2c70bc"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "images":{
            "normal~":"images/home/buff1_u45.png"}},
{
          "id":"3912ba96486f4c6186025c009d0ad487",
          "label":"buff2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":635,
              "y":530},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ce345309d504953a57c64bfc1441d47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":635,
                  "y":530},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]},
{
                      "action":"fadeWidget",
                      "description":"显示 information of buff2",
                      "objectsToFades":[{
                          "objectPath":["f4b099ae8dd4461d8284421cc0961a43"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1<br> (If visibility of information of buff2 = 真)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetVisibility",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["f4b099ae8dd4461d8284421cc0961a43"]}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":true}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 information of buff2",
                      "objectsToFades":[{
                          "objectPath":["f4b099ae8dd4461d8284421cc0961a43"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "images":{
            "normal~":"images/home/buff1_u45.png"}},
{
          "id":"59a26ed7858c404c821be23dbf2c70bc",
          "label":"information of buff",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":420,
              "y":465},
            "size":{
              "width":200,
              "height":50},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31a90ebd6d1d4dcabc41ef7aa51675cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":420,
                  "y":465},
                "size":{
                  "width":200,
                  "height":50},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/information_of_buff_u49.png"}},
{
          "id":"f4b099ae8dd4461d8284421cc0961a43",
          "label":"information of buff2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":420,
              "y":530},
            "size":{
              "width":200,
              "height":50},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adafd56787c94d3fa00729998c1c570c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":420,
                  "y":530},
                "size":{
                  "width":200,
                  "height":50},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/information_of_buff_u49.png"}},
{
          "id":"dbd8562f13bc4c339d30df1e1ae0f167",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":1130},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"581b6fa7be1e4a4da3d1447b5513ddae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":1130},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u3.png"}},
{
          "id":"490bb8b1a01443f5b0e677cabf16ce43",
          "label":"Friends list",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":370},
            "size":{
              "width":270,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8ce8064576e45339a062b8a5f589adc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":370},
                "size":{
                  "width":270,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/monster_box/check_information_optation_u125.png"}},
{
          "id":"bfa48fc3a9b5414293c152b450f29e35",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":370},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88edb43ee83e43639b70679565f889b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":370},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 sell monster",
                      "target":{
                        "targetType":"page",
                        "url":"sell_monster.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/world_boss/u73.png"}},
{
          "id":"26f0360f238846708688450444577b4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":1030},
            "size":{
              "width":320,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c68aa1fffb44984933b446c7d996744",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":1030},
                "size":{
                  "width":320,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u67.png"}},
{
          "id":"cbf42675d55240a593b7b9e8879333d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":930},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1627735f18464dd4949d14f88faeb2d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":930},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u3.png"}},
{
          "id":"34f6c51ca2e54552a526782567ac3bd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":930},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d1e4e2b33284a06bb0ed2ac956e2662",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":930},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u65.png"}},
{
          "id":"62cff0d3c0a748ca9db08101635f177a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":1030},
            "size":{
              "width":320,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44fcf3abd46e4f68bffe151f30695008",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":1030},
                "size":{
                  "width":320,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u67.png"}},
{
          "id":"e6751f86543a4d7c9bd21d96ee53da06",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":950},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d413c2acf05f4864a7609cbd08fd4f8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":950},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fighting/u4.png"}},
{
          "id":"841c2f57abe44fbcb06424c10e782645",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":1060},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc9a2d8acdce41b9b5467d68119aa3bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":1060},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/check_monster_infor/u55.png"}},
{
          "id":"c6c6a1ba51ad454bb6a0c7b2f3176058",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":60,
              "y":1030},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38700d9833fa4380a3b6e382666e3180",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":60,
                  "y":1030},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/check_monster_infor/u57.png"}},
{
          "id":"2252b32afe4e460a8b7e52449fabc5ad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":1060},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d85ca6f87ca4dfa905642ad570834a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":1060},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/check_monster_infor/u55.png"}},
{
          "id":"74b139ea7d89484d9c4d8c9869d05f1a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":1060},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9a7e4b991224d9c8be9d834e6222021",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":1060},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/check_monster_infor/u55.png"}},
{
          "id":"11d4766065514ec9a382dd30e7d38de8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":1060},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9daf8a8fea5244d7a23de488a749b2e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":1060},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/check_monster_infor/u55.png"}},
{
          "id":"60e54c4a00bc4198837f70c9cedf5f65",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":1060},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e825442bd418401095727e9ca6029051",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":1060},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/check_monster_infor/u55.png"}},
{
          "id":"7c2784a5ead4416eb989f88b4b6eec30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":380,
              "y":1030},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bd67028bb184fb2be1cb1db6ba8b9cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":380,
                  "y":1030},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/check_monster_infor/u57.png"}},
{
          "id":"f583b369ba2b4953a59e770285aabf59",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":1060},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9489dcadabf64b74b90616dd90075fc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":1060},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/check_monster_infor/u55.png"}},
{
          "id":"d11cca08ade54b76ae833fa4513ccfb8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":1060},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d18e28be1004bb2aed41a774d5e7fde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":1060},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/check_monster_infor/u55.png"}},
{
          "id":"5d96543b0e3343f9b924e00d5f46d238",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":1060},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b374547e58744694bd49a8404fd1248f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":1060},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/check_monster_infor/u55.png"}},
{
          "id":"945c4021f62647c99e14fc47daceea45",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":1060},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55f6a13381504603a11cc6fbd648566d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":1060},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/check_monster_infor/u55.png"}},
{
          "id":"dc1c89a9b76a497c8d413445f7152c5c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":1060},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33eb623829054b3287318e7833777ded",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":1060},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/check_monster_infor/u55.png"}},
{
          "id":"7a203ddb57b4485595d5bf4a1d94c0c1",
          "label":"slot of experience ",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":160,
              "y":990},
            "size":{
              "width":540,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d39cbf3b58ce4a669cb49f429937b0df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":160,
                  "y":990},
                "size":{
                  "width":540,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/check_monster_infor/slot_of_experience__u79.png"}},
{
          "id":"c8561a98ae034dd6ac6189306580b597",
          "label":"experience",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":172.5,
              "y":1000},
            "size":{
              "width":515,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f4b7a2d520d4f48b49d1211ba696681",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":172.5,
                  "y":1000},
                "size":{
                  "width":515,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/check_monster_infor/experience_u81.png"}},
{
          "id":"c68e351e26b448eea580efdcf4eda0c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":930},
            "size":{
              "width":540,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9c54beb579b47a6b3dd47fe3a2cf2a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":930},
                "size":{
                  "width":540,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/check_monster_infor/u83.png"}},
{
          "id":"cf3ce7ec9ff140d2a8d71e1bd94123b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":60,
              "y":1132},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7493ff62d3fa4aea994fe55e74f27b1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":60,
                  "y":1132},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/check_monster_infor/u57.png"}},
{
          "id":"fb82d3a366b540248c9017ab40ecb59d",
          "label":"buff1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":1162},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"032041bc8f4c433ba88c2d88865b45e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":1162},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/buff1_u45.png"}},
{
          "id":"2b6174fe52bc4ead860cfa42ea0c189a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":172,
              "y":1163},
            "size":{
              "width":513,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ee8d2f44c3c4cf480af2ffec79eebc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":172,
                  "y":1163},
                "size":{
                  "width":513,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/check_monster_infor/u89.png"}},
{
          "id":"3375abd8b301451594fd90b09cf8d5b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":943},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46c693df57d74cf59d292c6f7abb6e54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":943},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"308ea40e42b942b68f3689de2cac6db4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":300,
              "y":930},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e187a6305bf4ea38da9a0fc816eb0c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":300,
                  "y":930},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30427d25849944febbcd563d1cd4c171",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":300,
              "y":958},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9151d5268b9d4e599760ebad29f3feb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":300,
                  "y":958},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eab6f0e8b4c04a0ebce54cb1a1447b5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":420,
              "y":960},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47c74c7b9a30426c94a0477e7fb99358",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":420,
                  "y":960},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38462c1b96c34395bc9930afd00ae221",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":420,
              "y":930},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c661696691a14df898c3cf5d7a5dabbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":420,
                  "y":930},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eed3997b788c44879f529adf26c30225",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":541,
              "y":960},
            "size":{
              "width":140,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24a8b735ae974ad783a2d358516b7aca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":541,
                  "y":960},
                "size":{
                  "width":140,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c834b4e5a2ac4ca28adac51b8307d875",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":541,
              "y":930},
            "size":{
              "width":140,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0e77c1c197a4885b3edde5ed0347e18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":541,
                  "y":930},
                "size":{
                  "width":140,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5578c3f78b3d461fa67cbe2411abb6df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":970},
            "size":{
              "width":40,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cceae1fa5ca04c6aacd40821f9c0af66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":820,
                  "y":970},
                "size":{
                  "width":40,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/check_monster_infor/u105.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "115f907faf3a4212818328ef4fb9e44d":{
      "scriptId":"u0"},
    "49442bda98ed4a828c6bd7f705c8addd":{
      "scriptId":"u1"},
    "71bf53d145ce4d258fc44f9e8af7f044":{
      "scriptId":"u2"},
    "02308b426f2b43fbbdce2c4cf9a82363":{
      "scriptId":"u3"},
    "3efcd92381284a68b2aa0467acfc8146":{
      "scriptId":"u4"},
    "59b49d2f0b1d4636af43f9c1b594c768":{
      "scriptId":"u5"},
    "388e0319799243109fd1d37b482d77da":{
      "scriptId":"u6"},
    "0e716f30b0754b1fb72c0896010b0c7c":{
      "scriptId":"u7"},
    "933a45c69509439e95348a84d12ade2f":{
      "scriptId":"u8"},
    "1730c3b9937649a8bf2f2aa212da8580":{
      "scriptId":"u9"},
    "bf8033fba3fb45998feff1bdbf875f8b":{
      "scriptId":"u10"},
    "34676bc26e9c4b368f9e22c96bc86d12":{
      "scriptId":"u11"},
    "beddb423a0944d67a568b19d68feb133":{
      "scriptId":"u12"},
    "ed501b765e224daf80fcdf8681e23d9e":{
      "scriptId":"u13"},
    "55217d86e2c34deca49718cd3c309043":{
      "scriptId":"u14"},
    "b12348cb66f94dccb3362f2a36cdbe23":{
      "scriptId":"u15"},
    "f5f24403cb8a453d9b5124e77ea20512":{
      "scriptId":"u16"},
    "3583d50ee46c46aeaba6675643678574":{
      "scriptId":"u17"},
    "5e38294ae3854f168d9029d9fef394b0":{
      "scriptId":"u18"},
    "25ec19a28c7744728ad0de069038b9ca":{
      "scriptId":"u19"},
    "52567f36c2cf4986ae62885485d5b80c":{
      "scriptId":"u20"},
    "0639f3573115435e864d84df1f81802b":{
      "scriptId":"u21"},
    "f3875cfd0e1f4f6d9bb986ad40f376f8":{
      "scriptId":"u22"},
    "6f7fba5a795346079703d0ab05bacc0d":{
      "scriptId":"u23"},
    "2e8a8e0bec0e4a7ab5218bc23d363c7d":{
      "scriptId":"u24"},
    "2bd36408615f46a6bc227ccb20e7e2ce":{
      "scriptId":"u25"},
    "44e690f7acbe4e979e86d22d1ca79835":{
      "scriptId":"u26"},
    "f04b33b0138446c1b72ce56e75d07fd8":{
      "scriptId":"u27"},
    "f1739187973a4423b2e14dbc88c36986":{
      "scriptId":"u28"},
    "a6834ae9678542cda6185b6979713aa8":{
      "scriptId":"u29"},
    "2db78cb44512441d914a745b55a0d608":{
      "scriptId":"u30"},
    "4577efe51faa416fb69e04b0e257f666":{
      "scriptId":"u31"},
    "f91514369e374e9f9431096de0a4f66b":{
      "scriptId":"u32"},
    "3912ba96486f4c6186025c009d0ad487":{
      "scriptId":"u33"},
    "4ce345309d504953a57c64bfc1441d47":{
      "scriptId":"u34"},
    "59a26ed7858c404c821be23dbf2c70bc":{
      "scriptId":"u35"},
    "31a90ebd6d1d4dcabc41ef7aa51675cb":{
      "scriptId":"u36"},
    "f4b099ae8dd4461d8284421cc0961a43":{
      "scriptId":"u37"},
    "adafd56787c94d3fa00729998c1c570c":{
      "scriptId":"u38"},
    "dbd8562f13bc4c339d30df1e1ae0f167":{
      "scriptId":"u39"},
    "581b6fa7be1e4a4da3d1447b5513ddae":{
      "scriptId":"u40"},
    "490bb8b1a01443f5b0e677cabf16ce43":{
      "scriptId":"u41"},
    "d8ce8064576e45339a062b8a5f589adc":{
      "scriptId":"u42"},
    "bfa48fc3a9b5414293c152b450f29e35":{
      "scriptId":"u43"},
    "88edb43ee83e43639b70679565f889b6":{
      "scriptId":"u44"},
    "26f0360f238846708688450444577b4b":{
      "scriptId":"u45"},
    "2c68aa1fffb44984933b446c7d996744":{
      "scriptId":"u46"},
    "cbf42675d55240a593b7b9e8879333d0":{
      "scriptId":"u47"},
    "1627735f18464dd4949d14f88faeb2d8":{
      "scriptId":"u48"},
    "34f6c51ca2e54552a526782567ac3bd8":{
      "scriptId":"u49"},
    "0d1e4e2b33284a06bb0ed2ac956e2662":{
      "scriptId":"u50"},
    "62cff0d3c0a748ca9db08101635f177a":{
      "scriptId":"u51"},
    "44fcf3abd46e4f68bffe151f30695008":{
      "scriptId":"u52"},
    "e6751f86543a4d7c9bd21d96ee53da06":{
      "scriptId":"u53"},
    "d413c2acf05f4864a7609cbd08fd4f8b":{
      "scriptId":"u54"},
    "841c2f57abe44fbcb06424c10e782645":{
      "scriptId":"u55"},
    "bc9a2d8acdce41b9b5467d68119aa3bc":{
      "scriptId":"u56"},
    "c6c6a1ba51ad454bb6a0c7b2f3176058":{
      "scriptId":"u57"},
    "38700d9833fa4380a3b6e382666e3180":{
      "scriptId":"u58"},
    "2252b32afe4e460a8b7e52449fabc5ad":{
      "scriptId":"u59"},
    "6d85ca6f87ca4dfa905642ad570834a5":{
      "scriptId":"u60"},
    "74b139ea7d89484d9c4d8c9869d05f1a":{
      "scriptId":"u61"},
    "c9a7e4b991224d9c8be9d834e6222021":{
      "scriptId":"u62"},
    "11d4766065514ec9a382dd30e7d38de8":{
      "scriptId":"u63"},
    "9daf8a8fea5244d7a23de488a749b2e2":{
      "scriptId":"u64"},
    "60e54c4a00bc4198837f70c9cedf5f65":{
      "scriptId":"u65"},
    "e825442bd418401095727e9ca6029051":{
      "scriptId":"u66"},
    "7c2784a5ead4416eb989f88b4b6eec30":{
      "scriptId":"u67"},
    "4bd67028bb184fb2be1cb1db6ba8b9cb":{
      "scriptId":"u68"},
    "f583b369ba2b4953a59e770285aabf59":{
      "scriptId":"u69"},
    "9489dcadabf64b74b90616dd90075fc4":{
      "scriptId":"u70"},
    "d11cca08ade54b76ae833fa4513ccfb8":{
      "scriptId":"u71"},
    "4d18e28be1004bb2aed41a774d5e7fde":{
      "scriptId":"u72"},
    "5d96543b0e3343f9b924e00d5f46d238":{
      "scriptId":"u73"},
    "b374547e58744694bd49a8404fd1248f":{
      "scriptId":"u74"},
    "945c4021f62647c99e14fc47daceea45":{
      "scriptId":"u75"},
    "55f6a13381504603a11cc6fbd648566d":{
      "scriptId":"u76"},
    "dc1c89a9b76a497c8d413445f7152c5c":{
      "scriptId":"u77"},
    "33eb623829054b3287318e7833777ded":{
      "scriptId":"u78"},
    "7a203ddb57b4485595d5bf4a1d94c0c1":{
      "scriptId":"u79"},
    "d39cbf3b58ce4a669cb49f429937b0df":{
      "scriptId":"u80"},
    "c8561a98ae034dd6ac6189306580b597":{
      "scriptId":"u81"},
    "8f4b7a2d520d4f48b49d1211ba696681":{
      "scriptId":"u82"},
    "c68e351e26b448eea580efdcf4eda0c5":{
      "scriptId":"u83"},
    "e9c54beb579b47a6b3dd47fe3a2cf2a1":{
      "scriptId":"u84"},
    "cf3ce7ec9ff140d2a8d71e1bd94123b2":{
      "scriptId":"u85"},
    "7493ff62d3fa4aea994fe55e74f27b1c":{
      "scriptId":"u86"},
    "fb82d3a366b540248c9017ab40ecb59d":{
      "scriptId":"u87"},
    "032041bc8f4c433ba88c2d88865b45e2":{
      "scriptId":"u88"},
    "2b6174fe52bc4ead860cfa42ea0c189a":{
      "scriptId":"u89"},
    "0ee8d2f44c3c4cf480af2ffec79eebc1":{
      "scriptId":"u90"},
    "3375abd8b301451594fd90b09cf8d5b4":{
      "scriptId":"u91"},
    "46c693df57d74cf59d292c6f7abb6e54":{
      "scriptId":"u92"},
    "308ea40e42b942b68f3689de2cac6db4":{
      "scriptId":"u93"},
    "2e187a6305bf4ea38da9a0fc816eb0c2":{
      "scriptId":"u94"},
    "30427d25849944febbcd563d1cd4c171":{
      "scriptId":"u95"},
    "9151d5268b9d4e599760ebad29f3feb9":{
      "scriptId":"u96"},
    "eab6f0e8b4c04a0ebce54cb1a1447b5f":{
      "scriptId":"u97"},
    "47c74c7b9a30426c94a0477e7fb99358":{
      "scriptId":"u98"},
    "38462c1b96c34395bc9930afd00ae221":{
      "scriptId":"u99"},
    "c661696691a14df898c3cf5d7a5dabbe":{
      "scriptId":"u100"},
    "eed3997b788c44879f529adf26c30225":{
      "scriptId":"u101"},
    "24a8b735ae974ad783a2d358516b7aca":{
      "scriptId":"u102"},
    "c834b4e5a2ac4ca28adac51b8307d875":{
      "scriptId":"u103"},
    "b0e77c1c197a4885b3edde5ed0347e18":{
      "scriptId":"u104"},
    "5578c3f78b3d461fa67cbe2411abb6df":{
      "scriptId":"u105"},
    "cceae1fa5ca04c6aacd40821f9c0af66":{
      "scriptId":"u106"}}});