$axure.loadCurrentPage({
  "url":"水.html",
  "generationDate":new Date(1393973822742.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2c7ef09a36214db08e2ccdabed37872f",
    "type":"Axure:Page",
    "name":"水",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4d1791fff6314fc7a1915bae2961d9dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF996633},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9d119321f86417c9c89f418782b1b01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF996633},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/进入游戏/u0.png"}},
{
          "id":"29512d8b18734995bb135a45b5a7645b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF85E0C2},
            "location":{
              "x":0,
              "y":40},
            "size":{
              "width":640,
              "height":1100},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fe4c6ad892340d9aeea5792dec11b0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF85E0C2},
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":640,
                  "height":1100},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一次选择宠物/u2.png"}},
{
          "id":"a967c149001548c2ae60f651e32c3fad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF990099},
            "location":{
              "x":1,
              "y":0},
            "size":{
              "width":640,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b4b9b0100f247d88f9097d4bc1fdac3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF990099},
                "location":{
                  "x":1,
                  "y":0},
                "size":{
                  "width":640,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一次登陆/u4.png"}},
{
          "id":"310f5c2d5d3542deb117278520873b44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":210,
              "y":70},
            "size":{
              "width":221,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0ff7d8aed9b432ca28f883098e3c101",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":210,
                  "y":70},
                "size":{
                  "width":221,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"692bae6703344094ac6f541c0b333de6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":135},
            "size":{
              "width":80,
              "height":685}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7688385e0ffc4df58ea84554d8213ed6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":135},
                "size":{
                  "width":80,
                  "height":685}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 金",
                      "target":{
                        "targetType":"page",
                        "url":"金.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/第一次选择宠物/u8.png"}},
{
          "id":"56db182ae5ad4ab5992f99e63323e629",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":132.5},
            "size":{
              "width":260,
              "height":690}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af415da9e3b447cbba749d1fa2929eb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":132.5},
                "size":{
                  "width":260,
                  "height":690}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一次选择宠物/u10.png"}},
{
          "id":"f6bc46dc94f648b192e885fb8aed946b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":135},
            "size":{
              "width":80,
              "height":685}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"679dcceacd944680b93086d38d1787dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":135},
                "size":{
                  "width":80,
                  "height":685}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 第一次选择宠物",
                      "target":{
                        "targetType":"page",
                        "url":"第一次选择宠物.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/第一次选择宠物/u8.png"}},
{
          "id":"4fad397554994e0db3af0dd4f847aa97",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":1020},
            "size":{
              "width":390,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe4b0976dad3499e916f0fd60a5260f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":1020},
                "size":{
                  "width":390,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一次选择宠物/u14.png"}},
{
          "id":"18ce3d341a754a3c8ac9c1bf44095560",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":1020},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a5a427eb5504919b0069a4314031a18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":1020},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主菜单",
                      "target":{
                        "targetType":"page",
                        "url":"主菜单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/第一次选择宠物/u16.png"}},
{
          "id":"84fcf00947c947c4afc2a66e15d8de15",
          "label":"火",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "mouseDown":{
},
              "selected":{
                "opacity":"0.5",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":490,
              "y":740},
            "size":{
              "width":80,
              "height":80},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"485e069730ff4d4cab28e1c06e73a3bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "mouseDown":{
},
                  "selected":{
                    "opacity":"0.5",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":490,
                  "y":740},
                "size":{
                  "width":80,
                  "height":80},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一次选择宠物/火_u18.png",
            "selected~":"images/第一次选择宠物/火_u18_selected.png",
            "mouseOver~":"images/第一次选择宠物/火_u18_selected.png"}},
{
          "id":"c60846f77ea6450ead89a6da59e7d835",
          "label":"水",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "selected":{
                "opacity":"0.5",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":275,
              "y":740},
            "size":{
              "width":80,
              "height":80},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a91575d3536f4c1ba64407e25ddb5eb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "selected":{
                    "opacity":"0.5",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":275,
                  "y":740},
                "size":{
                  "width":80,
                  "height":80},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一次选择宠物/水_u22.png",
            "selected~":"images/第一次选择宠物/水_u22_selected.png",
            "mouseOver~":"images/第一次选择宠物/水_u22_selected.png"}},
{
          "id":"92f80b5ae0e044ee858b7d7f38ed739c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":832},
            "size":{
              "width":510,
              "height":178}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec8fe24720374e9db5802fa2252b97ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":832},
                "size":{
                  "width":510,
                  "height":178}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一次选择宠物/u24.png"}},
{
          "id":"56b82b25b44743cd8de221e85102b089",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":428},
            "size":{
              "width":170,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1f2aab107574e7ba713afc85dff1b59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":428},
                "size":{
                  "width":170,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 金",
                      "target":{
                        "targetType":"page",
                        "url":"金.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/第一次选择宠物/u26.png"}},
{
          "id":"500d373306ff40cca35f347fa3c36c21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":471,
              "y":427.5},
            "size":{
              "width":170,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"196625b7bb6743bc93d09e85d57c7d8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":471,
                  "y":427.5},
                "size":{
                  "width":170,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 第一次选择宠物",
                      "target":{
                        "targetType":"page",
                        "url":"第一次选择宠物.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/第一次选择宠物/u28.png"}},
{
          "id":"d335602801cd4e92b66754742175c07b",
          "label":"金",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "selected":{
                "opacity":"0.5",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":60,
              "y":740},
            "size":{
              "width":80,
              "height":80},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ee7ba3163b34a4aafb290d4bb724090",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "selected":{
                    "opacity":"0.5",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":60,
                  "y":740},
                "size":{
                  "width":80,
                  "height":80},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/水/金_u28.png",
            "selected~":"images/水/金_u28_selected.png",
            "mouseOver~":"images/水/金_u28_selected.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4d1791fff6314fc7a1915bae2961d9dc":{
      "scriptId":"u0"},
    "b9d119321f86417c9c89f418782b1b01":{
      "scriptId":"u1"},
    "29512d8b18734995bb135a45b5a7645b":{
      "scriptId":"u2"},
    "6fe4c6ad892340d9aeea5792dec11b0f":{
      "scriptId":"u3"},
    "a967c149001548c2ae60f651e32c3fad":{
      "scriptId":"u4"},
    "4b4b9b0100f247d88f9097d4bc1fdac3":{
      "scriptId":"u5"},
    "310f5c2d5d3542deb117278520873b44":{
      "scriptId":"u6"},
    "a0ff7d8aed9b432ca28f883098e3c101":{
      "scriptId":"u7"},
    "692bae6703344094ac6f541c0b333de6":{
      "scriptId":"u8"},
    "7688385e0ffc4df58ea84554d8213ed6":{
      "scriptId":"u9"},
    "56db182ae5ad4ab5992f99e63323e629":{
      "scriptId":"u10"},
    "af415da9e3b447cbba749d1fa2929eb3":{
      "scriptId":"u11"},
    "f6bc46dc94f648b192e885fb8aed946b":{
      "scriptId":"u12"},
    "679dcceacd944680b93086d38d1787dd":{
      "scriptId":"u13"},
    "4fad397554994e0db3af0dd4f847aa97":{
      "scriptId":"u14"},
    "fe4b0976dad3499e916f0fd60a5260f5":{
      "scriptId":"u15"},
    "18ce3d341a754a3c8ac9c1bf44095560":{
      "scriptId":"u16"},
    "6a5a427eb5504919b0069a4314031a18":{
      "scriptId":"u17"},
    "84fcf00947c947c4afc2a66e15d8de15":{
      "scriptId":"u18"},
    "485e069730ff4d4cab28e1c06e73a3bf":{
      "scriptId":"u19"},
    "c60846f77ea6450ead89a6da59e7d835":{
      "scriptId":"u20"},
    "a91575d3536f4c1ba64407e25ddb5eb4":{
      "scriptId":"u21"},
    "92f80b5ae0e044ee858b7d7f38ed739c":{
      "scriptId":"u22"},
    "ec8fe24720374e9db5802fa2252b97ee":{
      "scriptId":"u23"},
    "56b82b25b44743cd8de221e85102b089":{
      "scriptId":"u24"},
    "e1f2aab107574e7ba713afc85dff1b59":{
      "scriptId":"u25"},
    "500d373306ff40cca35f347fa3c36c21":{
      "scriptId":"u26"},
    "196625b7bb6743bc93d09e85d57c7d8b":{
      "scriptId":"u27"},
    "d335602801cd4e92b66754742175c07b":{
      "scriptId":"u28"},
    "7ee7ba3163b34a4aafb290d4bb724090":{
      "scriptId":"u29"}}});