$axure.loadCurrentPage({
  "url":"玩家拖动己方小球前.html",
  "generationDate":new Date(1397832004305.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bacdd5d42121418f90c1d512ad7fcf66",
    "type":"Axure:Page",
    "name":"玩家拖动己方小球前",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"03c5a63b34a24f529b1c26405300df30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d683202ee8d041d68300b6e51ddbf775",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/玩家拖动己方小球前/u0.png"}},
{
          "id":"5f9799cfd46b4346b65ee8a63379e6f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8886fdbab13430e8c54b733c04887c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":640,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/玩家拖动己方小球前/u2.png"}},
{
          "id":"b89f1c53bd544faeb92977b3736f874e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":1020},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a43ced345b4c4f2da5b08baf13b46c6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":1020},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/玩家拖动己方小球前/u4.png"}},
{
          "id":"e2200cc9a26744c18026c0e4f5dc50ab",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":1020},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9297349ceb624291a7c6efce513b6b8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":1020},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/玩家拖动己方小球前/u4.png"}},
{
          "id":"4d473c62c9a04a04b750ddc2b4fa4986",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":1020},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f91b2e90a7c465b9bb479dba609904b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":1020},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/玩家拖动己方小球前/u4.png"}},
{
          "id":"ea70c7e9fd1544f0890e5f88f1f99879",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":1020},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89e34707c6f84566906646203af3cc9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":1020},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/玩家拖动己方小球前/u4.png"}},
{
          "id":"9cd60223a1ec49a1a5c838a74552ca2f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":1020},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f9d0da4b53346e48d719b49c1a4e970",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":1020},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/玩家拖动己方小球前/u4.png"}},
{
          "id":"9ed263032bf649a4b0cf3e4920b2714a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":810},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13e489a847f2494eb9ba64f9efa2f362",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":810},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/玩家拖动己方小球前/u14.png"}},
{
          "id":"8bf02e7fdc084356b5bc3d8c53ab9427",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":20},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efabcc8711504112bb5b531dcfc3b78b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":20},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/玩家拖动己方小球前/u16.png"}},
{
          "id":"b4300c1006754c69997a829fc96b71eb",
          "label":"宠物",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":940},
            "size":{
              "width":200,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onPanelStateChange":{
              "description":"OnPanelStateChange",
              "cases":[{
                  "description":"用例 1<br> (If state of This = 状态2 或 state of This = 状态3)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"||",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetPanelState",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":true,
                            "isFocused":false,
                            "isTarget":false}]},
                      "rightExpr":{
                        "exprType":"panelDiagramLiteral",
                        "panelPath":["b4300c1006754c69997a829fc96b71eb"],
                        "panelIndex":1}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetPanelState",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":true,
                            "isFocused":false,
                            "isTarget":false}]},
                      "rightExpr":{
                        "exprType":"panelDiagramLiteral",
                        "panelPath":["b4300c1006754c69997a829fc96b71eb"],
                        "panelIndex":2}}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 文字 to State1 显示隐藏,<br>是 to State1 显示隐藏,<br>否 to State1 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["073ed0164ed646ce8d701ce361138ef7"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "compress":false}}},
{
                          "panelPath":["83e2bd682b864c48aa38f3440375c618"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "compress":false}}},
{
                          "panelPath":["f849fe69cea1413b9e0950592c270aef"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "compress":false}}}]}]},
{
                  "description":"用例 2<br> (Else If state of This = 状态1)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["b4300c1006754c69997a829fc96b71eb"],
                      "panelIndex":0}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 文字 to state2,<br>是 to state,<br>否 to state2",
                      "panelsToStates":[{
                          "panelPath":["073ed0164ed646ce8d701ce361138ef7"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}},
{
                          "panelPath":["83e2bd682b864c48aa38f3440375c618"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}},
{
                          "panelPath":["f849fe69cea1413b9e0950592c270aef"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]},
            "onSwipeLeft":{
              "description":"OnSwipeLeft",
              "cases":[{
                  "description":"用例 1<br> (If state of This = 状态1)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["b4300c1006754c69997a829fc96b71eb"],
                      "panelIndex":0}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 宠物 to 状态3 向右滑动 in 500ms",
                      "panelsToStates":[{
                          "panelPath":["b4300c1006754c69997a829fc96b71eb"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":3,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateIn":{
                                "easing":"slideRight",
                                "duration":500},
                              "compress":false}}}]}]},
{
                  "description":"用例 2<br> (Else If state of This = 状态3)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["b4300c1006754c69997a829fc96b71eb"],
                      "panelIndex":2}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 宠物 to 状态2 向右滑动 in 300ms",
                      "panelsToStates":[{
                          "panelPath":["b4300c1006754c69997a829fc96b71eb"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateIn":{
                                "easing":"slideRight",
                                "duration":300},
                              "compress":false}}}]}]},
{
                  "description":"用例 3<br> (Else If state of This = 状态2)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["b4300c1006754c69997a829fc96b71eb"],
                      "panelIndex":1}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 宠物 to 状态1 向右滑动 in 300ms",
                      "panelsToStates":[{
                          "panelPath":["b4300c1006754c69997a829fc96b71eb"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateIn":{
                                "easing":"slideRight",
                                "duration":300},
                              "compress":false}}}]}]}]},
            "onSwipeRight":{
              "description":"OnSwipeRight",
              "cases":[{
                  "description":"用例 1<br> (If state of This = 状态1)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["b4300c1006754c69997a829fc96b71eb"],
                      "panelIndex":0}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 宠物 to 状态2 向左滑动 in 300ms",
                      "panelsToStates":[{
                          "panelPath":["b4300c1006754c69997a829fc96b71eb"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":300},
                              "compress":false}}}]}]},
{
                  "description":"用例 2<br> (Else If state of This = 状态2)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["b4300c1006754c69997a829fc96b71eb"],
                      "panelIndex":1}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 宠物 to 状态3 向左滑动 in 500ms",
                      "panelsToStates":[{
                          "panelPath":["b4300c1006754c69997a829fc96b71eb"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":3,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]}]},
{
                  "description":"用例 3<br> (Else If state of This = 状态3)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["b4300c1006754c69997a829fc96b71eb"],
                      "panelIndex":2}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 宠物 to 状态1 向左滑动 in 500ms",
                      "panelsToStates":[{
                          "panelPath":["b4300c1006754c69997a829fc96b71eb"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"19920564f0294bf1a35080c904e697f6",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"467ebff8f2ef4f64af9947754bcf56c5",
                  "label":"出战宠物",
                  "parentDynamicPanel":"b4300c1006754c69997a829fc96b71eb",
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5895dcca3d6b4cc6b68e8b0928337f6a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b4300c1006754c69997a829fc96b71eb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/玩家拖动己方小球前/出战宠物_u19.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"4dd2575eee3c464bb4af3fd5481bb933",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"74696d4a88e049808d9b907582d64d52",
                  "label":"出战宠物",
                  "parentDynamicPanel":"b4300c1006754c69997a829fc96b71eb",
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bf07c0f1c4cc4e43a6521b6d7b72a958",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b4300c1006754c69997a829fc96b71eb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/玩家拖动己方小球前/出战宠物_u19.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"bf7ead51f0564261ba63155c26e6e3d3",
              "label":"状态3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5fac95143492434db5588963e0c52452",
                  "label":"出战宠物",
                  "parentDynamicPanel":"b4300c1006754c69997a829fc96b71eb",
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b7bd3150d2224c9790f66b7069121296",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b4300c1006754c69997a829fc96b71eb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/玩家拖动己方小球前/出战宠物_u19.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"073ed0164ed646ce8d701ce361138ef7",
          "label":"文字",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":220,
              "y":900},
            "size":{
              "width":200,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"afe1562cefb54fef87cd45ed856198b6",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3d6135fbc6ac4b129791f500bb53c7ad",
                  "label":"文字提示",
                  "parentDynamicPanel":"073ed0164ed646ce8d701ce361138ef7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5f40334f3e344bd489cfab487507bcbe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"073ed0164ed646ce8d701ce361138ef7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/玩家拖动己方小球前/文字提示_u26.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"e710ef6269304aa09024bd6dc991ec48",
              "label":"state2",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"83e2bd682b864c48aa38f3440375c618",
          "label":"是",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":10,
              "y":945},
            "size":{
              "width":200,
              "height":50},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"6963c257410748228d13247d0081b0e3",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d17082c476044a788093d772cb20c82a",
                  "label":"是",
                  "parentDynamicPanel":"83e2bd682b864c48aa38f3440375c618",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"09e06465370a4ecd8c1e85cf6a3922d5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83e2bd682b864c48aa38f3440375c618",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/玩家拖动己方小球前/是_u29.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"b3a58bf0baf34ea3a91c90fe64282289",
              "label":"state",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"f849fe69cea1413b9e0950592c270aef",
          "label":"否",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":430,
              "y":945},
            "size":{
              "width":200,
              "height":50},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"c9a20d0038e2489dac519bcb5b3dd5f6",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2e75aea157984c84bb1cf71ff85db73d",
                  "label":"否",
                  "parentDynamicPanel":"f849fe69cea1413b9e0950592c270aef",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6ec513a71bd4472aaad98023e2e11504",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f849fe69cea1413b9e0950592c270aef",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/玩家拖动己方小球前/是_u29.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"61c508a941154309a8b09fd7a365ac8a",
              "label":"state2",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"a9d40a9f79f64f9c9c5b60b1304939ae",
          "label":"回合时间",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":false,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":57,
              "y":784},
            "size":{
              "width":107,
              "height":59},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06f446e3eeae414db0939702e09bb4b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":57,
                  "y":784},
                "size":{
                  "width":107,
                  "height":59},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/玩家拖动己方小球前/回合时间_u34.png"}},
{
          "id":"a8d754bd6d834a049f08ab9f63a625a0",
          "label":"边框1",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":false,
          "style":{
            "location":{
              "x":70,
              "y":800},
            "size":{
              "width":80,
              "height":80},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"899bb1d655244be19e9dbf35d6ee638b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":70,
                  "y":800},
                "size":{
                  "width":80,
                  "height":80},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/玩家拖动己方小球前/边框1_u36.png"}},
{
          "id":"e35866a0d870406897fb002d6636ebd1",
          "label":"己方小球",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":810},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3358df30e20646f8aa315e4ef1ce4a50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":810},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 边框1,<br>回合时间",
                      "objectsToFades":[{
                          "objectPath":["a8d754bd6d834a049f08ab9f63a625a0"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["a9d40a9f79f64f9c9c5b60b1304939ae"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 回合时间,<br>边框1",
                      "objectsToFades":[{
                          "objectPath":["a9d40a9f79f64f9c9c5b60b1304939ae"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["a8d754bd6d834a049f08ab9f63a625a0"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/玩家拖动己方小球前/u14.png"}},
{
          "id":"d73a051316ce45b3a1d7886e9e0ecce1",
          "label":"边框2",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":false,
          "style":{
            "location":{
              "x":57,
              "y":784},
            "size":{
              "width":106,
              "height":106},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c40e063003a44bb19acbfea241d12535",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":57,
                  "y":784},
                "size":{
                  "width":106,
                  "height":106},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/玩家拖动己方小球前/边框2_u40.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "03c5a63b34a24f529b1c26405300df30":{
      "scriptId":"u0"},
    "d683202ee8d041d68300b6e51ddbf775":{
      "scriptId":"u1"},
    "5f9799cfd46b4346b65ee8a63379e6f2":{
      "scriptId":"u2"},
    "a8886fdbab13430e8c54b733c04887c7":{
      "scriptId":"u3"},
    "b89f1c53bd544faeb92977b3736f874e":{
      "scriptId":"u4"},
    "a43ced345b4c4f2da5b08baf13b46c6b":{
      "scriptId":"u5"},
    "e2200cc9a26744c18026c0e4f5dc50ab":{
      "scriptId":"u6"},
    "9297349ceb624291a7c6efce513b6b8c":{
      "scriptId":"u7"},
    "4d473c62c9a04a04b750ddc2b4fa4986":{
      "scriptId":"u8"},
    "5f91b2e90a7c465b9bb479dba609904b":{
      "scriptId":"u9"},
    "ea70c7e9fd1544f0890e5f88f1f99879":{
      "scriptId":"u10"},
    "89e34707c6f84566906646203af3cc9d":{
      "scriptId":"u11"},
    "9cd60223a1ec49a1a5c838a74552ca2f":{
      "scriptId":"u12"},
    "5f9d0da4b53346e48d719b49c1a4e970":{
      "scriptId":"u13"},
    "9ed263032bf649a4b0cf3e4920b2714a":{
      "scriptId":"u14"},
    "13e489a847f2494eb9ba64f9efa2f362":{
      "scriptId":"u15"},
    "8bf02e7fdc084356b5bc3d8c53ab9427":{
      "scriptId":"u16"},
    "efabcc8711504112bb5b531dcfc3b78b":{
      "scriptId":"u17"},
    "b4300c1006754c69997a829fc96b71eb":{
      "scriptId":"u18"},
    "467ebff8f2ef4f64af9947754bcf56c5":{
      "scriptId":"u19"},
    "5895dcca3d6b4cc6b68e8b0928337f6a":{
      "scriptId":"u20"},
    "74696d4a88e049808d9b907582d64d52":{
      "scriptId":"u21"},
    "bf07c0f1c4cc4e43a6521b6d7b72a958":{
      "scriptId":"u22"},
    "5fac95143492434db5588963e0c52452":{
      "scriptId":"u23"},
    "b7bd3150d2224c9790f66b7069121296":{
      "scriptId":"u24"},
    "073ed0164ed646ce8d701ce361138ef7":{
      "scriptId":"u25"},
    "3d6135fbc6ac4b129791f500bb53c7ad":{
      "scriptId":"u26"},
    "5f40334f3e344bd489cfab487507bcbe":{
      "scriptId":"u27"},
    "83e2bd682b864c48aa38f3440375c618":{
      "scriptId":"u28"},
    "d17082c476044a788093d772cb20c82a":{
      "scriptId":"u29"},
    "09e06465370a4ecd8c1e85cf6a3922d5":{
      "scriptId":"u30"},
    "f849fe69cea1413b9e0950592c270aef":{
      "scriptId":"u31"},
    "2e75aea157984c84bb1cf71ff85db73d":{
      "scriptId":"u32"},
    "6ec513a71bd4472aaad98023e2e11504":{
      "scriptId":"u33"},
    "a9d40a9f79f64f9c9c5b60b1304939ae":{
      "scriptId":"u34"},
    "06f446e3eeae414db0939702e09bb4b8":{
      "scriptId":"u35"},
    "a8d754bd6d834a049f08ab9f63a625a0":{
      "scriptId":"u36"},
    "899bb1d655244be19e9dbf35d6ee638b":{
      "scriptId":"u37"},
    "e35866a0d870406897fb002d6636ebd1":{
      "scriptId":"u38"},
    "3358df30e20646f8aa315e4ef1ce4a50":{
      "scriptId":"u39"},
    "d73a051316ce45b3a1d7886e9e0ecce1":{
      "scriptId":"u40"},
    "c40e063003a44bb19acbfea241d12535":{
      "scriptId":"u41"}}});