$axure.loadCurrentPage({
  "url":"推进动画_1.html",
  "generationDate":new Date(1406724395298.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ca15e8b518814559936fb2e190f8f4db",
    "type":"Axure:Page",
    "name":"推进动画",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"115f907faf3a4212818328ef4fb9e44d",
          "label":"手机",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "size":{
              "width":754,
              "height":1478}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49442bda98ed4a828c6bd7f705c8addd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "size":{
                  "width":754,
                  "height":1478}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/手机_u0.png"}},
{
          "id":"71bf53d145ce4d258fc44f9e8af7f044",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":260},
            "size":{
              "width":640,
              "height":960}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"webUrl",
            "urlLiteral":{
              "exprType":"stringLiteral",
              "value":"",
              "stos":[]},
            "includeVariables":false}},
{
          "id":"efd8d4b919fe45a5b8d4b738a1f27f66",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":60,
              "y":260},
            "size":{
              "width":640,
              "height":960}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7c3c86a044b482ca77b5f4befa13bff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":60,
                  "y":260},
                "size":{
                  "width":640,
                  "height":960}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show monster 1,<br>mosnster2 ,<br>monster3,<br>(Image),<br>(Image),<br>(Image),<br> moster ~",
                      "objectsToFades":[{
                          "objectPath":["4ee9bfae3e974f9f9ebbdff3779e2983"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["232f6938ac234b6ab1a78665c96f3c9d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["a276d2a7aee64b9b9a5c34703d19b6e4"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["12fe21697303422dab15c719d875409d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f17135cd11404a4ba4556c5658d1c3e2"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["50cb972cb32847eea3829a0841ed9286"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["485354d899984f5cb8cb18324e2a482b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/推进动画/u3.png"}},
{
          "id":"ee48471cd5954c6ba650fa6d19c0c075",
          "label":"副本名",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":60,
              "y":370},
            "size":{
              "width":270,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd81efb45511435fa1561583c9edffff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":60,
                  "y":370},
                "size":{
                  "width":270,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/copy_of_feed_to_monster/friends_list_u29.png"}},
{
          "id":"4ee9bfae3e974f9f9ebbdff3779e2983",
          "label":"monster 1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":200,
              "y":1100},
            "size":{
              "width":110,
              "height":110},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3389613ee954ba4876870330be61316",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":200,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 人物转变成球动画 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"人物转变成球动画_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"232f6938ac234b6ab1a78665c96f3c9d",
          "label":"mosnster2 ",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":325,
              "y":1100},
            "size":{
              "width":110,
              "height":110},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3af82d79be77465ab186fec33a3026c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":325,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"a276d2a7aee64b9b9a5c34703d19b6e4",
          "label":"monster3",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":450,
              "y":1100},
            "size":{
              "width":110,
              "height":110},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7560c22823741c08112574c17ff3067",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":450,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"12fe21697303422dab15c719d875409d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":228,
              "y":1125},
            "size":{
              "width":60,
              "height":60},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07b3c45fd986456391a5e1910e776cf7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":228,
                  "y":1125},
                "size":{
                  "width":60,
                  "height":60},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/feed3_u120.png"}},
{
          "id":"f17135cd11404a4ba4556c5658d1c3e2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":351,
              "y":1124},
            "size":{
              "width":60,
              "height":60},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6c00adc98cc47329d14b837bb2836e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":351,
                  "y":1124},
                "size":{
                  "width":60,
                  "height":60},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/feed5_u124.png"}},
{
          "id":"50cb972cb32847eea3829a0841ed9286",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":475,
              "y":1125},
            "size":{
              "width":60,
              "height":60},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fda4874f2dd491ea4f77e94a5a74bb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":475,
                  "y":1125},
                "size":{
                  "width":60,
                  "height":60},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/feed5_u124.png"}},
{
          "id":"485354d899984f5cb8cb18324e2a482b",
          "label":" moster ~",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":255,
              "y":614},
            "size":{
              "width":250,
              "height":250},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc91c291dfc4401bbb0051feb4d6045e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":255,
                  "y":614},
                "size":{
                  "width":250,
                  "height":250},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/actor_u33.png"}},
{
          "id":"94b6b6683c12427b9c0d43848efee894",
          "label":"acquire coin",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":162.5,
              "y":320},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ab19c28e7a543528ff62b71df9ce97a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":162.5,
                  "y":320},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"611d735f7d2a47159385811ebf3ba40f",
          "label":"acquire pets",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":387.5,
              "y":320},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7cf06e6d16f4406ae6b0ed276fe5be9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":387.5,
                  "y":320},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"d1daf7169bbb4317b17f4f88cf61da54",
          "label":"battle 1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":280,
              "y":500},
            "size":{
              "width":200,
              "height":70},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3842cd93cb9f482fa843864b1ade382e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":280,
                  "y":500},
                "size":{
                  "width":200,
                  "height":70},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/推进动画/battle_1_u25.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "115f907faf3a4212818328ef4fb9e44d":{
      "scriptId":"u0"},
    "49442bda98ed4a828c6bd7f705c8addd":{
      "scriptId":"u1"},
    "71bf53d145ce4d258fc44f9e8af7f044":{
      "scriptId":"u2"},
    "efd8d4b919fe45a5b8d4b738a1f27f66":{
      "scriptId":"u3"},
    "b7c3c86a044b482ca77b5f4befa13bff":{
      "scriptId":"u4"},
    "ee48471cd5954c6ba650fa6d19c0c075":{
      "scriptId":"u5"},
    "fd81efb45511435fa1561583c9edffff":{
      "scriptId":"u6"},
    "4ee9bfae3e974f9f9ebbdff3779e2983":{
      "scriptId":"u7"},
    "c3389613ee954ba4876870330be61316":{
      "scriptId":"u8"},
    "232f6938ac234b6ab1a78665c96f3c9d":{
      "scriptId":"u9"},
    "3af82d79be77465ab186fec33a3026c5":{
      "scriptId":"u10"},
    "a276d2a7aee64b9b9a5c34703d19b6e4":{
      "scriptId":"u11"},
    "b7560c22823741c08112574c17ff3067":{
      "scriptId":"u12"},
    "12fe21697303422dab15c719d875409d":{
      "scriptId":"u13"},
    "07b3c45fd986456391a5e1910e776cf7":{
      "scriptId":"u14"},
    "f17135cd11404a4ba4556c5658d1c3e2":{
      "scriptId":"u15"},
    "f6c00adc98cc47329d14b837bb2836e7":{
      "scriptId":"u16"},
    "50cb972cb32847eea3829a0841ed9286":{
      "scriptId":"u17"},
    "7fda4874f2dd491ea4f77e94a5a74bb1":{
      "scriptId":"u18"},
    "485354d899984f5cb8cb18324e2a482b":{
      "scriptId":"u19"},
    "bc91c291dfc4401bbb0051feb4d6045e":{
      "scriptId":"u20"},
    "94b6b6683c12427b9c0d43848efee894":{
      "scriptId":"u21"},
    "4ab19c28e7a543528ff62b71df9ce97a":{
      "scriptId":"u22"},
    "611d735f7d2a47159385811ebf3ba40f":{
      "scriptId":"u23"},
    "f7cf06e6d16f4406ae6b0ed276fe5be9":{
      "scriptId":"u24"},
    "d1daf7169bbb4317b17f4f88cf61da54":{
      "scriptId":"u25"},
    "3842cd93cb9f482fa843864b1ade382e":{
      "scriptId":"u26"}}});