$axure.loadCurrentPage({
  "url":"fighting.html",
  "generationDate":new Date(1402535710234.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7db9ec3a0e89444ca8a835506eae6843",
    "type":"Axure:Page",
    "name":"fighting",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f9f915c2c15840b99a4134f236c1cec2",
          "label":"手机",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":754,
              "height":1478}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d47fa315fd5d428fbe9da555cdaf277e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":754,
                  "height":1478}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/手机_u0.png"}},
{
          "id":"2657d642f0e14b9a844dd6f9785e3f5e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":460},
            "size":{
              "width":250,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14a9b250b5bb4717a23752787dd686de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":460},
                "size":{
                  "width":250,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 congratulations,<br>(形状)",
                      "objectsToFades":[{
                          "objectPath":["9300c9cddcc941f1bd21880bcfd804f1"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["35c9a5bc41ad4bc9b28506b367bc5175"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/actor_u37.png"}},
{
          "id":"23eba6b0a8054e5db61c15f15071fad8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":830},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f16ab56d0f1e417a9f268a66aa3be0c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":830},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fighting/u4.png"}},
{
          "id":"fca7cda248a34e42927c591247313b8c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":850},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19de3d3dcf164654bf096b0730cb05b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":850},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fighting/u4.png"}},
{
          "id":"b380be3761554b36b8f6e0f1fa652eb3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":910},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a314ca4601a4e8f94bd42853e1591d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":910},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fighting/u4.png"}},
{
          "id":"895f0dd56c614024a7b06eb2420ae9c7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":940},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60057f30e0ec47659d59f9be4465706e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":940},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fighting/u4.png"}},
{
          "id":"00e3bcc3122b4d42bfaffcd9f098166f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":1020},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c221c30d64514227976c99615ed67c73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":1020},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fighting/u4.png"}},
{
          "id":"8f7b3b6db85046dc999fb52fa5fc4714",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":930},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0aa452ea6784dddad60434cf7b8144d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":930},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fighting/u4.png"}},
{
          "id":"9300c9cddcc941f1bd21880bcfd804f1",
          "label":"congratulations",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":630},
            "size":{
              "width":390,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60a3789e76a84b01afef0e91c0d5853e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":185,
                  "y":630},
                "size":{
                  "width":390,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If visibility of This = 真)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetVisibility",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":true}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 HOME",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/fighting/congratulations_u16.png"}},
{
          "id":"730cc744112445059414879c1fb3347f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":85,
              "y":283},
            "size":{
              "width":445,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6646a5b9ae5d4ae7b85fafa5d2dca0b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":85,
                  "y":283},
                "size":{
                  "width":445,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fighting/u18.png"}},
{
          "id":"25259e276b4549e0b85aef9f00025046",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":92,
              "y":293},
            "size":{
              "width":428,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a8b57fe116e4e10bd37dc921b16d5a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":92,
                  "y":293},
                "size":{
                  "width":428,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fighting/u20.png"}},
{
          "id":"e63f5ad486d44cc79584457c016f9214",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":273},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"768d5dbe9885478fb4f9bf3b753a8583",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":85,
                  "y":273},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fighting/u22.png"}},
{
          "id":"ae7385a976904992ae4db5cf1a5cd2ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":283},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4fbe2d74b9d4021840a7246104980c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":283},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fighting/u24.png"}},
{
          "id":"35c9a5bc41ad4bc9b28506b367bc5175",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":355,
              "y":670},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"542378c9fd5c490d8ba228ebd50cbcf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":355,
                  "y":670},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/buff1_u45.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f9f915c2c15840b99a4134f236c1cec2":{
      "scriptId":"u0"},
    "d47fa315fd5d428fbe9da555cdaf277e":{
      "scriptId":"u1"},
    "2657d642f0e14b9a844dd6f9785e3f5e":{
      "scriptId":"u2"},
    "14a9b250b5bb4717a23752787dd686de":{
      "scriptId":"u3"},
    "23eba6b0a8054e5db61c15f15071fad8":{
      "scriptId":"u4"},
    "f16ab56d0f1e417a9f268a66aa3be0c6":{
      "scriptId":"u5"},
    "fca7cda248a34e42927c591247313b8c":{
      "scriptId":"u6"},
    "19de3d3dcf164654bf096b0730cb05b4":{
      "scriptId":"u7"},
    "b380be3761554b36b8f6e0f1fa652eb3":{
      "scriptId":"u8"},
    "3a314ca4601a4e8f94bd42853e1591d9":{
      "scriptId":"u9"},
    "895f0dd56c614024a7b06eb2420ae9c7":{
      "scriptId":"u10"},
    "60057f30e0ec47659d59f9be4465706e":{
      "scriptId":"u11"},
    "00e3bcc3122b4d42bfaffcd9f098166f":{
      "scriptId":"u12"},
    "c221c30d64514227976c99615ed67c73":{
      "scriptId":"u13"},
    "8f7b3b6db85046dc999fb52fa5fc4714":{
      "scriptId":"u14"},
    "a0aa452ea6784dddad60434cf7b8144d":{
      "scriptId":"u15"},
    "9300c9cddcc941f1bd21880bcfd804f1":{
      "scriptId":"u16"},
    "60a3789e76a84b01afef0e91c0d5853e":{
      "scriptId":"u17"},
    "730cc744112445059414879c1fb3347f":{
      "scriptId":"u18"},
    "6646a5b9ae5d4ae7b85fafa5d2dca0b4":{
      "scriptId":"u19"},
    "25259e276b4549e0b85aef9f00025046":{
      "scriptId":"u20"},
    "1a8b57fe116e4e10bd37dc921b16d5a7":{
      "scriptId":"u21"},
    "e63f5ad486d44cc79584457c016f9214":{
      "scriptId":"u22"},
    "768d5dbe9885478fb4f9bf3b753a8583":{
      "scriptId":"u23"},
    "ae7385a976904992ae4db5cf1a5cd2ea":{
      "scriptId":"u24"},
    "a4fbe2d74b9d4021840a7246104980c6":{
      "scriptId":"u25"},
    "35c9a5bc41ad4bc9b28506b367bc5175":{
      "scriptId":"u26"},
    "542378c9fd5c490d8ba228ebd50cbcf9":{
      "scriptId":"u27"}}});