$axure.loadCurrentPage({
  "url":"宠物可以释放技能状态2.html",
  "generationDate":new Date(1417511336892.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"589b0577c86a469da9aed777552335f4",
    "type":"Axure:Page",
    "name":"宠物可以释放技能状态2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"18d72e9db63a479fba8982e945501ab7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":324},
            "size":{
              "width":640,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"398f20cd0da949b4a15510fae5a27016",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":324},
                "size":{
                  "width":640,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u0.jpg"}},
{
          "id":"50fbc54262ad49d5b22e7b40835973e4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":4},
            "size":{
              "width":640,
              "height":320}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6570925bf2aa4d109b69d0ff596b99cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":4},
                "size":{
                  "width":640,
                  "height":320}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u2.jpg"}},
{
          "id":"7d38e799a3524c8f9981cada7529f3c8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":385,
              "y":84},
            "size":{
              "width":150,
              "height":140},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61556aa3abcd46189a306935d96790f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":385,
                  "y":84},
                "size":{
                  "width":150,
                  "height":140},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u4.png"}},
{
          "id":"cf8fc8e3af5c4cf4a28756f01fe1526d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":385,
              "y":224},
            "size":{
              "width":150,
              "height":10},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8fc69ba7a3d402287cee499cd290f20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":385,
                  "y":224},
                "size":{
                  "width":150,
                  "height":10},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u6.png"}},
{
          "id":"0ffc0512d95a4d22a3f3c45401586d0e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":73},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dd5b172a6324c38b6f28a3e320bfabd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":73},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u8.png"}},
{
          "id":"9171c0a110d6493fa3b5c041ca8e7902",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":415,
              "y":234},
            "size":{
              "width":80,
              "height":10},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59637fddc74a4d26ae4b40a55e27d726",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":415,
                  "y":234},
                "size":{
                  "width":80,
                  "height":10},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u10.png"}},
{
          "id":"0f9d9d4bbae34b38943c227206af5572",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":124,
              "y":224},
            "size":{
              "width":80,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e5c75de721b4fdd971de06a21561fb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":124,
                  "y":224},
                "size":{
                  "width":80,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u12.png"}},
{
          "id":"255e182c23b34d8f8a1eb2fa22e2547e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":614},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd6613ee107e41c5be27d7e3837572a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":614},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u14.png"}},
{
          "id":"9680e02cdbcc49d782e4dd657e3ee13c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":375,
              "y":629},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2627f6abd69b45c48fffb2d430e57760",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":375,
                  "y":629},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u16.png"}},
{
          "id":"fd459f8bfff6495ca4abe5611984b4f3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":554},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89ae5556a0354af3852d9e50923e54f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":554},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u14.png"}},
{
          "id":"ed25a3f7fafd491aa40e51b264bf9b67",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":569},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79f2180bdd1d4cbdadcf622bdcfb5a88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":569},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u16.png"}},
{
          "id":"4c1012b1907d4c3d8a244ca9651cf30b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":459},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb97c436df724afd8790e64ad12fe438",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":459},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u14.png"}},
{
          "id":"f56d51c7406544518899aa9cb8dfd571",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":14.5,
              "y":694},
            "size":{
              "width":180,
              "height":210}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8b82f91894145b5a2b0a8a5b84d86b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14.5,
                  "y":694},
                "size":{
                  "width":180,
                  "height":210}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/宠物可以释放技能状态1/u38.png"}},
{
          "id":"9e3e0c4450d84336b7dd6659e75a16ba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":474},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52502783be8d48398129503c20c938e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":425,
                  "y":474},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u16.png"}},
{
          "id":"d81ade25efab43ac977b10ef16ea9fc1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":694},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0804225901984aa1a67f4ed0959f9946",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":694},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u14.png"}},
{
          "id":"7d2ac03f8d3d4858b26c02991811be7e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":275,
              "y":709},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4777be4a7d014a819b12a9abc3af27f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":275,
                  "y":709},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u16.png"}},
{
          "id":"6cf21286f44348c6972be3e8d94d06a8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":444},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a1fafb19ad9450e9171f29b7997b6ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":444},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u14.png"}},
{
          "id":"452b74e0416d45b193dc0f5160991481",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":225,
              "y":459},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9603347b7e6348c7ae3ab946e65b9c23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":225,
                  "y":459},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u16.png"}},
{
          "id":"5c6568493c2549218927fa832d63678e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":780},
            "size":{
              "width":89,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dffbf72a2f14209b6db9322984397d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":780},
                "size":{
                  "width":89,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u8.png"}},
{
          "id":"8374ab5d7ed34e51a7bddcd02641cfb6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":790},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3f56a9461354f88a9354152ef40ade6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":790},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1<br> (If visibility of skill equals false)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetVisibility",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["95c5cd56bfb14eec824befeeb1b315c3"]}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":false}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show skill,<br>(Image),<br>(Image),<br>(Image),<br>(Image)",
                      "objectsToFades":[{
                          "objectPath":["95c5cd56bfb14eec824befeeb1b315c3"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["15d04a9133654736a5cc0a57979a2426"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["a0f11de4df684164b197e230d53e93c3"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0673d199a8054b058d4f2aa74e6942bb"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["66a0cf88e27d4cfdb56eddb64aa30adb"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/战斗开始/u14.png"}},
{
          "id":"298d0966f24a43d59999b7376d734fd9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":604},
            "size":{
              "width":90,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81ca85bdd2d346699b73e86327362207",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":604},
                "size":{
                  "width":90,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u38.png"}},
{
          "id":"54cc457a3ba94c06b413932da01e2c0f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":599},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6648a99dc2dd46be8e4cc2e9fbd609c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":599},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u14.png"}},
{
          "id":"66a0cf88e27d4cfdb56eddb64aa30adb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":554},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cd09d68e8784c428507471e5d93e675",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":554},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u42.png"}},
{
          "id":"0673d199a8054b058d4f2aa74e6942bb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":554},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd9d746ee51742b88172e926aa29bf19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":554},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u44.png"}},
{
          "id":"a0f11de4df684164b197e230d53e93c3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":554},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a4e8275e8f44c0c921098bfb2d5f016",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":554},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u46.png"}},
{
          "id":"15d04a9133654736a5cc0a57979a2426",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":554},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f1b7c0fad734130a5edeb83ca47f332",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":554},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u48.png"}},
{
          "id":"e010725bb5284f70bd9a3d8b2536428e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":736},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44dfeb96b34e499d8cd4d2af45e7fb62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":736},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u14.png"}},
{
          "id":"0cd5ed718a3e4d03aee52b1867a48db5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":761},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7569fb0fc98d4407be64a8b0746d049b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":465,
                  "y":761},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u52.png"}},
{
          "id":"95c5cd56bfb14eec824befeeb1b315c3",
          "label":"skill",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":790},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cae2b8deefbb4c459e28c94136774ba9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":790},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1<br> (If visibility of This equals true)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetVisibility",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":true}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Hide (Image),<br>(Image),<br>(Image),<br>(Image),<br>skill",
                      "objectsToFades":[{
                          "objectPath":["66a0cf88e27d4cfdb56eddb64aa30adb"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["15d04a9133654736a5cc0a57979a2426"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["a0f11de4df684164b197e230d53e93c3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0673d199a8054b058d4f2aa74e6942bb"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["95c5cd56bfb14eec824befeeb1b315c3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/战斗开始/skill_u54.png"}},
{
          "id":"57ba84d546cf40dd90bc4586edffdaa2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":437,
              "y":732},
            "size":{
              "width":107,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"644bd64f8172418083ac8107d3a8f514",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":437,
                  "y":732},
                "size":{
                  "width":107,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u56.png"}},
{
          "id":"2ef26a2a55f54d1892a8a6192b7029fa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":375,
              "y":20},
            "size":{
              "width":100,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0063c2a82154afd973f18a538aba162",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":375,
                  "y":20},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我方回合/u58.png"}},
{
          "id":"276c29ade8794c2885a973512a5df81b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":20},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d798300b1b44270ad0bf7c3607290ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":425,
                  "y":20},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我方回合/u60.png"}},
{
          "id":"9b80c5d19d8847c69955b1c73762373c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":20},
            "size":{
              "width":100,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e3f8667a5cd4c238f50a889e95106d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":20},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我方回合/u58.png"}},
{
          "id":"0262aab27eae45b1bf7188a065d49161",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":545,
              "y":25},
            "size":{
              "width":45,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f14d8e06f054db6b16552fc6b055755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":545,
                  "y":25},
                "size":{
                  "width":45,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我方回合/u64.png"}},
{
          "id":"e1ae85f68c9f40f7bd1a297cf11e71d5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-18,
              "y":306},
            "size":{
              "width":676,
              "height":676}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9b997b422434f719371d24a1a8dc31b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-18,
                  "y":306},
                "size":{
                  "width":676,
                  "height":676}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u58.png"}},
{
          "id":"df0d5fd39f1e4ce582aae110f7da8e03",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed5d47817d34459f8500018d26176801",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗开始/u60.png"}},
{
          "id":"229818254e0847ee90090aa62a3b4e20",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":115,
              "y":20},
            "size":{
              "width":100,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c6134e0c2234c4e864a1e41ff0bea65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":115,
                  "y":20},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我方回合/u58.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "18d72e9db63a479fba8982e945501ab7":{
      "scriptId":"u0"},
    "398f20cd0da949b4a15510fae5a27016":{
      "scriptId":"u1"},
    "50fbc54262ad49d5b22e7b40835973e4":{
      "scriptId":"u2"},
    "6570925bf2aa4d109b69d0ff596b99cf":{
      "scriptId":"u3"},
    "7d38e799a3524c8f9981cada7529f3c8":{
      "scriptId":"u4"},
    "61556aa3abcd46189a306935d96790f3":{
      "scriptId":"u5"},
    "cf8fc8e3af5c4cf4a28756f01fe1526d":{
      "scriptId":"u6"},
    "b8fc69ba7a3d402287cee499cd290f20":{
      "scriptId":"u7"},
    "0ffc0512d95a4d22a3f3c45401586d0e":{
      "scriptId":"u8"},
    "5dd5b172a6324c38b6f28a3e320bfabd":{
      "scriptId":"u9"},
    "9171c0a110d6493fa3b5c041ca8e7902":{
      "scriptId":"u10"},
    "59637fddc74a4d26ae4b40a55e27d726":{
      "scriptId":"u11"},
    "0f9d9d4bbae34b38943c227206af5572":{
      "scriptId":"u12"},
    "4e5c75de721b4fdd971de06a21561fb8":{
      "scriptId":"u13"},
    "255e182c23b34d8f8a1eb2fa22e2547e":{
      "scriptId":"u14"},
    "dd6613ee107e41c5be27d7e3837572a0":{
      "scriptId":"u15"},
    "9680e02cdbcc49d782e4dd657e3ee13c":{
      "scriptId":"u16"},
    "2627f6abd69b45c48fffb2d430e57760":{
      "scriptId":"u17"},
    "fd459f8bfff6495ca4abe5611984b4f3":{
      "scriptId":"u18"},
    "89ae5556a0354af3852d9e50923e54f7":{
      "scriptId":"u19"},
    "ed25a3f7fafd491aa40e51b264bf9b67":{
      "scriptId":"u20"},
    "79f2180bdd1d4cbdadcf622bdcfb5a88":{
      "scriptId":"u21"},
    "4c1012b1907d4c3d8a244ca9651cf30b":{
      "scriptId":"u22"},
    "eb97c436df724afd8790e64ad12fe438":{
      "scriptId":"u23"},
    "f56d51c7406544518899aa9cb8dfd571":{
      "scriptId":"u24"},
    "a8b82f91894145b5a2b0a8a5b84d86b8":{
      "scriptId":"u25"},
    "9e3e0c4450d84336b7dd6659e75a16ba":{
      "scriptId":"u26"},
    "52502783be8d48398129503c20c938e8":{
      "scriptId":"u27"},
    "d81ade25efab43ac977b10ef16ea9fc1":{
      "scriptId":"u28"},
    "0804225901984aa1a67f4ed0959f9946":{
      "scriptId":"u29"},
    "7d2ac03f8d3d4858b26c02991811be7e":{
      "scriptId":"u30"},
    "4777be4a7d014a819b12a9abc3af27f2":{
      "scriptId":"u31"},
    "6cf21286f44348c6972be3e8d94d06a8":{
      "scriptId":"u32"},
    "7a1fafb19ad9450e9171f29b7997b6ac":{
      "scriptId":"u33"},
    "452b74e0416d45b193dc0f5160991481":{
      "scriptId":"u34"},
    "9603347b7e6348c7ae3ab946e65b9c23":{
      "scriptId":"u35"},
    "5c6568493c2549218927fa832d63678e":{
      "scriptId":"u36"},
    "8dffbf72a2f14209b6db9322984397d7":{
      "scriptId":"u37"},
    "8374ab5d7ed34e51a7bddcd02641cfb6":{
      "scriptId":"u38"},
    "a3f56a9461354f88a9354152ef40ade6":{
      "scriptId":"u39"},
    "298d0966f24a43d59999b7376d734fd9":{
      "scriptId":"u40"},
    "81ca85bdd2d346699b73e86327362207":{
      "scriptId":"u41"},
    "54cc457a3ba94c06b413932da01e2c0f":{
      "scriptId":"u42"},
    "6648a99dc2dd46be8e4cc2e9fbd609c7":{
      "scriptId":"u43"},
    "66a0cf88e27d4cfdb56eddb64aa30adb":{
      "scriptId":"u44"},
    "4cd09d68e8784c428507471e5d93e675":{
      "scriptId":"u45"},
    "0673d199a8054b058d4f2aa74e6942bb":{
      "scriptId":"u46"},
    "dd9d746ee51742b88172e926aa29bf19":{
      "scriptId":"u47"},
    "a0f11de4df684164b197e230d53e93c3":{
      "scriptId":"u48"},
    "0a4e8275e8f44c0c921098bfb2d5f016":{
      "scriptId":"u49"},
    "15d04a9133654736a5cc0a57979a2426":{
      "scriptId":"u50"},
    "9f1b7c0fad734130a5edeb83ca47f332":{
      "scriptId":"u51"},
    "e010725bb5284f70bd9a3d8b2536428e":{
      "scriptId":"u52"},
    "44dfeb96b34e499d8cd4d2af45e7fb62":{
      "scriptId":"u53"},
    "0cd5ed718a3e4d03aee52b1867a48db5":{
      "scriptId":"u54"},
    "7569fb0fc98d4407be64a8b0746d049b":{
      "scriptId":"u55"},
    "95c5cd56bfb14eec824befeeb1b315c3":{
      "scriptId":"u56"},
    "cae2b8deefbb4c459e28c94136774ba9":{
      "scriptId":"u57"},
    "57ba84d546cf40dd90bc4586edffdaa2":{
      "scriptId":"u58"},
    "644bd64f8172418083ac8107d3a8f514":{
      "scriptId":"u59"},
    "2ef26a2a55f54d1892a8a6192b7029fa":{
      "scriptId":"u60"},
    "a0063c2a82154afd973f18a538aba162":{
      "scriptId":"u61"},
    "276c29ade8794c2885a973512a5df81b":{
      "scriptId":"u62"},
    "6d798300b1b44270ad0bf7c3607290ed":{
      "scriptId":"u63"},
    "9b80c5d19d8847c69955b1c73762373c":{
      "scriptId":"u64"},
    "3e3f8667a5cd4c238f50a889e95106d9":{
      "scriptId":"u65"},
    "0262aab27eae45b1bf7188a065d49161":{
      "scriptId":"u66"},
    "9f14d8e06f054db6b16552fc6b055755":{
      "scriptId":"u67"},
    "e1ae85f68c9f40f7bd1a297cf11e71d5":{
      "scriptId":"u68"},
    "d9b997b422434f719371d24a1a8dc31b":{
      "scriptId":"u69"},
    "df0d5fd39f1e4ce582aae110f7da8e03":{
      "scriptId":"u70"},
    "ed5d47817d34459f8500018d26176801":{
      "scriptId":"u71"},
    "229818254e0847ee90090aa62a3b4e20":{
      "scriptId":"u72"},
    "1c6134e0c2234c4e864a1e41ff0bea65":{
      "scriptId":"u73"}}});