$axure.loadCurrentPage({
  "url":"道具融合确定.html",
  "generationDate":new Date(1393973828590.26),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a5fa412b2d0d415793c39d7a77f010b3",
    "type":"Axure:Page",
    "name":"道具融合确定",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4d1791fff6314fc7a1915bae2961d9dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF996633},
            "size":{
              "width":640,
              "height":1136},
            "cornerRadiusTopLeft":"15"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9d119321f86417c9c89f418782b1b01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF996633},
                "size":{
                  "width":640,
                  "height":1136},
                "cornerRadiusTopLeft":"15"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u0.png"}},
{
          "id":"a967c149001548c2ae60f651e32c3fad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF990099},
            "location":{
              "x":1,
              "y":0},
            "size":{
              "width":640,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b4b9b0100f247d88f9097d4bc1fdac3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF990099},
                "location":{
                  "x":1,
                  "y":0},
                "size":{
                  "width":640,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一次登陆/u4.png"}},
{
          "id":"d3df5a84e3164c6ba3a34c919b24c6ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":1,
              "y":40},
            "size":{
              "width":640,
              "height":100},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c52eea33a3db47f1ba3ba307a248b4c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":1,
                  "y":40},
                "size":{
                  "width":640,
                  "height":100},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u4.png"}},
{
          "id":"eab38bfd43f046b5999083013fe2d36d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCC33},
{
                  "color":0xFFCCCC33},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":106,
              "y":75},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2da0be48de5c498d9842a3ade6821900",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCC33},
{
                      "color":0xFFCCCC33},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":106,
                  "y":75},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u6.png"}},
{
          "id":"c60846f77ea6450ead89a6da59e7d835",
          "label":"水",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":68},
            "size":{
              "width":45,
              "height":45},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a91575d3536f4c1ba64407e25ddb5eb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":68},
                "size":{
                  "width":45,
                  "height":45},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一次选择宠物/水_u22.png"}},
{
          "id":"f4af792ba6ec40819145eef3e1f20ab3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1,
              "y":990},
            "size":{
              "width":640,
              "height":160},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61445e47845c4899a948c117f4be0878",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1,
                  "y":990},
                "size":{
                  "width":640,
                  "height":160},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u10.png"}},
{
          "id":"38465080d4644a6f81c2928868b1e187",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "opacity":"1",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "mouseDown":{
                "opacity":"1"}},
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF993300},
            "location":{
              "x":10,
              "y":1010},
            "size":{
              "width":120,
              "height":120},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2816065c311943ec9d2b82d94b662959",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"1",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "mouseDown":{
                    "opacity":"1"}},
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF993300},
                "location":{
                  "x":10,
                  "y":1010},
                "size":{
                  "width":120,
                  "height":120},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 怪物",
                      "target":{
                        "targetType":"page",
                        "url":"怪物.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主菜单/u12.png",
            "mouseOver~":"images/主菜单/u12_mouseOver.png",
            "mouseDown~":"images/主菜单/u12_mouseOver.png"}},
{
          "id":"9c92d2ac00c34f18b00fe2a71d7b51fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "opacity":"1",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "mouseDown":{
                "opacity":"1"}},
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF993300},
            "location":{
              "x":135,
              "y":1010},
            "size":{
              "width":120,
              "height":120},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5472cd4b951a429aae62619ac46f5eda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"1",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "mouseDown":{
                    "opacity":"1"}},
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF993300},
                "location":{
                  "x":135,
                  "y":1010},
                "size":{
                  "width":120,
                  "height":120},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u12.png",
            "mouseOver~":"images/主菜单/u12_mouseOver.png",
            "mouseDown~":"images/主菜单/u12_mouseOver.png"}},
{
          "id":"7eb5b3b6d6cf47638ca3ee9513980783",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "mouseDown":{
                "opacity":"1"}},
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF993300},
            "location":{
              "x":260,
              "y":1010},
            "size":{
              "width":120,
              "height":120},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b961b78ca934a55b07caab227c2cda3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "mouseDown":{
                    "opacity":"1"}},
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF993300},
                "location":{
                  "x":260,
                  "y":1010},
                "size":{
                  "width":120,
                  "height":120},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 战斗",
                      "target":{
                        "targetType":"page",
                        "url":"战斗.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主菜单/u12.png",
            "mouseOver~":"images/主菜单/u12_mouseOver.png",
            "mouseDown~":"images/主菜单/u12_mouseOver.png"}},
{
          "id":"2da8c064e45e48b1a99a56996fb92cc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "opacity":"1",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "mouseDown":{
                "opacity":"1"}},
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF993300},
            "location":{
              "x":385,
              "y":1010},
            "size":{
              "width":120,
              "height":120},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4870a67408a1495d88940fd8463c31fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"1",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "mouseDown":{
                    "opacity":"1"}},
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF993300},
                "location":{
                  "x":385,
                  "y":1010},
                "size":{
                  "width":120,
                  "height":120},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商城",
                      "target":{
                        "targetType":"page",
                        "url":"商城.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主菜单/u12.png",
            "mouseOver~":"images/主菜单/u12_mouseOver.png",
            "mouseDown~":"images/主菜单/u12_mouseOver.png"}},
{
          "id":"990ff90dbd8b4eaeb1a250f636786d64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "opacity":"1",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "mouseDown":{
                "opacity":"1"}},
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF993300},
            "location":{
              "x":510,
              "y":1010},
            "size":{
              "width":120,
              "height":120},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f28b2a0f0494b47b4b3288450452f38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"1",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "mouseDown":{
                    "opacity":"1"}},
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF993300},
                "location":{
                  "x":510,
                  "y":1010},
                "size":{
                  "width":120,
                  "height":120},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设置",
                      "target":{
                        "targetType":"page",
                        "url":"设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主菜单/u12.png",
            "mouseOver~":"images/主菜单/u12_mouseOver.png",
            "mouseDown~":"images/主菜单/u12_mouseOver.png"}},
{
          "id":"a20ff0c79beb4d36afc66f531bc51a38",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":850,
              "y":1036},
            "size":{
              "width":2,
              "height":3},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97cb91ee461047d29a0cbc30c29b3d66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":850,
                  "y":1036},
                "size":{
                  "width":2,
                  "height":3},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u22.png"}},
{
          "id":"6d05e91faba24f7d99ed7e33f772fa85",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":852,
              "y":1036},
            "size":{
              "width":57,
              "height":3},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f11f7841eda4985b29b040c64b0eadf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":852,
                  "y":1036},
                "size":{
                  "width":57,
                  "height":3},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u24.png"}},
{
          "id":"27b6b89dce03497ab1410f4ae9d7bb45",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":37,
              "y":1037},
            "size":{
              "width":70,
              "height":70},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf4d13f7c0054592892b61c5b0054743",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":37,
                  "y":1037},
                "size":{
                  "width":70,
                  "height":70},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u26.png",
            "mouseOver~":"images/主菜单/u26_mouseOver.png"}},
{
          "id":"248f12466e9240d4b7e4f94a539a2cf5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":160,
              "y":1035},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6f2c65df2964399bf2c26384f475962",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":160,
                  "y":1035},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u28.png",
            "mouseOver~":"images/主菜单/u28_mouseOver.png"}},
{
          "id":"9d54de637a1046dba413af97d1b147d2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":288,
              "y":1032},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d42788179f94464c9c008392441d569d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":288,
                  "y":1032},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u30.jpg",
            "mouseOver~":"images/主菜单/u30_mouseOver.png"}},
{
          "id":"a15888cb8d06494b8fd74d06cc9f985d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":411,
              "y":1033},
            "size":{
              "width":70,
              "height":70},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7a2726db5434470bb28456b271a687c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":411,
                  "y":1033},
                "size":{
                  "width":70,
                  "height":70},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u32.png",
            "mouseOver~":"images/主菜单/u32_mouseOver.png"}},
{
          "id":"0f5f6b07327b48c4abc3299b4b0df90b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":542,
              "y":1037},
            "size":{
              "width":55,
              "height":56},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d8f8907ad3642cfb375e82ecc703429",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":542,
                  "y":1037},
                "size":{
                  "width":55,
                  "height":56},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u34.png",
            "mouseOver~":"images/主菜单/u34_mouseOver.png"}},
{
          "id":"404e1acebece4d89a012b116e1daadbb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":336,
              "y":68},
            "size":{
              "width":45,
              "height":45},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab4277ee7ef544458d9176536d929a66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":336,
                  "y":68},
                "size":{
                  "width":45,
                  "height":45},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u36.png"}},
{
          "id":"e1ea6eadcf62465ca68a23e9ceef9463",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCC33},
{
                  "color":0xFFCCCC33},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":401,
              "y":75},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8e8f8d8681349769a0b3d635159e63c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCC33},
{
                      "color":0xFFCCCC33},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":401,
                  "y":75},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u6.png"}},
{
          "id":"ab8ff6e900be46ac9b28c33c70086687",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF990000},
            "location":{
              "x":40,
              "y":187},
            "size":{
              "width":380,
              "height":80},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD91504},
            "cornerRadiusTopLeft":"15"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fb43d1ad43840d9ab93f0f2c7ebb3d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF990000},
                "location":{
                  "x":40,
                  "y":187},
                "size":{
                  "width":380,
                  "height":80},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD91504},
                "cornerRadiusTopLeft":"15"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u40.png"}},
{
          "id":"15ad58a4988149dc99c3a93706ce34b9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":150},
            "size":{
              "width":104,
              "height":37},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7808206e94394820bbd9a7cb28ce10f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":150},
                "size":{
                  "width":104,
                  "height":37},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u42.png"}},
{
          "id":"7e589a0910e44c9cb7079acb13c3e0c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":30,
              "y":290},
            "size":{
              "width":580,
              "height":419},
            "borderWidth":"5",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1ebafb29b34444785b800e7dd8f3ac5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":30,
                  "y":290},
                "size":{
                  "width":580,
                  "height":419},
                "borderWidth":"5",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/融合/u44.png"}},
{
          "id":"eb6f5bed5c5e4bdc84a3a0858ef1294b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":54,
              "y":202},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD91504},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"122cb632e90b43b98a6f21bde5c7a3cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":54,
                  "y":202},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD91504},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 融合",
                      "target":{
                        "targetType":"page",
                        "url":"融合.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/怪物编队/u46.png"}},
{
          "id":"988471009dbc4cde81d26eb02d61c750",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":130,
              "y":350},
            "size":{
              "width":100,
              "height":100},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2ad3c736d68474288c4b62ed9c6ae00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":130,
                  "y":350},
                "size":{
                  "width":100,
                  "height":100},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物编队/u90.png"}},
{
          "id":"878acae5cfab4014bfd5ea6490cbbc9a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":395},
            "size":{
              "width":165,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/已选择一只怪物/u52_line.png"}},
{
          "id":"b7b77e831e4c4e4388b774069f565e9c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":400},
            "size":{
              "width":10,
              "height":110}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/已选择一只怪物/u53_line.png"}},
{
          "id":"989cdde2a8e14085ac0bc2fa18476cf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":263,
              "y":510},
            "size":{
              "width":100,
              "height":100},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7bd7aee71884ca4b34db9b59878e615",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":263,
                  "y":510},
                "size":{
                  "width":100,
                  "height":100},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物编队/u90.png"}},
{
          "id":"5838153b95404ebbb44b1e8142a1b866",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "location":{
              "x":130,
              "y":450},
            "size":{
              "width":150,
              "height":50},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95f5126d44c648289683f6ed4a779de1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "location":{
                  "x":130,
                  "y":450},
                "size":{
                  "width":150,
                  "height":50},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物编队/u84.png"}},
{
          "id":"9da02d2197d144818ad847d55b1f6cc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009900},
            "location":{
              "x":395,
              "y":350},
            "size":{
              "width":100,
              "height":100},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009999},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d81feceba99408a918a00e223e9f9d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009900},
                "location":{
                  "x":395,
                  "y":350},
                "size":{
                  "width":100,
                  "height":100},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择道具/u46.png"}},
{
          "id":"157819b7b51f4da0b0c4adeb765020ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "location":{
              "x":363,
              "y":559},
            "size":{
              "width":150,
              "height":50},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d29ae8346144b8e9334e7b0dfd952a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "location":{
                  "x":363,
                  "y":559},
                "size":{
                  "width":150,
                  "height":50},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物编队/u84.png"}},
{
          "id":"796bc6b8fadc465a9f6788f68e757701",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0.6",
            "fill":{
              "fillType":"solid",
              "color":0xFF996666},
            "location":{
              "x":268,
              "y":630},
            "size":{
              "width":90,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"226ad08c68ae49b5bf5b6dc7f7870511",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0.6",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF996666},
                "location":{
                  "x":268,
                  "y":630},
                "size":{
                  "width":90,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 生成新怪物",
                      "target":{
                        "targetType":"page",
                        "url":"生成新怪物.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/第一次登陆/u13.png"}},
{
          "id":"4e0ee763875c4b9a968634b42d1f4cd7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.4",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"161828cf826646cba241a9a90c30d709",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.4",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/与被封印宠物更换出场顺序/u104.png"}},
{
          "id":"34b600002ff34b6b8df276e6dac406fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":480},
            "size":{
              "width":270,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98b25e05013642b9bd7af170105bc7a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":480},
                "size":{
                  "width":270,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/融合确定/u66.png"}},
{
          "id":"96397471d57c4fb3829faabee8716f5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0.6",
            "fill":{
              "fillType":"solid",
              "color":0xFF996666},
            "location":{
              "x":200,
              "y":580},
            "size":{
              "width":90,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b306a89708614aa984580afc5f58801c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0.6",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF996666},
                "location":{
                  "x":200,
                  "y":580},
                "size":{
                  "width":90,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 生成新怪物",
                      "target":{
                        "targetType":"page",
                        "url":"生成新怪物.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/第一次登陆/u13.png"}},
{
          "id":"eecefef54ef644e18bf6d52bb94ae009",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0.6",
            "fill":{
              "fillType":"solid",
              "color":0xFF996666},
            "location":{
              "x":330,
              "y":580},
            "size":{
              "width":90,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"801487ac3d6b47738602e39152d3eb66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0.6",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF996666},
                "location":{
                  "x":330,
                  "y":580},
                "size":{
                  "width":90,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 道具融合",
                      "target":{
                        "targetType":"page",
                        "url":"道具融合.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/第一次登陆/u13.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4d1791fff6314fc7a1915bae2961d9dc":{
      "scriptId":"u0"},
    "b9d119321f86417c9c89f418782b1b01":{
      "scriptId":"u1"},
    "a967c149001548c2ae60f651e32c3fad":{
      "scriptId":"u2"},
    "4b4b9b0100f247d88f9097d4bc1fdac3":{
      "scriptId":"u3"},
    "d3df5a84e3164c6ba3a34c919b24c6ba":{
      "scriptId":"u4"},
    "c52eea33a3db47f1ba3ba307a248b4c3":{
      "scriptId":"u5"},
    "eab38bfd43f046b5999083013fe2d36d":{
      "scriptId":"u6"},
    "2da0be48de5c498d9842a3ade6821900":{
      "scriptId":"u7"},
    "c60846f77ea6450ead89a6da59e7d835":{
      "scriptId":"u8"},
    "a91575d3536f4c1ba64407e25ddb5eb4":{
      "scriptId":"u9"},
    "f4af792ba6ec40819145eef3e1f20ab3":{
      "scriptId":"u10"},
    "61445e47845c4899a948c117f4be0878":{
      "scriptId":"u11"},
    "38465080d4644a6f81c2928868b1e187":{
      "scriptId":"u12"},
    "2816065c311943ec9d2b82d94b662959":{
      "scriptId":"u13"},
    "9c92d2ac00c34f18b00fe2a71d7b51fb":{
      "scriptId":"u14"},
    "5472cd4b951a429aae62619ac46f5eda":{
      "scriptId":"u15"},
    "7eb5b3b6d6cf47638ca3ee9513980783":{
      "scriptId":"u16"},
    "6b961b78ca934a55b07caab227c2cda3":{
      "scriptId":"u17"},
    "2da8c064e45e48b1a99a56996fb92cc5":{
      "scriptId":"u18"},
    "4870a67408a1495d88940fd8463c31fd":{
      "scriptId":"u19"},
    "990ff90dbd8b4eaeb1a250f636786d64":{
      "scriptId":"u20"},
    "1f28b2a0f0494b47b4b3288450452f38":{
      "scriptId":"u21"},
    "a20ff0c79beb4d36afc66f531bc51a38":{
      "scriptId":"u22"},
    "97cb91ee461047d29a0cbc30c29b3d66":{
      "scriptId":"u23"},
    "6d05e91faba24f7d99ed7e33f772fa85":{
      "scriptId":"u24"},
    "8f11f7841eda4985b29b040c64b0eadf":{
      "scriptId":"u25"},
    "27b6b89dce03497ab1410f4ae9d7bb45":{
      "scriptId":"u26"},
    "cf4d13f7c0054592892b61c5b0054743":{
      "scriptId":"u27"},
    "248f12466e9240d4b7e4f94a539a2cf5":{
      "scriptId":"u28"},
    "f6f2c65df2964399bf2c26384f475962":{
      "scriptId":"u29"},
    "9d54de637a1046dba413af97d1b147d2":{
      "scriptId":"u30"},
    "d42788179f94464c9c008392441d569d":{
      "scriptId":"u31"},
    "a15888cb8d06494b8fd74d06cc9f985d":{
      "scriptId":"u32"},
    "a7a2726db5434470bb28456b271a687c":{
      "scriptId":"u33"},
    "0f5f6b07327b48c4abc3299b4b0df90b":{
      "scriptId":"u34"},
    "0d8f8907ad3642cfb375e82ecc703429":{
      "scriptId":"u35"},
    "404e1acebece4d89a012b116e1daadbb":{
      "scriptId":"u36"},
    "ab4277ee7ef544458d9176536d929a66":{
      "scriptId":"u37"},
    "e1ea6eadcf62465ca68a23e9ceef9463":{
      "scriptId":"u38"},
    "c8e8f8d8681349769a0b3d635159e63c":{
      "scriptId":"u39"},
    "ab8ff6e900be46ac9b28c33c70086687":{
      "scriptId":"u40"},
    "1fb43d1ad43840d9ab93f0f2c7ebb3d5":{
      "scriptId":"u41"},
    "15ad58a4988149dc99c3a93706ce34b9":{
      "scriptId":"u42"},
    "7808206e94394820bbd9a7cb28ce10f5":{
      "scriptId":"u43"},
    "7e589a0910e44c9cb7079acb13c3e0c9":{
      "scriptId":"u44"},
    "c1ebafb29b34444785b800e7dd8f3ac5":{
      "scriptId":"u45"},
    "eb6f5bed5c5e4bdc84a3a0858ef1294b":{
      "scriptId":"u46"},
    "122cb632e90b43b98a6f21bde5c7a3cf":{
      "scriptId":"u47"},
    "988471009dbc4cde81d26eb02d61c750":{
      "scriptId":"u48"},
    "d2ad3c736d68474288c4b62ed9c6ae00":{
      "scriptId":"u49"},
    "878acae5cfab4014bfd5ea6490cbbc9a":{
      "scriptId":"u50"},
    "b7b77e831e4c4e4388b774069f565e9c":{
      "scriptId":"u51"},
    "989cdde2a8e14085ac0bc2fa18476cf8":{
      "scriptId":"u52"},
    "c7bd7aee71884ca4b34db9b59878e615":{
      "scriptId":"u53"},
    "5838153b95404ebbb44b1e8142a1b866":{
      "scriptId":"u54"},
    "95f5126d44c648289683f6ed4a779de1":{
      "scriptId":"u55"},
    "9da02d2197d144818ad847d55b1f6cc4":{
      "scriptId":"u56"},
    "1d81feceba99408a918a00e223e9f9d5":{
      "scriptId":"u57"},
    "157819b7b51f4da0b0c4adeb765020ae":{
      "scriptId":"u58"},
    "5d29ae8346144b8e9334e7b0dfd952a2":{
      "scriptId":"u59"},
    "796bc6b8fadc465a9f6788f68e757701":{
      "scriptId":"u60"},
    "226ad08c68ae49b5bf5b6dc7f7870511":{
      "scriptId":"u61"},
    "4e0ee763875c4b9a968634b42d1f4cd7":{
      "scriptId":"u62"},
    "161828cf826646cba241a9a90c30d709":{
      "scriptId":"u63"},
    "34b600002ff34b6b8df276e6dac406fc":{
      "scriptId":"u64"},
    "98b25e05013642b9bd7af170105bc7a3":{
      "scriptId":"u65"},
    "96397471d57c4fb3829faabee8716f5b":{
      "scriptId":"u66"},
    "b306a89708614aa984580afc5f58801c":{
      "scriptId":"u67"},
    "eecefef54ef644e18bf6d52bb94ae009":{
      "scriptId":"u68"},
    "801487ac3d6b47738602e39152d3eb66":{
      "scriptId":"u69"}}});