$axure.loadCurrentPage({
  "url":"怪物.html",
  "generationDate":new Date(1393776253395.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"55d90d194b12424195696f7eaaf7f18a",
    "type":"Axure:Page",
    "name":"怪物",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4d1791fff6314fc7a1915bae2961d9dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF996633},
            "size":{
              "width":640,
              "height":1136},
            "cornerRadiusTopLeft":"15"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9d119321f86417c9c89f418782b1b01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF996633},
                "size":{
                  "width":640,
                  "height":1136},
                "cornerRadiusTopLeft":"15"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u0.png"}},
{
          "id":"a967c149001548c2ae60f651e32c3fad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF990099},
            "location":{
              "x":1,
              "y":0},
            "size":{
              "width":640,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b4b9b0100f247d88f9097d4bc1fdac3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF990099},
                "location":{
                  "x":1,
                  "y":0},
                "size":{
                  "width":640,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一次登陆/u4.png"}},
{
          "id":"d3df5a84e3164c6ba3a34c919b24c6ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":1,
              "y":40},
            "size":{
              "width":640,
              "height":100},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c52eea33a3db47f1ba3ba307a248b4c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":1,
                  "y":40},
                "size":{
                  "width":640,
                  "height":100},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u4.png"}},
{
          "id":"eab38bfd43f046b5999083013fe2d36d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCC33},
{
                  "color":0xFFCCCC33},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":106,
              "y":75},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2da0be48de5c498d9842a3ade6821900",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCC33},
{
                      "color":0xFFCCCC33},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":106,
                  "y":75},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u6.png"}},
{
          "id":"c60846f77ea6450ead89a6da59e7d835",
          "label":"水",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":68},
            "size":{
              "width":45,
              "height":45},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a91575d3536f4c1ba64407e25ddb5eb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":68},
                "size":{
                  "width":45,
                  "height":45},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一次选择宠物/水_u22.png"}},
{
          "id":"f4af792ba6ec40819145eef3e1f20ab3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1,
              "y":990},
            "size":{
              "width":640,
              "height":160},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61445e47845c4899a948c117f4be0878",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1,
                  "y":990},
                "size":{
                  "width":640,
                  "height":160},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u10.png"}},
{
          "id":"38465080d4644a6f81c2928868b1e187",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "opacity":"1",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "mouseDown":{
                "opacity":"1"}},
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF993300},
            "location":{
              "x":10,
              "y":1010},
            "size":{
              "width":120,
              "height":120},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2816065c311943ec9d2b82d94b662959",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"1",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "mouseDown":{
                    "opacity":"1"}},
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF993300},
                "location":{
                  "x":10,
                  "y":1010},
                "size":{
                  "width":120,
                  "height":120},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 怪物",
                      "target":{
                        "targetType":"page",
                        "url":"怪物.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主菜单/u12.png",
            "mouseOver~":"images/主菜单/u12_mouseOver.png",
            "mouseDown~":"images/主菜单/u12_mouseOver.png"}},
{
          "id":"9c92d2ac00c34f18b00fe2a71d7b51fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "opacity":"1",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "mouseDown":{
                "opacity":"1"}},
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF993300},
            "location":{
              "x":135,
              "y":1010},
            "size":{
              "width":120,
              "height":120},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5472cd4b951a429aae62619ac46f5eda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"1",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "mouseDown":{
                    "opacity":"1"}},
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF993300},
                "location":{
                  "x":135,
                  "y":1010},
                "size":{
                  "width":120,
                  "height":120},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 背包",
                      "target":{
                        "targetType":"page",
                        "url":"背包.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主菜单/u12.png",
            "mouseOver~":"images/主菜单/u12_mouseOver.png",
            "mouseDown~":"images/主菜单/u12_mouseOver.png"}},
{
          "id":"7eb5b3b6d6cf47638ca3ee9513980783",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "mouseDown":{
                "opacity":"1"}},
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF993300},
            "location":{
              "x":260,
              "y":1010},
            "size":{
              "width":120,
              "height":120},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b961b78ca934a55b07caab227c2cda3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "mouseDown":{
                    "opacity":"1"}},
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF993300},
                "location":{
                  "x":260,
                  "y":1010},
                "size":{
                  "width":120,
                  "height":120},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 战斗",
                      "target":{
                        "targetType":"page",
                        "url":"战斗.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主菜单/u12.png",
            "mouseOver~":"images/主菜单/u12_mouseOver.png",
            "mouseDown~":"images/主菜单/u12_mouseOver.png"}},
{
          "id":"2da8c064e45e48b1a99a56996fb92cc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "opacity":"1",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "mouseDown":{
                "opacity":"1"}},
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF993300},
            "location":{
              "x":385,
              "y":1010},
            "size":{
              "width":120,
              "height":120},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4870a67408a1495d88940fd8463c31fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"1",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "mouseDown":{
                    "opacity":"1"}},
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF993300},
                "location":{
                  "x":385,
                  "y":1010},
                "size":{
                  "width":120,
                  "height":120},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商城",
                      "target":{
                        "targetType":"page",
                        "url":"商城.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主菜单/u12.png",
            "mouseOver~":"images/主菜单/u12_mouseOver.png",
            "mouseDown~":"images/主菜单/u12_mouseOver.png"}},
{
          "id":"990ff90dbd8b4eaeb1a250f636786d64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "opacity":"1",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "mouseDown":{
                "opacity":"1"}},
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF993300},
            "location":{
              "x":510,
              "y":1010},
            "size":{
              "width":120,
              "height":120},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f28b2a0f0494b47b4b3288450452f38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"1",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "mouseDown":{
                    "opacity":"1"}},
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF993300},
                "location":{
                  "x":510,
                  "y":1010},
                "size":{
                  "width":120,
                  "height":120},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设置",
                      "target":{
                        "targetType":"page",
                        "url":"设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主菜单/u12.png",
            "mouseOver~":"images/主菜单/u12_mouseOver.png",
            "mouseDown~":"images/主菜单/u12_mouseOver.png"}},
{
          "id":"a20ff0c79beb4d36afc66f531bc51a38",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":850,
              "y":1036},
            "size":{
              "width":2,
              "height":3},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97cb91ee461047d29a0cbc30c29b3d66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":850,
                  "y":1036},
                "size":{
                  "width":2,
                  "height":3},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u22.png"}},
{
          "id":"6d05e91faba24f7d99ed7e33f772fa85",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":852,
              "y":1036},
            "size":{
              "width":57,
              "height":3},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f11f7841eda4985b29b040c64b0eadf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":852,
                  "y":1036},
                "size":{
                  "width":57,
                  "height":3},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u24.png"}},
{
          "id":"27b6b89dce03497ab1410f4ae9d7bb45",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":37,
              "y":1037},
            "size":{
              "width":70,
              "height":70},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf4d13f7c0054592892b61c5b0054743",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":37,
                  "y":1037},
                "size":{
                  "width":70,
                  "height":70},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u26.png",
            "mouseOver~":"images/主菜单/u26_mouseOver.png"}},
{
          "id":"248f12466e9240d4b7e4f94a539a2cf5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":160,
              "y":1035},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6f2c65df2964399bf2c26384f475962",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":160,
                  "y":1035},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u28.png",
            "mouseOver~":"images/主菜单/u28_mouseOver.png"}},
{
          "id":"9d54de637a1046dba413af97d1b147d2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":288,
              "y":1032},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d42788179f94464c9c008392441d569d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":288,
                  "y":1032},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u30.jpg",
            "mouseOver~":"images/主菜单/u30_mouseOver.png"}},
{
          "id":"a15888cb8d06494b8fd74d06cc9f985d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":411,
              "y":1033},
            "size":{
              "width":70,
              "height":70},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7a2726db5434470bb28456b271a687c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":411,
                  "y":1033},
                "size":{
                  "width":70,
                  "height":70},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u32.png",
            "mouseOver~":"images/主菜单/u32_mouseOver.png"}},
{
          "id":"0f5f6b07327b48c4abc3299b4b0df90b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":542,
              "y":1037},
            "size":{
              "width":55,
              "height":56},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d8f8907ad3642cfb375e82ecc703429",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":542,
                  "y":1037},
                "size":{
                  "width":55,
                  "height":56},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u34.png",
            "mouseOver~":"images/主菜单/u34_mouseOver.png"}},
{
          "id":"404e1acebece4d89a012b116e1daadbb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":336,
              "y":68},
            "size":{
              "width":45,
              "height":45},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab4277ee7ef544458d9176536d929a66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":336,
                  "y":68},
                "size":{
                  "width":45,
                  "height":45},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u36.png"}},
{
          "id":"e1ea6eadcf62465ca68a23e9ceef9463",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCC33},
{
                  "color":0xFFCCCC33},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":401,
              "y":75},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8e8f8d8681349769a0b3d635159e63c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCC33},
{
                      "color":0xFFCCCC33},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":401,
                  "y":75},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u6.png"}},
{
          "id":"ab8ff6e900be46ac9b28c33c70086687",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF990000},
            "location":{
              "x":40,
              "y":187},
            "size":{
              "width":380,
              "height":80},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD91504},
            "cornerRadiusTopLeft":"15"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fb43d1ad43840d9ab93f0f2c7ebb3d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF990000},
                "location":{
                  "x":40,
                  "y":187},
                "size":{
                  "width":380,
                  "height":80},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD91504},
                "cornerRadiusTopLeft":"15"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u40.png"}},
{
          "id":"15ad58a4988149dc99c3a93706ce34b9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":150},
            "size":{
              "width":104,
              "height":37},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7808206e94394820bbd9a7cb28ce10f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":150},
                "size":{
                  "width":104,
                  "height":37},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u42.png"}},
{
          "id":"7e589a0910e44c9cb7079acb13c3e0c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":170,
              "y":341},
            "size":{
              "width":300,
              "height":350},
            "borderWidth":"5",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1ebafb29b34444785b800e7dd8f3ac5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":170,
                  "y":341},
                "size":{
                  "width":300,
                  "height":350},
                "borderWidth":"5",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/怪物/u44.png"}},
{
          "id":"dcc8d2b4f56f40b5be3e3d56383d34ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":75,
              "y":780},
            "size":{
              "width":100,
              "height":100},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD91504},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dabe00772e64daa83fb302d1966195b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":75,
                  "y":780},
                "size":{
                  "width":100,
                  "height":100},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD91504},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 进化树",
                      "target":{
                        "targetType":"page",
                        "url":"进化树.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/怪物/u46.png"}},
{
          "id":"12620fc0f4604a80851159661b5f2989",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":205,
              "y":780},
            "size":{
              "width":100,
              "height":100},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD91504},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90c163db0593465e9451870d510b31aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":205,
                  "y":780},
                "size":{
                  "width":100,
                  "height":100},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD91504},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 融合",
                      "target":{
                        "targetType":"page",
                        "url":"融合.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/怪物/u46.png"}},
{
          "id":"eb6f5bed5c5e4bdc84a3a0858ef1294b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":335,
              "y":780},
            "size":{
              "width":100,
              "height":100},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD91504},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"122cb632e90b43b98a6f21bde5c7a3cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":335,
                  "y":780},
                "size":{
                  "width":100,
                  "height":100},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD91504},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u46.png"}},
{
          "id":"2b61f212da78455aad4fb9d001a65f36",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":465,
              "y":780},
            "size":{
              "width":100,
              "height":100},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD91504},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"182d1df35dc244afa3083ed87bb8c60b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":465,
                  "y":780},
                "size":{
                  "width":100,
                  "height":100},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD91504},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 怪物编队",
                      "target":{
                        "targetType":"page",
                        "url":"怪物编队.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/怪物/u46.png"}},
{
          "id":"b5a9cb4a451b4c6ba81753050948506b",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":710},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd07a8f242e8457b9f6df8bbc1c0985b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":710},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u54.png"}},
{
          "id":"cdc2f6a03a3b443fb3ced7c2cb89788e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":347,
              "y":715},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f7a39b527bb4362975ed9592b155eda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":347,
                  "y":715},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u56.png"}},
{
          "id":"1787f5986880492fba2b3e95aecd567b",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":715},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92e545d838bf4ae781a205c708f4f51e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":715},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u56.png"}},
{
          "id":"d4c33743c3b248b1bf7cfe11406d46e2",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":474},
            "size":{
              "width":62,
              "height":84}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e28c74478e2d4ed297912cfff01b666a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":474},
                "size":{
                  "width":62,
                  "height":84}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u60.png"}},
{
          "id":"982d347cd78340618257e142cbf34a8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":198,
              "y":613},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60574e31ff6542d8893bee26d60118d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":198,
                  "y":613},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0679f89c233740d7b6e2d0575b259338",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":198,
              "y":647},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"434fc95095184e4c8a686c834546fca4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":198,
                  "y":647},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b61abfb8d64e4acdb78cf13cd4cd8f18",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCC6633},
            "location":{
              "x":258,
              "y":618},
            "size":{
              "width":200,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC6666},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"255c4914be8249789c034da73df77707",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC6633},
                "location":{
                  "x":258,
                  "y":618},
                "size":{
                  "width":200,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC6666},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u66.png"}},
{
          "id":"f67aff0174034abebf5b1a0da1fb1825",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCC66},
            "location":{
              "x":258,
              "y":651},
            "size":{
              "width":200,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCC33},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"707b9c37a6974c7b8f990c79c57ffc90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCC66},
                "location":{
                  "x":258,
                  "y":651},
                "size":{
                  "width":200,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCC33},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u68.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4d1791fff6314fc7a1915bae2961d9dc":{
      "scriptId":"u0"},
    "b9d119321f86417c9c89f418782b1b01":{
      "scriptId":"u1"},
    "a967c149001548c2ae60f651e32c3fad":{
      "scriptId":"u2"},
    "4b4b9b0100f247d88f9097d4bc1fdac3":{
      "scriptId":"u3"},
    "d3df5a84e3164c6ba3a34c919b24c6ba":{
      "scriptId":"u4"},
    "c52eea33a3db47f1ba3ba307a248b4c3":{
      "scriptId":"u5"},
    "eab38bfd43f046b5999083013fe2d36d":{
      "scriptId":"u6"},
    "2da0be48de5c498d9842a3ade6821900":{
      "scriptId":"u7"},
    "c60846f77ea6450ead89a6da59e7d835":{
      "scriptId":"u8"},
    "a91575d3536f4c1ba64407e25ddb5eb4":{
      "scriptId":"u9"},
    "f4af792ba6ec40819145eef3e1f20ab3":{
      "scriptId":"u10"},
    "61445e47845c4899a948c117f4be0878":{
      "scriptId":"u11"},
    "38465080d4644a6f81c2928868b1e187":{
      "scriptId":"u12"},
    "2816065c311943ec9d2b82d94b662959":{
      "scriptId":"u13"},
    "9c92d2ac00c34f18b00fe2a71d7b51fb":{
      "scriptId":"u14"},
    "5472cd4b951a429aae62619ac46f5eda":{
      "scriptId":"u15"},
    "7eb5b3b6d6cf47638ca3ee9513980783":{
      "scriptId":"u16"},
    "6b961b78ca934a55b07caab227c2cda3":{
      "scriptId":"u17"},
    "2da8c064e45e48b1a99a56996fb92cc5":{
      "scriptId":"u18"},
    "4870a67408a1495d88940fd8463c31fd":{
      "scriptId":"u19"},
    "990ff90dbd8b4eaeb1a250f636786d64":{
      "scriptId":"u20"},
    "1f28b2a0f0494b47b4b3288450452f38":{
      "scriptId":"u21"},
    "a20ff0c79beb4d36afc66f531bc51a38":{
      "scriptId":"u22"},
    "97cb91ee461047d29a0cbc30c29b3d66":{
      "scriptId":"u23"},
    "6d05e91faba24f7d99ed7e33f772fa85":{
      "scriptId":"u24"},
    "8f11f7841eda4985b29b040c64b0eadf":{
      "scriptId":"u25"},
    "27b6b89dce03497ab1410f4ae9d7bb45":{
      "scriptId":"u26"},
    "cf4d13f7c0054592892b61c5b0054743":{
      "scriptId":"u27"},
    "248f12466e9240d4b7e4f94a539a2cf5":{
      "scriptId":"u28"},
    "f6f2c65df2964399bf2c26384f475962":{
      "scriptId":"u29"},
    "9d54de637a1046dba413af97d1b147d2":{
      "scriptId":"u30"},
    "d42788179f94464c9c008392441d569d":{
      "scriptId":"u31"},
    "a15888cb8d06494b8fd74d06cc9f985d":{
      "scriptId":"u32"},
    "a7a2726db5434470bb28456b271a687c":{
      "scriptId":"u33"},
    "0f5f6b07327b48c4abc3299b4b0df90b":{
      "scriptId":"u34"},
    "0d8f8907ad3642cfb375e82ecc703429":{
      "scriptId":"u35"},
    "404e1acebece4d89a012b116e1daadbb":{
      "scriptId":"u36"},
    "ab4277ee7ef544458d9176536d929a66":{
      "scriptId":"u37"},
    "e1ea6eadcf62465ca68a23e9ceef9463":{
      "scriptId":"u38"},
    "c8e8f8d8681349769a0b3d635159e63c":{
      "scriptId":"u39"},
    "ab8ff6e900be46ac9b28c33c70086687":{
      "scriptId":"u40"},
    "1fb43d1ad43840d9ab93f0f2c7ebb3d5":{
      "scriptId":"u41"},
    "15ad58a4988149dc99c3a93706ce34b9":{
      "scriptId":"u42"},
    "7808206e94394820bbd9a7cb28ce10f5":{
      "scriptId":"u43"},
    "7e589a0910e44c9cb7079acb13c3e0c9":{
      "scriptId":"u44"},
    "c1ebafb29b34444785b800e7dd8f3ac5":{
      "scriptId":"u45"},
    "dcc8d2b4f56f40b5be3e3d56383d34ec":{
      "scriptId":"u46"},
    "7dabe00772e64daa83fb302d1966195b":{
      "scriptId":"u47"},
    "12620fc0f4604a80851159661b5f2989":{
      "scriptId":"u48"},
    "90c163db0593465e9451870d510b31aa":{
      "scriptId":"u49"},
    "eb6f5bed5c5e4bdc84a3a0858ef1294b":{
      "scriptId":"u50"},
    "122cb632e90b43b98a6f21bde5c7a3cf":{
      "scriptId":"u51"},
    "2b61f212da78455aad4fb9d001a65f36":{
      "scriptId":"u52"},
    "182d1df35dc244afa3083ed87bb8c60b":{
      "scriptId":"u53"},
    "b5a9cb4a451b4c6ba81753050948506b":{
      "scriptId":"u54"},
    "bd07a8f242e8457b9f6df8bbc1c0985b":{
      "scriptId":"u55"},
    "cdc2f6a03a3b443fb3ced7c2cb89788e":{
      "scriptId":"u56"},
    "8f7a39b527bb4362975ed9592b155eda":{
      "scriptId":"u57"},
    "1787f5986880492fba2b3e95aecd567b":{
      "scriptId":"u58"},
    "92e545d838bf4ae781a205c708f4f51e":{
      "scriptId":"u59"},
    "d4c33743c3b248b1bf7cfe11406d46e2":{
      "scriptId":"u60"},
    "e28c74478e2d4ed297912cfff01b666a":{
      "scriptId":"u61"},
    "982d347cd78340618257e142cbf34a8f":{
      "scriptId":"u62"},
    "60574e31ff6542d8893bee26d60118d1":{
      "scriptId":"u63"},
    "0679f89c233740d7b6e2d0575b259338":{
      "scriptId":"u64"},
    "434fc95095184e4c8a686c834546fca4":{
      "scriptId":"u65"},
    "b61abfb8d64e4acdb78cf13cd4cd8f18":{
      "scriptId":"u66"},
    "255c4914be8249789c034da73df77707":{
      "scriptId":"u67"},
    "f67aff0174034abebf5b1a0da1fb1825":{
      "scriptId":"u68"},
    "707b9c37a6974c7b8f990c79c57ffc90":{
      "scriptId":"u69"}}});