$axure.loadCurrentPage({
  "url":"抽奖.html",
  "generationDate":new Date(1406724398075.03),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"93c6e7e94a284d2cb5be7d08d29e546a",
    "type":"Axure:Page",
    "name":"抽奖",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"115f907faf3a4212818328ef4fb9e44d",
          "label":"手机",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "size":{
              "width":754,
              "height":1478}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49442bda98ed4a828c6bd7f705c8addd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "size":{
                  "width":754,
                  "height":1478}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/手机_u0.png"}},
{
          "id":"71bf53d145ce4d258fc44f9e8af7f044",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":260},
            "size":{
              "width":640,
              "height":960}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"webUrl",
            "urlLiteral":{
              "exprType":"stringLiteral",
              "value":"",
              "stos":[]},
            "includeVariables":false}},
{
          "id":"02308b426f2b43fbbdce2c4cf9a82363",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":60,
              "y":260},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3efcd92381284a68b2aa0467acfc8146",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":60,
                  "y":260},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u3.png"}},
{
          "id":"59b49d2f0b1d4636af43f9c1b594c768",
          "label":"name",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":75,
              "y":270},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"388e0319799243109fd1d37b482d77da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":75,
                  "y":270},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"0e716f30b0754b1fb72c0896010b0c7c",
          "label":"coin",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":75,
              "y":320},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"933a45c69509439e95348a84d12ade2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":75,
                  "y":320},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"1730c3b9937649a8bf2f2aa212da8580",
          "label":"tips",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":300,
              "y":270},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf8033fba3fb45998feff1bdbf875f8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":300,
                  "y":270},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"34676bc26e9c4b368f9e22c96bc86d12",
          "label":"magic stone",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":300,
              "y":320},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beddb423a0944d67a568b19d68feb133",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":300,
                  "y":320},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If visibility of shopping bar equals false and visibility of shopping bar option 1 equals false and visibility of shopping bar option 2 equals false and visibility of shopping&nbsp; bar option 3 equals false)",
                  "isNewIfGroup":true,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetVisibility",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["25ec19a28c7744728ad0de069038b9ca"]}]},
                      "rightExpr":{
                        "exprType":"booleanLiteral",
                        "value":false}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"&&",
                      "leftExpr":{
                        "exprType":"binaryOp",
                        "op":"==",
                        "leftExpr":{
                          "exprType":"fcall",
                          "functionName":"GetWidgetVisibility",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["0639f3573115435e864d84df1f81802b"]}]},
                        "rightExpr":{
                          "exprType":"booleanLiteral",
                          "value":false}},
                      "rightExpr":{
                        "exprType":"binaryOp",
                        "op":"&&",
                        "leftExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetWidgetVisibility",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["6f7fba5a795346079703d0ab05bacc0d"]}]},
                          "rightExpr":{
                            "exprType":"booleanLiteral",
                            "value":false}},
                        "rightExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetWidgetVisibility",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["2bd36408615f46a6bc227ccb20e7e2ce"]}]},
                          "rightExpr":{
                            "exprType":"booleanLiteral",
                            "value":false}}}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show shopping bar,<br>shopping bar option 1,<br>shopping bar option 2,<br>shopping&nbsp; bar option 3",
                      "objectsToFades":[{
                          "objectPath":["25ec19a28c7744728ad0de069038b9ca"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0639f3573115435e864d84df1f81802b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6f7fba5a795346079703d0ab05bacc0d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2bd36408615f46a6bc227ccb20e7e2ce"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"用例 2<br> (Else If visibility of shopping bar equals true and visibility of shopping bar option 1 equals true and visibility of shopping bar option 2 equals true and visibility of shopping&nbsp; bar option 3 equals true)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetVisibility",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["25ec19a28c7744728ad0de069038b9ca"]}]},
                      "rightExpr":{
                        "exprType":"booleanLiteral",
                        "value":true}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"&&",
                      "leftExpr":{
                        "exprType":"binaryOp",
                        "op":"==",
                        "leftExpr":{
                          "exprType":"fcall",
                          "functionName":"GetWidgetVisibility",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["0639f3573115435e864d84df1f81802b"]}]},
                        "rightExpr":{
                          "exprType":"booleanLiteral",
                          "value":true}},
                      "rightExpr":{
                        "exprType":"binaryOp",
                        "op":"&&",
                        "leftExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetWidgetVisibility",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["6f7fba5a795346079703d0ab05bacc0d"]}]},
                          "rightExpr":{
                            "exprType":"booleanLiteral",
                            "value":true}},
                        "rightExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetWidgetVisibility",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["2bd36408615f46a6bc227ccb20e7e2ce"]}]},
                          "rightExpr":{
                            "exprType":"booleanLiteral",
                            "value":true}}}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Hide shopping bar,<br>shopping bar option 1,<br>shopping bar option 2,<br>shopping&nbsp; bar option 3",
                      "objectsToFades":[{
                          "objectPath":["25ec19a28c7744728ad0de069038b9ca"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0639f3573115435e864d84df1f81802b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6f7fba5a795346079703d0ab05bacc0d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2bd36408615f46a6bc227ccb20e7e2ce"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"ed501b765e224daf80fcdf8681e23d9e",
          "label":"add more magic stone",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":480,
              "y":320},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55217d86e2c34deca49718cd3c309043",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":480,
                  "y":320},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/add_more_magic_stone_u13.png"}},
{
          "id":"b12348cb66f94dccb3362f2a36cdbe23",
          "label":"friends",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":525,
              "y":270},
            "size":{
              "width":160,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5f24403cb8a453d9b5124e77ea20512",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":525,
                  "y":270},
                "size":{
                  "width":160,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Friends in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"friends.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/friends_u15.png"}},
{
          "id":"a2e43479a4b5432ea14a53e6bc1e739f",
          "label":"actor scene",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":60,
              "y":360},
            "size":{
              "width":640,
              "height":730}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"050a55908d5846e28faea53a3b481dd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":60,
                  "y":360},
                "size":{
                  "width":640,
                  "height":730}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/actor_scene_u17.png"}},
{
          "id":"402a8ab8802e4c5db281ac7e8ae83e4a",
          "label":"optional bar",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":60,
              "y":1090},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6b73491537047539502e65b53c3a67d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":60,
                  "y":1090},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/optional_bar_u19.png"}},
{
          "id":"a3546a77032f4e14ad10813b105ad8e6",
          "label":"monster",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":75,
              "y":1100},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"598fff3917634ec29806e76c681ec759",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":75,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open monster in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"monster.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"32d3416cc1bd4d8ba89fd1ffcb8b5e88",
          "label":"knapsack",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":200,
              "y":1100},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07605281390949799a13163b05ce481b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":200,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"ed27b13ac4234940865a2b542df9444f",
          "label":"fighting",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":325,
              "y":1100},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"513484ca83c843cfb6c81313a2f19ac5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":325,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"d799ea9592c746debcc1b1edfb5d007a",
          "label":"schedule",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":450,
              "y":1100},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af68a9c62bd4483ba19480dd5a4f23c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":450,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 抽奖 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"抽奖.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"dc98b814d4b241609283c553036f609d",
          "label":"others",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":574,
              "y":1100},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"620c9e90c50f472c800b1297686d3b54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":574,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open others in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"others.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"25ec19a28c7744728ad0de069038b9ca",
          "label":"shopping bar",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":60,
              "y":600},
            "size":{
              "width":640,
              "height":250},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52567f36c2cf4986ae62885485d5b80c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":60,
                  "y":600},
                "size":{
                  "width":640,
                  "height":250},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/shopping_bar_u93.png"}},
{
          "id":"0639f3573115435e864d84df1f81802b",
          "label":"shopping bar option 1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":75,
              "y":615},
            "size":{
              "width":180,
              "height":220},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3875cfd0e1f4f6d9bb986ad40f376f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":75,
                  "y":615},
                "size":{
                  "width":180,
                  "height":220},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/shopping_bar_option_1_u95.png"}},
{
          "id":"6f7fba5a795346079703d0ab05bacc0d",
          "label":"shopping bar option 2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":270,
              "y":615},
            "size":{
              "width":180,
              "height":220},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e8a8e0bec0e4a7ab5218bc23d363c7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":270,
                  "y":615},
                "size":{
                  "width":180,
                  "height":220},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/shopping_bar_option_1_u95.png"}},
{
          "id":"2bd36408615f46a6bc227ccb20e7e2ce",
          "label":"shopping  bar option 3",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":465,
              "y":615},
            "size":{
              "width":180,
              "height":220},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44e690f7acbe4e979e86d22d1ca79835",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":465,
                  "y":615},
                "size":{
                  "width":180,
                  "height":220},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/shopping_bar_option_1_u95.png"}},
{
          "id":"f04b33b0138446c1b72ce56e75d07fd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":820,
              "y":390},
            "size":{
              "width":15,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1739187973a4423b2e14dbc88c36986",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":820,
                  "y":390},
                "size":{
                  "width":15,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u35.png"}},
{
          "id":"a6834ae9678542cda6185b6979713aa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":800,
              "y":520},
            "size":{
              "width":200,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2db78cb44512441d914a745b55a0d608",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":800,
                  "y":520},
                "size":{
                  "width":200,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u37.png"}},
{
          "id":"919851e2e7cc4468818b310f91cf8e88",
          "label":"schedule list",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":60,
              "y":370},
            "size":{
              "width":270,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f1b2a44c3d14e4f8af59114da2edc02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":60,
                  "y":370},
                "size":{
                  "width":270,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/copy_of_feed_to_monster/friends_list_u29.png"}},
{
          "id":"b208a0059359413aa701ea5f572a8847",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":75,
              "y":445},
            "size":{
              "width":610,
              "height":630}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acdb4f2ce0b748ca9dd9c4118a316071",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":75,
                  "y":445},
                "size":{
                  "width":610,
                  "height":630}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u61.png"}},
{
          "id":"d3e4782c4ca246a594df55b50a04f235",
          "label":"invite",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":560},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If state of This equals 状态1)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["d3e4782c4ca246a594df55b50a04f235"],
                      "panelIndex":0}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set invite to 状态2",
                      "panelsToStates":[{
                          "panelPath":["d3e4782c4ca246a594df55b50a04f235"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]},
{
                  "description":"用例 2<br> (Else If state of This equals 状态2)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["d3e4782c4ca246a594df55b50a04f235"],
                      "panelIndex":1}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set invite to 状态1",
                      "panelsToStates":[{
                          "panelPath":["d3e4782c4ca246a594df55b50a04f235"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"103d1445ac5b4862bcae0c873db58469",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"cb16971c20b944108987e1c6d43321a6",
                  "label":"",
                  "parentDynamicPanel":"d3e4782c4ca246a594df55b50a04f235",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "size":{
                      "width":80,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"75f043f5b3f345c88f0e64ee80fd61f1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d3e4782c4ca246a594df55b50a04f235",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'应用字体 Regular', '应用字体'",
                        "size":{
                          "width":80,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u69.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"64bb3b303d764a58a1e161bea4e1d4a1",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"fd83b988254c48eba88d2693baedcdf4",
                  "label":"",
                  "parentDynamicPanel":"d3e4782c4ca246a594df55b50a04f235",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "size":{
                      "width":80,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"532df4aca64c4f3abb08284ca9c772d4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d3e4782c4ca246a594df55b50a04f235",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'应用字体 Regular', '应用字体'",
                        "size":{
                          "width":80,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u69.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"27fb038fe1e24755a4392fa040d1fe42",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":180,
              "y":560},
            "size":{
              "width":400,
              "height":400}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3eab68534eb425f83f0eb491d2d311f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":180,
                  "y":560},
                "size":{
                  "width":400,
                  "height":400}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show congratulations",
                      "objectsToFades":[{
                          "objectPath":["face4af479df41f6bd80823be4999855"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/抽奖/u52.png"}},
{
          "id":"fa1cadc614444d47b94aaff530f991c2",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":365,
              "y":890},
            "size":{
              "width":30,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5164c1b4446b4e05a2a6dd121d753f05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":365,
                  "y":890},
                "size":{
                  "width":30,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/抽奖/u54.png"}},
{
          "id":"face4af479df41f6bd80823be4999855",
          "label":"congratulations",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":185,
              "y":630},
            "size":{
              "width":390,
              "height":220},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aef481b62c2a4aed868078a830c78e62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":185,
                  "y":630},
                "size":{
                  "width":390,
                  "height":220},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If visibility of This equals true)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetVisibility",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":true}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 抽奖 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"抽奖.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/knapsack/acquire_u232.png"}},
{
          "id":"5a4ea21627af49ab98b76c160c0e43e4",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":560,
              "y":470},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd7c53e21faa4ef680f4a6b545ae8bf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":560,
                  "y":470},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/抽奖/u58.png"}},
{
          "id":"12497972891c4fea91c4f83ca3756dd6",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":75,
              "y":370},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd6dc2a95ede4828b77fa4efb684e831",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":75,
                  "y":370},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open schedule in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"schedule.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/抽奖/u60.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "115f907faf3a4212818328ef4fb9e44d":{
      "scriptId":"u0"},
    "49442bda98ed4a828c6bd7f705c8addd":{
      "scriptId":"u1"},
    "71bf53d145ce4d258fc44f9e8af7f044":{
      "scriptId":"u2"},
    "02308b426f2b43fbbdce2c4cf9a82363":{
      "scriptId":"u3"},
    "3efcd92381284a68b2aa0467acfc8146":{
      "scriptId":"u4"},
    "59b49d2f0b1d4636af43f9c1b594c768":{
      "scriptId":"u5"},
    "388e0319799243109fd1d37b482d77da":{
      "scriptId":"u6"},
    "0e716f30b0754b1fb72c0896010b0c7c":{
      "scriptId":"u7"},
    "933a45c69509439e95348a84d12ade2f":{
      "scriptId":"u8"},
    "1730c3b9937649a8bf2f2aa212da8580":{
      "scriptId":"u9"},
    "bf8033fba3fb45998feff1bdbf875f8b":{
      "scriptId":"u10"},
    "34676bc26e9c4b368f9e22c96bc86d12":{
      "scriptId":"u11"},
    "beddb423a0944d67a568b19d68feb133":{
      "scriptId":"u12"},
    "ed501b765e224daf80fcdf8681e23d9e":{
      "scriptId":"u13"},
    "55217d86e2c34deca49718cd3c309043":{
      "scriptId":"u14"},
    "b12348cb66f94dccb3362f2a36cdbe23":{
      "scriptId":"u15"},
    "f5f24403cb8a453d9b5124e77ea20512":{
      "scriptId":"u16"},
    "a2e43479a4b5432ea14a53e6bc1e739f":{
      "scriptId":"u17"},
    "050a55908d5846e28faea53a3b481dd1":{
      "scriptId":"u18"},
    "402a8ab8802e4c5db281ac7e8ae83e4a":{
      "scriptId":"u19"},
    "a6b73491537047539502e65b53c3a67d":{
      "scriptId":"u20"},
    "a3546a77032f4e14ad10813b105ad8e6":{
      "scriptId":"u21"},
    "598fff3917634ec29806e76c681ec759":{
      "scriptId":"u22"},
    "32d3416cc1bd4d8ba89fd1ffcb8b5e88":{
      "scriptId":"u23"},
    "07605281390949799a13163b05ce481b":{
      "scriptId":"u24"},
    "ed27b13ac4234940865a2b542df9444f":{
      "scriptId":"u25"},
    "513484ca83c843cfb6c81313a2f19ac5":{
      "scriptId":"u26"},
    "d799ea9592c746debcc1b1edfb5d007a":{
      "scriptId":"u27"},
    "af68a9c62bd4483ba19480dd5a4f23c0":{
      "scriptId":"u28"},
    "dc98b814d4b241609283c553036f609d":{
      "scriptId":"u29"},
    "620c9e90c50f472c800b1297686d3b54":{
      "scriptId":"u30"},
    "25ec19a28c7744728ad0de069038b9ca":{
      "scriptId":"u31"},
    "52567f36c2cf4986ae62885485d5b80c":{
      "scriptId":"u32"},
    "0639f3573115435e864d84df1f81802b":{
      "scriptId":"u33"},
    "f3875cfd0e1f4f6d9bb986ad40f376f8":{
      "scriptId":"u34"},
    "6f7fba5a795346079703d0ab05bacc0d":{
      "scriptId":"u35"},
    "2e8a8e0bec0e4a7ab5218bc23d363c7d":{
      "scriptId":"u36"},
    "2bd36408615f46a6bc227ccb20e7e2ce":{
      "scriptId":"u37"},
    "44e690f7acbe4e979e86d22d1ca79835":{
      "scriptId":"u38"},
    "f04b33b0138446c1b72ce56e75d07fd8":{
      "scriptId":"u39"},
    "f1739187973a4423b2e14dbc88c36986":{
      "scriptId":"u40"},
    "a6834ae9678542cda6185b6979713aa8":{
      "scriptId":"u41"},
    "2db78cb44512441d914a745b55a0d608":{
      "scriptId":"u42"},
    "919851e2e7cc4468818b310f91cf8e88":{
      "scriptId":"u43"},
    "2f1b2a44c3d14e4f8af59114da2edc02":{
      "scriptId":"u44"},
    "b208a0059359413aa701ea5f572a8847":{
      "scriptId":"u45"},
    "acdb4f2ce0b748ca9dd9c4118a316071":{
      "scriptId":"u46"},
    "d3e4782c4ca246a594df55b50a04f235":{
      "scriptId":"u47"},
    "cb16971c20b944108987e1c6d43321a6":{
      "scriptId":"u48"},
    "75f043f5b3f345c88f0e64ee80fd61f1":{
      "scriptId":"u49"},
    "fd83b988254c48eba88d2693baedcdf4":{
      "scriptId":"u50"},
    "532df4aca64c4f3abb08284ca9c772d4":{
      "scriptId":"u51"},
    "27fb038fe1e24755a4392fa040d1fe42":{
      "scriptId":"u52"},
    "d3eab68534eb425f83f0eb491d2d311f":{
      "scriptId":"u53"},
    "fa1cadc614444d47b94aaff530f991c2":{
      "scriptId":"u54"},
    "5164c1b4446b4e05a2a6dd121d753f05":{
      "scriptId":"u55"},
    "face4af479df41f6bd80823be4999855":{
      "scriptId":"u56"},
    "aef481b62c2a4aed868078a830c78e62":{
      "scriptId":"u57"},
    "5a4ea21627af49ab98b76c160c0e43e4":{
      "scriptId":"u58"},
    "cd7c53e21faa4ef680f4a6b545ae8bf6":{
      "scriptId":"u59"},
    "12497972891c4fea91c4f83ca3756dd6":{
      "scriptId":"u60"},
    "bd6dc2a95ede4828b77fa4efb684e831":{
      "scriptId":"u61"}}});