$axure.loadCurrentPage({
  "url":"第一次登陆.html",
  "generationDate":new Date(1393776251292.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"004022ed08974f61835939f2660b5a66",
    "type":"Axure:Page",
    "name":"第一次登陆",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4d1791fff6314fc7a1915bae2961d9dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF996633},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9d119321f86417c9c89f418782b1b01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF996633},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/进入游戏/u0.png"}},
{
          "id":"29512d8b18734995bb135a45b5a7645b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF85E0C2},
            "location":{
              "x":116,
              "y":488},
            "size":{
              "width":410,
              "height":170},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fe4c6ad892340d9aeea5792dec11b0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF85E0C2},
                "location":{
                  "x":116,
                  "y":488},
                "size":{
                  "width":410,
                  "height":170},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一次登陆/u2.png"}},
{
          "id":"a967c149001548c2ae60f651e32c3fad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF990099},
            "location":{
              "x":1,
              "y":0},
            "size":{
              "width":640,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b4b9b0100f247d88f9097d4bc1fdac3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF990099},
                "location":{
                  "x":1,
                  "y":0},
                "size":{
                  "width":640,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一次登陆/u4.png"}},
{
          "id":"d3df5a84e3164c6ba3a34c919b24c6ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":1,
              "y":40},
            "size":{
              "width":640,
              "height":100},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c52eea33a3db47f1ba3ba307a248b4c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":1,
                  "y":40},
                "size":{
                  "width":640,
                  "height":100},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一次登陆/u6.png"}},
{
          "id":"cfd2aef7d6e6414a8e774ddeeeff214b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.6",
            "fill":{
              "fillType":"solid",
              "color":0xFF339933},
            "textShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.647058823529412}},
            "location":{
              "x":121,
              "y":492},
            "size":{
              "width":400,
              "height":160},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF33CC99},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92c80538fa5d451fb605519ed653a92d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.6",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF339933},
                "textShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.647058823529412}},
                "location":{
                  "x":121,
                  "y":492},
                "size":{
                  "width":400,
                  "height":160},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF33CC99},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一次登陆/u8.png"}},
{
          "id":"310f5c2d5d3542deb117278520873b44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":220,
              "y":520},
            "size":{
              "width":201,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0ff7d8aed9b432ca28f883098e3c101",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":220,
                  "y":520},
                "size":{
                  "width":201,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1dea0ed7b9d64015a4ebed9c9c3dd3ed",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":171,
              "y":560.5},
            "size":{
              "width":300,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4e9d42870cf041b4b562039fbe0b0636",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF993300}}},
            "opacity":"0.6",
            "fill":{
              "fillType":"solid",
              "color":0xFF996666},
            "location":{
              "x":276,
              "y":600},
            "size":{
              "width":90,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"947a7e3d6d354f19aeeae85d79ce3160",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF993300}}},
                "opacity":"0.6",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF996666},
                "location":{
                  "x":276,
                  "y":600},
                "size":{
                  "width":90,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 第一次选择宠物",
                      "target":{
                        "targetType":"page",
                        "url":"第一次选择宠物.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/第一次登陆/u13.png",
            "mouseDown~":"images/第一次登陆/u13_mouseDown.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4d1791fff6314fc7a1915bae2961d9dc":{
      "scriptId":"u0"},
    "b9d119321f86417c9c89f418782b1b01":{
      "scriptId":"u1"},
    "29512d8b18734995bb135a45b5a7645b":{
      "scriptId":"u2"},
    "6fe4c6ad892340d9aeea5792dec11b0f":{
      "scriptId":"u3"},
    "a967c149001548c2ae60f651e32c3fad":{
      "scriptId":"u4"},
    "4b4b9b0100f247d88f9097d4bc1fdac3":{
      "scriptId":"u5"},
    "d3df5a84e3164c6ba3a34c919b24c6ba":{
      "scriptId":"u6"},
    "c52eea33a3db47f1ba3ba307a248b4c3":{
      "scriptId":"u7"},
    "cfd2aef7d6e6414a8e774ddeeeff214b":{
      "scriptId":"u8"},
    "92c80538fa5d451fb605519ed653a92d":{
      "scriptId":"u9"},
    "310f5c2d5d3542deb117278520873b44":{
      "scriptId":"u10"},
    "a0ff7d8aed9b432ca28f883098e3c101":{
      "scriptId":"u11"},
    "1dea0ed7b9d64015a4ebed9c9c3dd3ed":{
      "scriptId":"u12"},
    "4e9d42870cf041b4b562039fbe0b0636":{
      "scriptId":"u13"},
    "947a7e3d6d354f19aeeae85d79ce3160":{
      "scriptId":"u14"}}});