$axure.loadCurrentPage({
  "url":"怪物编队.html",
  "generationDate":new Date(1393776253694.26),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"31124f775e61436bbf1ab6fe37c21e22",
    "type":"Axure:Page",
    "name":"怪物编队",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4d1791fff6314fc7a1915bae2961d9dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF996633},
            "size":{
              "width":640,
              "height":1136},
            "cornerRadiusTopLeft":"15"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9d119321f86417c9c89f418782b1b01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF996633},
                "size":{
                  "width":640,
                  "height":1136},
                "cornerRadiusTopLeft":"15"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u0.png"}},
{
          "id":"a967c149001548c2ae60f651e32c3fad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF990099},
            "location":{
              "x":1,
              "y":0},
            "size":{
              "width":640,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b4b9b0100f247d88f9097d4bc1fdac3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF990099},
                "location":{
                  "x":1,
                  "y":0},
                "size":{
                  "width":640,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一次登陆/u4.png"}},
{
          "id":"d3df5a84e3164c6ba3a34c919b24c6ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":1,
              "y":40},
            "size":{
              "width":640,
              "height":100},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c52eea33a3db47f1ba3ba307a248b4c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":1,
                  "y":40},
                "size":{
                  "width":640,
                  "height":100},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u4.png"}},
{
          "id":"eab38bfd43f046b5999083013fe2d36d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCC33},
{
                  "color":0xFFCCCC33},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":106,
              "y":75},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2da0be48de5c498d9842a3ade6821900",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCC33},
{
                      "color":0xFFCCCC33},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":106,
                  "y":75},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u6.png"}},
{
          "id":"c60846f77ea6450ead89a6da59e7d835",
          "label":"水",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":68},
            "size":{
              "width":45,
              "height":45},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a91575d3536f4c1ba64407e25ddb5eb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":68},
                "size":{
                  "width":45,
                  "height":45},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一次选择宠物/水_u22.png"}},
{
          "id":"f4af792ba6ec40819145eef3e1f20ab3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1,
              "y":990},
            "size":{
              "width":640,
              "height":160},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61445e47845c4899a948c117f4be0878",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1,
                  "y":990},
                "size":{
                  "width":640,
                  "height":160},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u10.png"}},
{
          "id":"38465080d4644a6f81c2928868b1e187",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "opacity":"1",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "mouseDown":{
                "opacity":"1"}},
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF993300},
            "location":{
              "x":10,
              "y":1010},
            "size":{
              "width":120,
              "height":120},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2816065c311943ec9d2b82d94b662959",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"1",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "mouseDown":{
                    "opacity":"1"}},
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF993300},
                "location":{
                  "x":10,
                  "y":1010},
                "size":{
                  "width":120,
                  "height":120},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 怪物",
                      "target":{
                        "targetType":"page",
                        "url":"怪物.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主菜单/u12.png",
            "mouseOver~":"images/主菜单/u12_mouseOver.png",
            "mouseDown~":"images/主菜单/u12_mouseOver.png"}},
{
          "id":"9c92d2ac00c34f18b00fe2a71d7b51fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "opacity":"1",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "mouseDown":{
                "opacity":"1"}},
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF993300},
            "location":{
              "x":135,
              "y":1010},
            "size":{
              "width":120,
              "height":120},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5472cd4b951a429aae62619ac46f5eda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"1",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "mouseDown":{
                    "opacity":"1"}},
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF993300},
                "location":{
                  "x":135,
                  "y":1010},
                "size":{
                  "width":120,
                  "height":120},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 背包",
                      "target":{
                        "targetType":"page",
                        "url":"背包.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主菜单/u12.png",
            "mouseOver~":"images/主菜单/u12_mouseOver.png",
            "mouseDown~":"images/主菜单/u12_mouseOver.png"}},
{
          "id":"7eb5b3b6d6cf47638ca3ee9513980783",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "mouseDown":{
                "opacity":"1"}},
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF993300},
            "location":{
              "x":260,
              "y":1010},
            "size":{
              "width":120,
              "height":120},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b961b78ca934a55b07caab227c2cda3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "mouseDown":{
                    "opacity":"1"}},
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF993300},
                "location":{
                  "x":260,
                  "y":1010},
                "size":{
                  "width":120,
                  "height":120},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 战斗",
                      "target":{
                        "targetType":"page",
                        "url":"战斗.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主菜单/u12.png",
            "mouseOver~":"images/主菜单/u12_mouseOver.png",
            "mouseDown~":"images/主菜单/u12_mouseOver.png"}},
{
          "id":"2da8c064e45e48b1a99a56996fb92cc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "opacity":"1",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "mouseDown":{
                "opacity":"1"}},
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF993300},
            "location":{
              "x":385,
              "y":1010},
            "size":{
              "width":120,
              "height":120},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4870a67408a1495d88940fd8463c31fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"1",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "mouseDown":{
                    "opacity":"1"}},
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF993300},
                "location":{
                  "x":385,
                  "y":1010},
                "size":{
                  "width":120,
                  "height":120},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商城",
                      "target":{
                        "targetType":"page",
                        "url":"商城.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主菜单/u12.png",
            "mouseOver~":"images/主菜单/u12_mouseOver.png",
            "mouseDown~":"images/主菜单/u12_mouseOver.png"}},
{
          "id":"990ff90dbd8b4eaeb1a250f636786d64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "opacity":"1",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "mouseDown":{
                "opacity":"1"}},
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF993300},
            "location":{
              "x":510,
              "y":1010},
            "size":{
              "width":120,
              "height":120},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f28b2a0f0494b47b4b3288450452f38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"1",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "mouseDown":{
                    "opacity":"1"}},
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF993300},
                "location":{
                  "x":510,
                  "y":1010},
                "size":{
                  "width":120,
                  "height":120},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设置",
                      "target":{
                        "targetType":"page",
                        "url":"设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主菜单/u12.png",
            "mouseOver~":"images/主菜单/u12_mouseOver.png",
            "mouseDown~":"images/主菜单/u12_mouseOver.png"}},
{
          "id":"a20ff0c79beb4d36afc66f531bc51a38",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":850,
              "y":1036},
            "size":{
              "width":2,
              "height":3},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97cb91ee461047d29a0cbc30c29b3d66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":850,
                  "y":1036},
                "size":{
                  "width":2,
                  "height":3},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u22.png"}},
{
          "id":"6d05e91faba24f7d99ed7e33f772fa85",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":852,
              "y":1036},
            "size":{
              "width":57,
              "height":3},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f11f7841eda4985b29b040c64b0eadf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":852,
                  "y":1036},
                "size":{
                  "width":57,
                  "height":3},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u24.png"}},
{
          "id":"27b6b89dce03497ab1410f4ae9d7bb45",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":37,
              "y":1037},
            "size":{
              "width":70,
              "height":70},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf4d13f7c0054592892b61c5b0054743",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":37,
                  "y":1037},
                "size":{
                  "width":70,
                  "height":70},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u26.png",
            "mouseOver~":"images/主菜单/u26_mouseOver.png"}},
{
          "id":"248f12466e9240d4b7e4f94a539a2cf5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":160,
              "y":1035},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6f2c65df2964399bf2c26384f475962",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":160,
                  "y":1035},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u28.png",
            "mouseOver~":"images/主菜单/u28_mouseOver.png"}},
{
          "id":"9d54de637a1046dba413af97d1b147d2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":288,
              "y":1032},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d42788179f94464c9c008392441d569d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":288,
                  "y":1032},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u30.jpg",
            "mouseOver~":"images/主菜单/u30_mouseOver.png"}},
{
          "id":"a15888cb8d06494b8fd74d06cc9f985d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":411,
              "y":1033},
            "size":{
              "width":70,
              "height":70},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7a2726db5434470bb28456b271a687c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":411,
                  "y":1033},
                "size":{
                  "width":70,
                  "height":70},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u32.png",
            "mouseOver~":"images/主菜单/u32_mouseOver.png"}},
{
          "id":"0f5f6b07327b48c4abc3299b4b0df90b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":542,
              "y":1037},
            "size":{
              "width":55,
              "height":56},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d8f8907ad3642cfb375e82ecc703429",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":542,
                  "y":1037},
                "size":{
                  "width":55,
                  "height":56},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u34.png",
            "mouseOver~":"images/主菜单/u34_mouseOver.png"}},
{
          "id":"404e1acebece4d89a012b116e1daadbb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":336,
              "y":68},
            "size":{
              "width":45,
              "height":45},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab4277ee7ef544458d9176536d929a66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":336,
                  "y":68},
                "size":{
                  "width":45,
                  "height":45},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u36.png"}},
{
          "id":"e1ea6eadcf62465ca68a23e9ceef9463",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCC33},
{
                  "color":0xFFCCCC33},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":401,
              "y":75},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8e8f8d8681349769a0b3d635159e63c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCC33},
{
                      "color":0xFFCCCC33},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":401,
                  "y":75},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u6.png"}},
{
          "id":"ab8ff6e900be46ac9b28c33c70086687",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF990000},
            "location":{
              "x":40,
              "y":187},
            "size":{
              "width":380,
              "height":80},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD91504},
            "cornerRadiusTopLeft":"15"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fb43d1ad43840d9ab93f0f2c7ebb3d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF990000},
                "location":{
                  "x":40,
                  "y":187},
                "size":{
                  "width":380,
                  "height":80},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD91504},
                "cornerRadiusTopLeft":"15"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u40.png"}},
{
          "id":"15ad58a4988149dc99c3a93706ce34b9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":150},
            "size":{
              "width":104,
              "height":37},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7808206e94394820bbd9a7cb28ce10f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":150},
                "size":{
                  "width":104,
                  "height":37},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u42.png"}},
{
          "id":"7e589a0910e44c9cb7079acb13c3e0c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":30,
              "y":290},
            "size":{
              "width":580,
              "height":670},
            "borderWidth":"5",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1ebafb29b34444785b800e7dd8f3ac5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":30,
                  "y":290},
                "size":{
                  "width":580,
                  "height":670},
                "borderWidth":"5",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物编队/u44.png"}},
{
          "id":"eb6f5bed5c5e4bdc84a3a0858ef1294b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":54,
              "y":202},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD91504},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"122cb632e90b43b98a6f21bde5c7a3cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":54,
                  "y":202},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD91504},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 怪物",
                      "target":{
                        "targetType":"page",
                        "url":"怪物.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/怪物编队/u46.png"}},
{
          "id":"91a4521650544429a3441ac327124d2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":40,
              "y":325.5},
            "size":{
              "width":182,
              "height":258},
            "borderWidth":"5",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08836f6bc8e047b89a9ddc9d8626265f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":40,
                  "y":325.5},
                "size":{
                  "width":182,
                  "height":258},
                "borderWidth":"5",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 未封印宠物更换出场顺序1",
                      "target":{
                        "targetType":"page",
                        "url":"未封印宠物更换出场顺序1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/怪物编队/u48.png"}},
{
          "id":"e52f3a1ea1d946a5a629396450e0d91b",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":424.5},
            "size":{
              "width":37,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c1370ab135c4825a286e8173ea47ebc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":112,
                  "y":424.5},
                "size":{
                  "width":37,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物编队/u50.png"}},
{
          "id":"7d7d7750c2fd48dabc9d4c368876e051",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":57,
              "y":526.5},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3184652e241467f93b113146e2785fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":57,
                  "y":526.5},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25e752428e3f4314baf5dfa3f3833554",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":57,
              "y":551.5},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7aa9ed4a4e2b4810a1bdb3dcd5bc1eed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":57,
                  "y":551.5},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9e7c241504a4bc3b3d67a5041acf7f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCC6633},
            "location":{
              "x":94,
              "y":530.5},
            "size":{
              "width":121,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC6666},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34d9f3413d954472963e268af74c4ea4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC6633},
                "location":{
                  "x":94,
                  "y":530.5},
                "size":{
                  "width":121,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC6666},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物编队/u56.png"}},
{
          "id":"9a63381bf8ff464da0d0a7488f9cccd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCC66},
            "location":{
              "x":94,
              "y":554.5},
            "size":{
              "width":121,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCC33},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88b0b70f4a404797b8f4e33aa43edeb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCC66},
                "location":{
                  "x":94,
                  "y":554.5},
                "size":{
                  "width":121,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCC33},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物编队/u58.png"}},
{
          "id":"3b402defd9e84d7fa14f457da34b45f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":232,
              "y":326},
            "size":{
              "width":182,
              "height":258},
            "borderWidth":"5",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cbbe49d70494fad826a2b949e2b8c0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":232,
                  "y":326},
                "size":{
                  "width":182,
                  "height":258},
                "borderWidth":"5",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物编队/u48.png"}},
{
          "id":"637c739039bd455cb90fa6608e430353",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":304,
              "y":426},
            "size":{
              "width":37,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddb1f2ffabb74daaa6e01bc843891bae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":304,
                  "y":426},
                "size":{
                  "width":37,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物编队/u50.png"}},
{
          "id":"a2c25e570de3429c849d9ac2efc75300",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":248,
              "y":528},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c32a78cdf7064f60b994a2b1bb39273d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":248,
                  "y":528},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99b65f00a19c4901a46b754245035726",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":248,
              "y":552},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f4cb635677a4e74a0084f86c28262d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":248,
                  "y":552},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05f2722f575246f2a06c346d4a0c1ffb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCC6633},
            "location":{
              "x":286,
              "y":532},
            "size":{
              "width":121,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC6666},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e16bc5513ff470b8fd947ffd4a8e38f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC6633},
                "location":{
                  "x":286,
                  "y":532},
                "size":{
                  "width":121,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC6666},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物编队/u56.png"}},
{
          "id":"25450cd5104f440aa27cbb3027f266ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCC66},
            "location":{
              "x":286,
              "y":556},
            "size":{
              "width":121,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCC33},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d030dbe9e24470ab8836f7c0fe0cf1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCC66},
                "location":{
                  "x":286,
                  "y":556},
                "size":{
                  "width":121,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCC33},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物编队/u58.png"}},
{
          "id":"f77b0c8ce2a24576ba766fc65015a4d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":418,
              "y":326},
            "size":{
              "width":182,
              "height":258},
            "borderWidth":"5",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b198cb69d4f493bb3b1ef4f5bdb2b05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":418,
                  "y":326},
                "size":{
                  "width":182,
                  "height":258},
                "borderWidth":"5",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物编队/u48.png"}},
{
          "id":"7e37ae4264ce44aaa345fbb182876e1b",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":424},
            "size":{
              "width":37,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19d754ebb5bf4df9940a2b6de8ca64ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":424},
                "size":{
                  "width":37,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物编队/u50.png"}},
{
          "id":"ba21f169d0604bd79b068efd828f60f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":435,
              "y":526},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68d60fec72ae4375908a587ec8d7cd87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":435,
                  "y":526},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fcf861194ad04bb3abb4c1783e33f252",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":435,
              "y":552},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbabf012b62c410092f61ab682cb57b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":435,
                  "y":552},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84943a5eeea84976819f09ed85d7ac79",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCC6633},
            "location":{
              "x":472,
              "y":530},
            "size":{
              "width":121,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC6666},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f320dfd4f7504bb89df10859f725bac0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC6633},
                "location":{
                  "x":472,
                  "y":530},
                "size":{
                  "width":121,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC6666},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物编队/u56.png"}},
{
          "id":"93b3163c1bab4675b3bb55b6cb3af010",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCC66},
            "location":{
              "x":472,
              "y":554},
            "size":{
              "width":121,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCC33},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b755346f612470995dff7f87cf88147",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCC66},
                "location":{
                  "x":472,
                  "y":554},
                "size":{
                  "width":121,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCC33},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物编队/u58.png"}},
{
          "id":"d7260306515547aaa7886ca6f43d0cae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "location":{
              "x":56,
              "y":335},
            "size":{
              "width":150,
              "height":50},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6a11f730b0240d4bb10c9bb62e477f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "location":{
                  "x":56,
                  "y":335},
                "size":{
                  "width":150,
                  "height":50},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物编队/u84.png"}},
{
          "id":"11e9be8e2fcb4495bb797dca79120f06",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "location":{
              "x":248,
              "y":335},
            "size":{
              "width":150,
              "height":50},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11e8f0957576489895e0c764879235e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "location":{
                  "x":248,
                  "y":335},
                "size":{
                  "width":150,
                  "height":50},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物编队/u84.png"}},
{
          "id":"ecba23a9ee0c454eb2a79788f1318bdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "location":{
              "x":435,
              "y":335},
            "size":{
              "width":150,
              "height":50},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eaf7100d0b7c447c9b2a6bf28f6aa772",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "location":{
                  "x":435,
                  "y":335},
                "size":{
                  "width":150,
                  "height":50},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物编队/u84.png"}},
{
          "id":"f0f76f75867c483d8061ee2d8dea2bdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":70,
              "y":640},
            "size":{
              "width":100,
              "height":100},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2bf26d0e66349e3bc359882dfe1ad27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":70,
                  "y":640},
                "size":{
                  "width":100,
                  "height":100},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物编队/u90.png"}},
{
          "id":"8f75edc9629b43689e2f9ba1c2607087",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":252.5,
              "y":584},
            "size":{
              "width":141,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbf4fc7cd46145aa8d72f2bd0a2b7ef3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":252.5,
                  "y":584},
                "size":{
                  "width":141,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c70ff3e61b9443498d17217f189ea34",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":121.5,
              "y":293},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dac78bdbfaa49cc88b3a96d74c71823",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121.5,
                  "y":293},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76d9681afdfc4367b62139aca8d9e325",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":293},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9947166f7eba4095b768a11be6300bf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":322,
                  "y":293},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7a6fe15572445d3bdaa581e1114bd5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":292},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f908db2ff8d4f9a9394780bfca47957",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":292},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "4d1791fff6314fc7a1915bae2961d9dc":{
      "scriptId":"u0"},
    "b9d119321f86417c9c89f418782b1b01":{
      "scriptId":"u1"},
    "a967c149001548c2ae60f651e32c3fad":{
      "scriptId":"u2"},
    "4b4b9b0100f247d88f9097d4bc1fdac3":{
      "scriptId":"u3"},
    "d3df5a84e3164c6ba3a34c919b24c6ba":{
      "scriptId":"u4"},
    "c52eea33a3db47f1ba3ba307a248b4c3":{
      "scriptId":"u5"},
    "eab38bfd43f046b5999083013fe2d36d":{
      "scriptId":"u6"},
    "2da0be48de5c498d9842a3ade6821900":{
      "scriptId":"u7"},
    "c60846f77ea6450ead89a6da59e7d835":{
      "scriptId":"u8"},
    "a91575d3536f4c1ba64407e25ddb5eb4":{
      "scriptId":"u9"},
    "f4af792ba6ec40819145eef3e1f20ab3":{
      "scriptId":"u10"},
    "61445e47845c4899a948c117f4be0878":{
      "scriptId":"u11"},
    "38465080d4644a6f81c2928868b1e187":{
      "scriptId":"u12"},
    "2816065c311943ec9d2b82d94b662959":{
      "scriptId":"u13"},
    "9c92d2ac00c34f18b00fe2a71d7b51fb":{
      "scriptId":"u14"},
    "5472cd4b951a429aae62619ac46f5eda":{
      "scriptId":"u15"},
    "7eb5b3b6d6cf47638ca3ee9513980783":{
      "scriptId":"u16"},
    "6b961b78ca934a55b07caab227c2cda3":{
      "scriptId":"u17"},
    "2da8c064e45e48b1a99a56996fb92cc5":{
      "scriptId":"u18"},
    "4870a67408a1495d88940fd8463c31fd":{
      "scriptId":"u19"},
    "990ff90dbd8b4eaeb1a250f636786d64":{
      "scriptId":"u20"},
    "1f28b2a0f0494b47b4b3288450452f38":{
      "scriptId":"u21"},
    "a20ff0c79beb4d36afc66f531bc51a38":{
      "scriptId":"u22"},
    "97cb91ee461047d29a0cbc30c29b3d66":{
      "scriptId":"u23"},
    "6d05e91faba24f7d99ed7e33f772fa85":{
      "scriptId":"u24"},
    "8f11f7841eda4985b29b040c64b0eadf":{
      "scriptId":"u25"},
    "27b6b89dce03497ab1410f4ae9d7bb45":{
      "scriptId":"u26"},
    "cf4d13f7c0054592892b61c5b0054743":{
      "scriptId":"u27"},
    "248f12466e9240d4b7e4f94a539a2cf5":{
      "scriptId":"u28"},
    "f6f2c65df2964399bf2c26384f475962":{
      "scriptId":"u29"},
    "9d54de637a1046dba413af97d1b147d2":{
      "scriptId":"u30"},
    "d42788179f94464c9c008392441d569d":{
      "scriptId":"u31"},
    "a15888cb8d06494b8fd74d06cc9f985d":{
      "scriptId":"u32"},
    "a7a2726db5434470bb28456b271a687c":{
      "scriptId":"u33"},
    "0f5f6b07327b48c4abc3299b4b0df90b":{
      "scriptId":"u34"},
    "0d8f8907ad3642cfb375e82ecc703429":{
      "scriptId":"u35"},
    "404e1acebece4d89a012b116e1daadbb":{
      "scriptId":"u36"},
    "ab4277ee7ef544458d9176536d929a66":{
      "scriptId":"u37"},
    "e1ea6eadcf62465ca68a23e9ceef9463":{
      "scriptId":"u38"},
    "c8e8f8d8681349769a0b3d635159e63c":{
      "scriptId":"u39"},
    "ab8ff6e900be46ac9b28c33c70086687":{
      "scriptId":"u40"},
    "1fb43d1ad43840d9ab93f0f2c7ebb3d5":{
      "scriptId":"u41"},
    "15ad58a4988149dc99c3a93706ce34b9":{
      "scriptId":"u42"},
    "7808206e94394820bbd9a7cb28ce10f5":{
      "scriptId":"u43"},
    "7e589a0910e44c9cb7079acb13c3e0c9":{
      "scriptId":"u44"},
    "c1ebafb29b34444785b800e7dd8f3ac5":{
      "scriptId":"u45"},
    "eb6f5bed5c5e4bdc84a3a0858ef1294b":{
      "scriptId":"u46"},
    "122cb632e90b43b98a6f21bde5c7a3cf":{
      "scriptId":"u47"},
    "91a4521650544429a3441ac327124d2b":{
      "scriptId":"u48"},
    "08836f6bc8e047b89a9ddc9d8626265f":{
      "scriptId":"u49"},
    "e52f3a1ea1d946a5a629396450e0d91b":{
      "scriptId":"u50"},
    "8c1370ab135c4825a286e8173ea47ebc":{
      "scriptId":"u51"},
    "7d7d7750c2fd48dabc9d4c368876e051":{
      "scriptId":"u52"},
    "e3184652e241467f93b113146e2785fc":{
      "scriptId":"u53"},
    "25e752428e3f4314baf5dfa3f3833554":{
      "scriptId":"u54"},
    "7aa9ed4a4e2b4810a1bdb3dcd5bc1eed":{
      "scriptId":"u55"},
    "a9e7c241504a4bc3b3d67a5041acf7f3":{
      "scriptId":"u56"},
    "34d9f3413d954472963e268af74c4ea4":{
      "scriptId":"u57"},
    "9a63381bf8ff464da0d0a7488f9cccd1":{
      "scriptId":"u58"},
    "88b0b70f4a404797b8f4e33aa43edeb8":{
      "scriptId":"u59"},
    "3b402defd9e84d7fa14f457da34b45f6":{
      "scriptId":"u60"},
    "8cbbe49d70494fad826a2b949e2b8c0b":{
      "scriptId":"u61"},
    "637c739039bd455cb90fa6608e430353":{
      "scriptId":"u62"},
    "ddb1f2ffabb74daaa6e01bc843891bae":{
      "scriptId":"u63"},
    "a2c25e570de3429c849d9ac2efc75300":{
      "scriptId":"u64"},
    "c32a78cdf7064f60b994a2b1bb39273d":{
      "scriptId":"u65"},
    "99b65f00a19c4901a46b754245035726":{
      "scriptId":"u66"},
    "4f4cb635677a4e74a0084f86c28262d2":{
      "scriptId":"u67"},
    "05f2722f575246f2a06c346d4a0c1ffb":{
      "scriptId":"u68"},
    "7e16bc5513ff470b8fd947ffd4a8e38f":{
      "scriptId":"u69"},
    "25450cd5104f440aa27cbb3027f266ff":{
      "scriptId":"u70"},
    "4d030dbe9e24470ab8836f7c0fe0cf1a":{
      "scriptId":"u71"},
    "f77b0c8ce2a24576ba766fc65015a4d0":{
      "scriptId":"u72"},
    "5b198cb69d4f493bb3b1ef4f5bdb2b05":{
      "scriptId":"u73"},
    "7e37ae4264ce44aaa345fbb182876e1b":{
      "scriptId":"u74"},
    "19d754ebb5bf4df9940a2b6de8ca64ba":{
      "scriptId":"u75"},
    "ba21f169d0604bd79b068efd828f60f0":{
      "scriptId":"u76"},
    "68d60fec72ae4375908a587ec8d7cd87":{
      "scriptId":"u77"},
    "fcf861194ad04bb3abb4c1783e33f252":{
      "scriptId":"u78"},
    "bbabf012b62c410092f61ab682cb57b1":{
      "scriptId":"u79"},
    "84943a5eeea84976819f09ed85d7ac79":{
      "scriptId":"u80"},
    "f320dfd4f7504bb89df10859f725bac0":{
      "scriptId":"u81"},
    "93b3163c1bab4675b3bb55b6cb3af010":{
      "scriptId":"u82"},
    "6b755346f612470995dff7f87cf88147":{
      "scriptId":"u83"},
    "d7260306515547aaa7886ca6f43d0cae":{
      "scriptId":"u84"},
    "a6a11f730b0240d4bb10c9bb62e477f7":{
      "scriptId":"u85"},
    "11e9be8e2fcb4495bb797dca79120f06":{
      "scriptId":"u86"},
    "11e8f0957576489895e0c764879235e7":{
      "scriptId":"u87"},
    "ecba23a9ee0c454eb2a79788f1318bdf":{
      "scriptId":"u88"},
    "eaf7100d0b7c447c9b2a6bf28f6aa772":{
      "scriptId":"u89"},
    "f0f76f75867c483d8061ee2d8dea2bdf":{
      "scriptId":"u90"},
    "a2bf26d0e66349e3bc359882dfe1ad27":{
      "scriptId":"u91"},
    "8f75edc9629b43689e2f9ba1c2607087":{
      "scriptId":"u92"},
    "fbf4fc7cd46145aa8d72f2bd0a2b7ef3":{
      "scriptId":"u93"},
    "9c70ff3e61b9443498d17217f189ea34":{
      "scriptId":"u94"},
    "4dac78bdbfaa49cc88b3a96d74c71823":{
      "scriptId":"u95"},
    "76d9681afdfc4367b62139aca8d9e325":{
      "scriptId":"u96"},
    "9947166f7eba4095b768a11be6300bf4":{
      "scriptId":"u97"},
    "b7a6fe15572445d3bdaa581e1114bd5f":{
      "scriptId":"u98"},
    "1f908db2ff8d4f9a9394780bfca47957":{
      "scriptId":"u99"}}});