$axure.loadCurrentPage({
  "url":"战斗界面.html",
  "generationDate":new Date(1397338193349.77),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d9309f6e742d4ae9a27c699e507b922d",
    "type":"Axure:Page",
    "name":"战斗界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"03c5a63b34a24f529b1c26405300df30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d683202ee8d041d68300b6e51ddbf775",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗界面/regen/u0.png"}},
{
          "id":"5f9799cfd46b4346b65ee8a63379e6f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8886fdbab13430e8c54b733c04887c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":640,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗界面/regen/u2.png"}},
{
          "id":"b89f1c53bd544faeb92977b3736f874e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":1020},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a43ced345b4c4f2da5b08baf13b46c6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":1020},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗界面/regen/u4.png"}},
{
          "id":"e2200cc9a26744c18026c0e4f5dc50ab",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":1020},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9297349ceb624291a7c6efce513b6b8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":1020},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗界面/regen/u4.png"}},
{
          "id":"4d473c62c9a04a04b750ddc2b4fa4986",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":1020},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f91b2e90a7c465b9bb479dba609904b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":1020},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗界面/regen/u4.png"}},
{
          "id":"ea70c7e9fd1544f0890e5f88f1f99879",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":1020},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89e34707c6f84566906646203af3cc9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":1020},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗界面/regen/u4.png"}},
{
          "id":"9cd60223a1ec49a1a5c838a74552ca2f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":1020},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f9d0da4b53346e48d719b49c1a4e970",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":1020},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗界面/regen/u4.png"}},
{
          "id":"616812b2cd054f658174934484f9a421",
          "label":"边框2",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":false,
          "style":{
            "location":{
              "x":57,
              "y":784},
            "size":{
              "width":106,
              "height":106},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b951ef7c6f34a1f885f087480cb344d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":57,
                  "y":784},
                "size":{
                  "width":106,
                  "height":106},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗界面/regen/边框2_u14.png"}},
{
          "id":"e384af05148b4420863d3902cb2320e7",
          "label":"回合时间",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":false,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":57,
              "y":784},
            "size":{
              "width":107,
              "height":59},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bd4c179048848ee82d2a63c335ec170",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":57,
                  "y":784},
                "size":{
                  "width":107,
                  "height":59},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗界面/regen/回合时间_u16.png"}},
{
          "id":"d04dc56740174431bc48ee70b9108e94",
          "label":"边框1",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":false,
          "style":{
            "location":{
              "x":70,
              "y":800},
            "size":{
              "width":80,
              "height":80},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46804bc67b154b469039c22f2f391999",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":70,
                  "y":800},
                "size":{
                  "width":80,
                  "height":80},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗界面/regen/边框1_u18.png"}},
{
          "id":"9ed263032bf649a4b0cf3e4920b2714a",
          "label":"己方小球",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":810},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13e489a847f2494eb9ba64f9efa2f362",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":810},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 边框2,<br>边框1,<br>回合时间",
                      "objectsToFades":[{
                          "objectPath":["616812b2cd054f658174934484f9a421"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["d04dc56740174431bc48ee70b9108e94"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["e384af05148b4420863d3902cb2320e7"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 边框2,<br>回合时间,<br>边框1",
                      "objectsToFades":[{
                          "objectPath":["616812b2cd054f658174934484f9a421"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["e384af05148b4420863d3902cb2320e7"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["d04dc56740174431bc48ee70b9108e94"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/战斗界面/regen/己方小球_u20.png"}},
{
          "id":"28c705c0102a4b61b88f401f9e5d1193",
          "label":"暂停",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":20},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d93a89f4b394138bf37a5898656d089",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":20},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗界面/regen/暂停_u22.png"}},
{
          "id":"0dad439c6922469d9df07aacab050033",
          "label":"宠物1",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":950},
            "size":{
              "width":200,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4c74df3582248f38f0bc00860d4089b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":950},
                "size":{
                  "width":200,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 遮盖1",
                      "objectsToFades":[{
                          "objectPath":["bd084ce99a3c4de38b200cc5287a6242"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/战斗界面/regen/宠物1_u24.png"}},
{
          "id":"f17b1b74097b4ac9ae28c1843dc370a5",
          "label":"宠物2",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":950},
            "size":{
              "width":200,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38e0450215fd4e13afc647afbd2767d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":950},
                "size":{
                  "width":200,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 遮盖1",
                      "objectsToFades":[{
                          "objectPath":["fb52da5beeb24bb1b7ef1dcfd147a2e4"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/战斗界面/regen/宠物1_u24.png"}},
{
          "id":"53ee3d055d4f41ed8542f7b90fde68db",
          "label":"宠物3",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":950},
            "size":{
              "width":200,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e72b72f647b445a9a96ed0c82c0bb98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":950},
                "size":{
                  "width":200,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 遮盖1",
                      "objectsToFades":[{
                          "objectPath":["3ebce751641e4c8d9987760e760f0b88"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/战斗界面/regen/宠物1_u24.png"}},
{
          "id":"bd084ce99a3c4de38b200cc5287a6242",
          "label":"遮盖1",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":false,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":20,
              "y":950},
            "size":{
              "width":200,
              "height":60},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d744181b3ba480faa8c0ef70dbd3c80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":20,
                  "y":950},
                "size":{
                  "width":200,
                  "height":60},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 遮盖1",
                      "objectsToFades":[{
                          "objectPath":["bd084ce99a3c4de38b200cc5287a6242"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/战斗界面/regen/遮盖1_u30.png"}},
{
          "id":"fb52da5beeb24bb1b7ef1dcfd147a2e4",
          "label":"遮盖1",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":false,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":220,
              "y":950},
            "size":{
              "width":200,
              "height":60},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d0be227b890418ca8467aa2122b3b82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":220,
                  "y":950},
                "size":{
                  "width":200,
                  "height":60},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 遮盖1",
                      "objectsToFades":[{
                          "objectPath":["fb52da5beeb24bb1b7ef1dcfd147a2e4"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/战斗界面/regen/遮盖1_u30.png"}},
{
          "id":"3ebce751641e4c8d9987760e760f0b88",
          "label":"遮盖1",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":false,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":420,
              "y":950},
            "size":{
              "width":200,
              "height":60},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d0713bdcf4946d8bdedd3e0a2a073d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":420,
                  "y":950},
                "size":{
                  "width":200,
                  "height":60},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 遮盖1",
                      "objectsToFades":[{
                          "objectPath":["3ebce751641e4c8d9987760e760f0b88"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/战斗界面/regen/遮盖1_u30.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "03c5a63b34a24f529b1c26405300df30":{
      "scriptId":"u0"},
    "d683202ee8d041d68300b6e51ddbf775":{
      "scriptId":"u1"},
    "5f9799cfd46b4346b65ee8a63379e6f2":{
      "scriptId":"u2"},
    "a8886fdbab13430e8c54b733c04887c7":{
      "scriptId":"u3"},
    "b89f1c53bd544faeb92977b3736f874e":{
      "scriptId":"u4"},
    "a43ced345b4c4f2da5b08baf13b46c6b":{
      "scriptId":"u5"},
    "e2200cc9a26744c18026c0e4f5dc50ab":{
      "scriptId":"u6"},
    "9297349ceb624291a7c6efce513b6b8c":{
      "scriptId":"u7"},
    "4d473c62c9a04a04b750ddc2b4fa4986":{
      "scriptId":"u8"},
    "5f91b2e90a7c465b9bb479dba609904b":{
      "scriptId":"u9"},
    "ea70c7e9fd1544f0890e5f88f1f99879":{
      "scriptId":"u10"},
    "89e34707c6f84566906646203af3cc9d":{
      "scriptId":"u11"},
    "9cd60223a1ec49a1a5c838a74552ca2f":{
      "scriptId":"u12"},
    "5f9d0da4b53346e48d719b49c1a4e970":{
      "scriptId":"u13"},
    "616812b2cd054f658174934484f9a421":{
      "scriptId":"u14"},
    "8b951ef7c6f34a1f885f087480cb344d":{
      "scriptId":"u15"},
    "e384af05148b4420863d3902cb2320e7":{
      "scriptId":"u16"},
    "2bd4c179048848ee82d2a63c335ec170":{
      "scriptId":"u17"},
    "d04dc56740174431bc48ee70b9108e94":{
      "scriptId":"u18"},
    "46804bc67b154b469039c22f2f391999":{
      "scriptId":"u19"},
    "9ed263032bf649a4b0cf3e4920b2714a":{
      "scriptId":"u20"},
    "13e489a847f2494eb9ba64f9efa2f362":{
      "scriptId":"u21"},
    "28c705c0102a4b61b88f401f9e5d1193":{
      "scriptId":"u22"},
    "2d93a89f4b394138bf37a5898656d089":{
      "scriptId":"u23"},
    "0dad439c6922469d9df07aacab050033":{
      "scriptId":"u24"},
    "f4c74df3582248f38f0bc00860d4089b":{
      "scriptId":"u25"},
    "f17b1b74097b4ac9ae28c1843dc370a5":{
      "scriptId":"u26"},
    "38e0450215fd4e13afc647afbd2767d0":{
      "scriptId":"u27"},
    "53ee3d055d4f41ed8542f7b90fde68db":{
      "scriptId":"u28"},
    "0e72b72f647b445a9a96ed0c82c0bb98":{
      "scriptId":"u29"},
    "bd084ce99a3c4de38b200cc5287a6242":{
      "scriptId":"u30"},
    "9d744181b3ba480faa8c0ef70dbd3c80":{
      "scriptId":"u31"},
    "fb52da5beeb24bb1b7ef1dcfd147a2e4":{
      "scriptId":"u32"},
    "0d0be227b890418ca8467aa2122b3b82":{
      "scriptId":"u33"},
    "3ebce751641e4c8d9987760e760f0b88":{
      "scriptId":"u34"},
    "2d0713bdcf4946d8bdedd3e0a2a073d1":{
      "scriptId":"u35"}}});