$axure.loadCurrentPage({
  "url":"暂停界面.html",
  "generationDate":new Date(1393776261811.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b7a8ffed74134ad7876227dcc0dee158",
    "type":"Axure:Page",
    "name":"暂停界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4d1791fff6314fc7a1915bae2961d9dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF996633},
            "size":{
              "width":640,
              "height":1136},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9d119321f86417c9c89f418782b1b01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF996633},
                "size":{
                  "width":640,
                  "height":1136},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物1/u0.png"}},
{
          "id":"a967c149001548c2ae60f651e32c3fad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.9",
            "fill":{
              "fillType":"solid",
              "color":0xFF990099},
            "size":{
              "width":640,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b4b9b0100f247d88f9097d4bc1fdac3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.9",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF990099},
                "size":{
                  "width":640,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一次登陆/u4.png"}},
{
          "id":"d3df5a84e3164c6ba3a34c919b24c6ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":1,
              "y":40},
            "size":{
              "width":640,
              "height":100},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c52eea33a3db47f1ba3ba307a248b4c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":1,
                  "y":40},
                "size":{
                  "width":640,
                  "height":100},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u4.png"}},
{
          "id":"eab38bfd43f046b5999083013fe2d36d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCC33},
{
                  "color":0xFFCCCC33},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":106,
              "y":75},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2da0be48de5c498d9842a3ade6821900",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCC33},
{
                      "color":0xFFCCCC33},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":106,
                  "y":75},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u6.png"}},
{
          "id":"c60846f77ea6450ead89a6da59e7d835",
          "label":"水",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":68},
            "size":{
              "width":45,
              "height":45},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a91575d3536f4c1ba64407e25ddb5eb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":68},
                "size":{
                  "width":45,
                  "height":45},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一次选择宠物/水_u22.png"}},
{
          "id":"a20ff0c79beb4d36afc66f531bc51a38",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":850,
              "y":1036},
            "size":{
              "width":2,
              "height":3},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97cb91ee461047d29a0cbc30c29b3d66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":850,
                  "y":1036},
                "size":{
                  "width":2,
                  "height":3},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u22.png"}},
{
          "id":"6d05e91faba24f7d99ed7e33f772fa85",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":852,
              "y":1036},
            "size":{
              "width":57,
              "height":3},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f11f7841eda4985b29b040c64b0eadf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":852,
                  "y":1036},
                "size":{
                  "width":57,
                  "height":3},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u24.png"}},
{
          "id":"404e1acebece4d89a012b116e1daadbb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":336,
              "y":68},
            "size":{
              "width":45,
              "height":45},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab4277ee7ef544458d9176536d929a66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":336,
                  "y":68},
                "size":{
                  "width":45,
                  "height":45},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u36.png"}},
{
          "id":"e1ea6eadcf62465ca68a23e9ceef9463",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCC33},
{
                  "color":0xFFCCCC33},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":401,
              "y":75},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8e8f8d8681349769a0b3d635159e63c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCC33},
{
                      "color":0xFFCCCC33},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":401,
                  "y":75},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主菜单/u6.png"}},
{
          "id":"1e3b5ccfd650489b8a506cdbb59224c6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":138},
            "size":{
              "width":640,
              "height":358},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9689afb11dd04e249d2790be8731aefd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":138},
                "size":{
                  "width":640,
                  "height":358},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u20.png"}},
{
          "id":"24b08d5df1bd4727b60d98a2118116e7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":496},
            "size":{
              "width":640,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34f24cb06f634efead03490f361750c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":496},
                "size":{
                  "width":640,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u22.png"}},
{
          "id":"84187b3761ab4297a535fdd49c26d1f1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":138},
            "size":{
              "width":64,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57ff4715a452478fa9810d73a1492bb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":138},
                "size":{
                  "width":64,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u24.png"}},
{
          "id":"4ac3b1a9c4b3492f9d910388334d178b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":430},
            "size":{
              "width":51,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"146a4c0cac3d408c9455eda6f36be14e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":430},
                "size":{
                  "width":51,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u26.png"}},
{
          "id":"ffee9380264746f38afcbba49fd8928b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":430},
            "size":{
              "width":56,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae445ff8ecc3481fb37db0491bdd6dae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":430},
                "size":{
                  "width":56,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u28.png"}},
{
          "id":"e7b532e320f04a49908301ed3e35ff3d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":513,
              "y":161},
            "size":{
              "width":51,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"301e2167b66d402d80306a8a232ff9dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":513,
                  "y":161},
                "size":{
                  "width":51,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u26.png"}},
{
          "id":"219216bb427a45d68482bc44ab548075",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":574,
              "y":161},
            "size":{
              "width":56,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef59e0d0337c498d97984509c3ac099d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":574,
                  "y":161},
                "size":{
                  "width":56,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗页面/u28.png"}},
{
          "id":"1a3033219d984c67ba95813bd246a05e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.4",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed4d585b8fbf4a4898da1a240d42727d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.4",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/与被封印宠物更换出场顺序/u104.png"}},
{
          "id":"3ca514e6c2a344c3a69a85f9018bba23",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":252,
              "y":197},
            "size":{
              "width":118,
              "height":40},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6c9d8c111e044589bd9778e69e9e9ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":252,
                  "y":197},
                "size":{
                  "width":118,
                  "height":40},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/暂停界面/u34.png"}},
{
          "id":"577f748897d74f498df76dbb31d8fb97",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":212,
              "y":270},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78c44bbb24234b979f6339476dfa5a63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":212,
                  "y":270},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/暂停界面/u36.png"}},
{
          "id":"a7d571f35a57429f85fe67731cfad3f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":212,
              "y":340},
            "size":{
              "width":200,
              "height":40},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6c1f2e180864c158eb5bc5b97bd905f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":212,
                  "y":340},
                "size":{
                  "width":200,
                  "height":40},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/暂停界面/u38.png"}},
{
          "id":"c01cd70fe5a34d47a69754c891f9f083",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":212,
              "y":410},
            "size":{
              "width":200,
              "height":40},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff9fd156bd0641379cc25b5738cc4984",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":212,
                  "y":410},
                "size":{
                  "width":200,
                  "height":40},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 战斗页面",
                      "target":{
                        "targetType":"page",
                        "url":"战斗页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/暂停界面/u38.png"}},
{
          "id":"10db896d6f994be095d81fad2321bdc7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":285},
            "size":{
              "width":160,
              "height":10},
            "borderWidth":"5"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/暂停界面/u42_line.png"}},
{
          "id":"6abb8959a86d49dda80bc3ceac82ba17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":370,
              "y":270},
            "size":{
              "width":20,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60356f4b12b14048a393da86f7244d42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":370,
                  "y":270},
                "size":{
                  "width":20,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/暂停界面/u43.png"}},
{
          "id":"8402cb8961414b249a8ebed15ccf2a02",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":212,
              "y":480},
            "size":{
              "width":200,
              "height":40},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90152562bd644d399ece8d14e2c310c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":212,
                  "y":480},
                "size":{
                  "width":200,
                  "height":40},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 退出副本确认",
                      "target":{
                        "targetType":"page",
                        "url":"退出副本确认.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/暂停界面/u38.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4d1791fff6314fc7a1915bae2961d9dc":{
      "scriptId":"u0"},
    "b9d119321f86417c9c89f418782b1b01":{
      "scriptId":"u1"},
    "a967c149001548c2ae60f651e32c3fad":{
      "scriptId":"u2"},
    "4b4b9b0100f247d88f9097d4bc1fdac3":{
      "scriptId":"u3"},
    "d3df5a84e3164c6ba3a34c919b24c6ba":{
      "scriptId":"u4"},
    "c52eea33a3db47f1ba3ba307a248b4c3":{
      "scriptId":"u5"},
    "eab38bfd43f046b5999083013fe2d36d":{
      "scriptId":"u6"},
    "2da0be48de5c498d9842a3ade6821900":{
      "scriptId":"u7"},
    "c60846f77ea6450ead89a6da59e7d835":{
      "scriptId":"u8"},
    "a91575d3536f4c1ba64407e25ddb5eb4":{
      "scriptId":"u9"},
    "a20ff0c79beb4d36afc66f531bc51a38":{
      "scriptId":"u10"},
    "97cb91ee461047d29a0cbc30c29b3d66":{
      "scriptId":"u11"},
    "6d05e91faba24f7d99ed7e33f772fa85":{
      "scriptId":"u12"},
    "8f11f7841eda4985b29b040c64b0eadf":{
      "scriptId":"u13"},
    "404e1acebece4d89a012b116e1daadbb":{
      "scriptId":"u14"},
    "ab4277ee7ef544458d9176536d929a66":{
      "scriptId":"u15"},
    "e1ea6eadcf62465ca68a23e9ceef9463":{
      "scriptId":"u16"},
    "c8e8f8d8681349769a0b3d635159e63c":{
      "scriptId":"u17"},
    "1e3b5ccfd650489b8a506cdbb59224c6":{
      "scriptId":"u18"},
    "9689afb11dd04e249d2790be8731aefd":{
      "scriptId":"u19"},
    "24b08d5df1bd4727b60d98a2118116e7":{
      "scriptId":"u20"},
    "34f24cb06f634efead03490f361750c9":{
      "scriptId":"u21"},
    "84187b3761ab4297a535fdd49c26d1f1":{
      "scriptId":"u22"},
    "57ff4715a452478fa9810d73a1492bb4":{
      "scriptId":"u23"},
    "4ac3b1a9c4b3492f9d910388334d178b":{
      "scriptId":"u24"},
    "146a4c0cac3d408c9455eda6f36be14e":{
      "scriptId":"u25"},
    "ffee9380264746f38afcbba49fd8928b":{
      "scriptId":"u26"},
    "ae445ff8ecc3481fb37db0491bdd6dae":{
      "scriptId":"u27"},
    "e7b532e320f04a49908301ed3e35ff3d":{
      "scriptId":"u28"},
    "301e2167b66d402d80306a8a232ff9dc":{
      "scriptId":"u29"},
    "219216bb427a45d68482bc44ab548075":{
      "scriptId":"u30"},
    "ef59e0d0337c498d97984509c3ac099d":{
      "scriptId":"u31"},
    "1a3033219d984c67ba95813bd246a05e":{
      "scriptId":"u32"},
    "ed4d585b8fbf4a4898da1a240d42727d":{
      "scriptId":"u33"},
    "3ca514e6c2a344c3a69a85f9018bba23":{
      "scriptId":"u34"},
    "c6c9d8c111e044589bd9778e69e9e9ba":{
      "scriptId":"u35"},
    "577f748897d74f498df76dbb31d8fb97":{
      "scriptId":"u36"},
    "78c44bbb24234b979f6339476dfa5a63":{
      "scriptId":"u37"},
    "a7d571f35a57429f85fe67731cfad3f1":{
      "scriptId":"u38"},
    "d6c1f2e180864c158eb5bc5b97bd905f":{
      "scriptId":"u39"},
    "c01cd70fe5a34d47a69754c891f9f083":{
      "scriptId":"u40"},
    "ff9fd156bd0641379cc25b5738cc4984":{
      "scriptId":"u41"},
    "10db896d6f994be095d81fad2321bdc7":{
      "scriptId":"u42"},
    "6abb8959a86d49dda80bc3ceac82ba17":{
      "scriptId":"u43"},
    "60356f4b12b14048a393da86f7244d42":{
      "scriptId":"u44"},
    "8402cb8961414b249a8ebed15ccf2a02":{
      "scriptId":"u45"},
    "90152562bd644d399ece8d14e2c310c5":{
      "scriptId":"u46"}}});