$axure.loadCurrentPage({
  "url":"小场景.html",
  "generationDate":new Date(1402535714320.32),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9a524382a81048c0b30dbd71bc5d362b",
    "type":"Axure:Page",
    "name":"小场景",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"115f907faf3a4212818328ef4fb9e44d",
          "label":"手机",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":754,
              "height":1478}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49442bda98ed4a828c6bd7f705c8addd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":754,
                  "height":1478}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/手机_u0.png"}},
{
          "id":"71bf53d145ce4d258fc44f9e8af7f044",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":260},
            "size":{
              "width":640,
              "height":960}},
          "adaptiveStyles":{
}},
{
          "id":"99bb3c364173420596b35677f37af456",
          "label":"Friends list",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":370},
            "size":{
              "width":300,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44087969703d4412b7c7ecebe816cfaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":370},
                "size":{
                  "width":300,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/world_boss/friends_list_u31.png"}},
{
          "id":"f04b33b0138446c1b72ce56e75d07fd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":390},
            "size":{
              "width":15,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1739187973a4423b2e14dbc88c36986",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":820,
                  "y":390},
                "size":{
                  "width":15,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u39.png"}},
{
          "id":"a6834ae9678542cda6185b6979713aa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":520},
            "size":{
              "width":200,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2db78cb44512441d914a745b55a0d608",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":800,
                  "y":520},
                "size":{
                  "width":200,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u41.png"}},
{
          "id":"16fea5dac2694a96a9759a714b46ffef",
          "label":"关卡1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":870},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b2af782a68943f3b0f2a6f84028fe3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101,
                  "y":870},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 推进动画",
                      "target":{
                        "targetType":"page",
                        "url":"推进动画.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/fighting_1/关卡1_u9.png"}},
{
          "id":"444d94b3a96e4e7f984a2f55618d41bf",
          "label":"关卡2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":191,
              "y":460},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d902215891d646e3945c7b30cdd332dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":191,
                  "y":460},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 推进动画",
                      "target":{
                        "targetType":"page",
                        "url":"推进动画.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/fighting_1/关卡1_u9.png"}},
{
          "id":"811c3c786f614e9b82f7bf6b1bc52055",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":620},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cab65a1ce70c4a818b5d35e34099137d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":620},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fighting_1/关卡1_u9.png"}},
{
          "id":"dc46672bd03c4fcba91fdbfcce7aee25",
          "label":"info",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":191,
              "y":870},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3f9be6d409048828a3e84935fa756ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":191,
                  "y":870},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If visibility of 副本信息 = 假)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetVisibility",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["32c8e1afe17440abad4de0d32d1a8992"]}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":false}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 副本信息",
                      "objectsToFades":[{
                          "objectPath":["32c8e1afe17440abad4de0d32d1a8992"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/fighting_1/info_u15.png"}},
{
          "id":"36d6ec8820f14a9d92cbd965754a1e80",
          "label":"back",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":370},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d4c423f53d546eb8a8e5bb59ca4666d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":370},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/world_boss/u73.png"}},
{
          "id":"9ebbf9efed11469eae4d59b6bb563587",
          "label":"info",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":281,
              "y":460},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e2503727b774896a9024539d9ba30f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":281,
                  "y":460},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If visibility of 副本信息 = 假)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetVisibility",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["32c8e1afe17440abad4de0d32d1a8992"]}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":false}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 副本信息",
                      "objectsToFades":[{
                          "objectPath":["32c8e1afe17440abad4de0d32d1a8992"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/fighting_1/info_u15.png"}},
{
          "id":"7435f59fdff24dffbf12cf1c0222f6eb",
          "label":"info",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":620},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96847d7018d84c819236ffec49a12282",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":620},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If visibility of 副本信息 = 假)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetVisibility",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["32c8e1afe17440abad4de0d32d1a8992"]}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":false}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 副本信息",
                      "objectsToFades":[{
                          "objectPath":["32c8e1afe17440abad4de0d32d1a8992"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/fighting_1/info_u15.png"}},
{
          "id":"32c8e1afe17440abad4de0d32d1a8992",
          "label":"副本信息",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":230,
              "y":539},
            "size":{
              "width":300,
              "height":400},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13c2c1ab9d264ec4ba2e916cb86aa703",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":230,
                  "y":539},
                "size":{
                  "width":300,
                  "height":400},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If visibility of This = 真)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetVisibility",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":true}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 副本信息",
                      "objectsToFades":[{
                          "objectPath":["32c8e1afe17440abad4de0d32d1a8992"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/fighting_1/副本信息_u23.png"}},
{
          "id":"d2c1402af86d4ff288f1e1fd2238f7c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":260},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"781285fe73f3478f9fbf0d708998864d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":260},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u3.png"}},
{
          "id":"8f1e5b64afcc45c9a8afe088f8edab3f",
          "label":"name",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":270},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56086971acff427d9910a9184e338e14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":270},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"5f5856ec42bc49709d82ac391fb4d684",
          "label":"coin",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":320},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3623890611744210af825447ef227416",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":320},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"ff7c014739fb4cc2a9c68e10179ba691",
          "label":"tips",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":270},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc23a53cc9c84cb5aadc64c3728f8882",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":270},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"60e1820e96d04d90a510e73d6b84d21b",
          "label":"magic stone",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":320},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6469fe74ce9c4b2b890f20d68e518958",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":320},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If visibility of 不明 = 假 和 visibility of 不明 = 假 和 visibility of 不明 = 假 和 visibility of 不明 = 假)",
                  "isNewIfGroup":true,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetVisibility",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["25ec19a28c7744728ad0de069038b9ca"]}]},
                      "rightExpr":{
                        "exprType":"booleanLiteral",
                        "value":false}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"&&",
                      "leftExpr":{
                        "exprType":"binaryOp",
                        "op":"==",
                        "leftExpr":{
                          "exprType":"fcall",
                          "functionName":"GetWidgetVisibility",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["0639f3573115435e864d84df1f81802b"]}]},
                        "rightExpr":{
                          "exprType":"booleanLiteral",
                          "value":false}},
                      "rightExpr":{
                        "exprType":"binaryOp",
                        "op":"&&",
                        "leftExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetWidgetVisibility",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["6f7fba5a795346079703d0ab05bacc0d"]}]},
                          "rightExpr":{
                            "exprType":"booleanLiteral",
                            "value":false}},
                        "rightExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetWidgetVisibility",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["2bd36408615f46a6bc227ccb20e7e2ce"]}]},
                          "rightExpr":{
                            "exprType":"booleanLiteral",
                            "value":false}}}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]},
{
                  "description":"用例 2<br> (Else If visibility of 不明 = 真 和 visibility of 不明 = 真 和 visibility of 不明 = 真 和 visibility of 不明 = 真)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetVisibility",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["25ec19a28c7744728ad0de069038b9ca"]}]},
                      "rightExpr":{
                        "exprType":"booleanLiteral",
                        "value":true}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"&&",
                      "leftExpr":{
                        "exprType":"binaryOp",
                        "op":"==",
                        "leftExpr":{
                          "exprType":"fcall",
                          "functionName":"GetWidgetVisibility",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["0639f3573115435e864d84df1f81802b"]}]},
                        "rightExpr":{
                          "exprType":"booleanLiteral",
                          "value":true}},
                      "rightExpr":{
                        "exprType":"binaryOp",
                        "op":"&&",
                        "leftExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetWidgetVisibility",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["6f7fba5a795346079703d0ab05bacc0d"]}]},
                          "rightExpr":{
                            "exprType":"booleanLiteral",
                            "value":true}},
                        "rightExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetWidgetVisibility",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["2bd36408615f46a6bc227ccb20e7e2ce"]}]},
                          "rightExpr":{
                            "exprType":"booleanLiteral",
                            "value":true}}}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/name_u5.png"}},
{
          "id":"608d913edb7240c08afada191bb58c78",
          "label":"friends",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":525,
              "y":270},
            "size":{
              "width":160,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03382a2c3418427888e40bea0a7c7e2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":525,
                  "y":270},
                "size":{
                  "width":160,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Friends",
                      "target":{
                        "targetType":"page",
                        "url":"friends.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/friends_u15.png"}},
{
          "id":"a1e382d9150f447f94cad89ab250e6d9",
          "label":"optional bar",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":1090},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84b154384e4545cdba5bc7322d886c46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":1090},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/optional_bar_u19.png"}},
{
          "id":"c3d2944f6c144ad4bb184f2118b7affb",
          "label":"monster",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":1100},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4b16034fac647b6bba3a93050e55664",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 monster",
                      "target":{
                        "targetType":"page",
                        "url":"monster.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"4ee9bfae3e974f9f9ebbdff3779e2983",
          "label":"knapsack",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":1100},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3389613ee954ba4876870330be61316",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"232f6938ac234b6ab1a78665c96f3c9d",
          "label":"fighting",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":1100},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3af82d79be77465ab186fec33a3026c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"a276d2a7aee64b9b9a5c34703d19b6e4",
          "label":"schedule",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":1100},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7560c22823741c08112574c17ff3067",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 schedule",
                      "target":{
                        "targetType":"page",
                        "url":"schedule.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/monster_u21.png"}},
{
          "id":"c60c0f5c50f54c0e9deabd6015bdd4aa",
          "label":"others",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":574.5,
              "y":1100},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f0701955221426eae484f0d904e4a18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":574.5,
                  "y":1100},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 others",
                      "target":{
                        "targetType":"page",
                        "url":"others.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/monster_u21.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "115f907faf3a4212818328ef4fb9e44d":{
      "scriptId":"u0"},
    "49442bda98ed4a828c6bd7f705c8addd":{
      "scriptId":"u1"},
    "71bf53d145ce4d258fc44f9e8af7f044":{
      "scriptId":"u2"},
    "99bb3c364173420596b35677f37af456":{
      "scriptId":"u3"},
    "44087969703d4412b7c7ecebe816cfaa":{
      "scriptId":"u4"},
    "f04b33b0138446c1b72ce56e75d07fd8":{
      "scriptId":"u5"},
    "f1739187973a4423b2e14dbc88c36986":{
      "scriptId":"u6"},
    "a6834ae9678542cda6185b6979713aa8":{
      "scriptId":"u7"},
    "2db78cb44512441d914a745b55a0d608":{
      "scriptId":"u8"},
    "16fea5dac2694a96a9759a714b46ffef":{
      "scriptId":"u9"},
    "0b2af782a68943f3b0f2a6f84028fe3d":{
      "scriptId":"u10"},
    "444d94b3a96e4e7f984a2f55618d41bf":{
      "scriptId":"u11"},
    "d902215891d646e3945c7b30cdd332dd":{
      "scriptId":"u12"},
    "811c3c786f614e9b82f7bf6b1bc52055":{
      "scriptId":"u13"},
    "cab65a1ce70c4a818b5d35e34099137d":{
      "scriptId":"u14"},
    "dc46672bd03c4fcba91fdbfcce7aee25":{
      "scriptId":"u15"},
    "b3f9be6d409048828a3e84935fa756ed":{
      "scriptId":"u16"},
    "36d6ec8820f14a9d92cbd965754a1e80":{
      "scriptId":"u17"},
    "9d4c423f53d546eb8a8e5bb59ca4666d":{
      "scriptId":"u18"},
    "9ebbf9efed11469eae4d59b6bb563587":{
      "scriptId":"u19"},
    "4e2503727b774896a9024539d9ba30f4":{
      "scriptId":"u20"},
    "7435f59fdff24dffbf12cf1c0222f6eb":{
      "scriptId":"u21"},
    "96847d7018d84c819236ffec49a12282":{
      "scriptId":"u22"},
    "32c8e1afe17440abad4de0d32d1a8992":{
      "scriptId":"u23"},
    "13c2c1ab9d264ec4ba2e916cb86aa703":{
      "scriptId":"u24"},
    "d2c1402af86d4ff288f1e1fd2238f7c4":{
      "scriptId":"u25"},
    "781285fe73f3478f9fbf0d708998864d":{
      "scriptId":"u26"},
    "8f1e5b64afcc45c9a8afe088f8edab3f":{
      "scriptId":"u27"},
    "56086971acff427d9910a9184e338e14":{
      "scriptId":"u28"},
    "5f5856ec42bc49709d82ac391fb4d684":{
      "scriptId":"u29"},
    "3623890611744210af825447ef227416":{
      "scriptId":"u30"},
    "ff7c014739fb4cc2a9c68e10179ba691":{
      "scriptId":"u31"},
    "dc23a53cc9c84cb5aadc64c3728f8882":{
      "scriptId":"u32"},
    "60e1820e96d04d90a510e73d6b84d21b":{
      "scriptId":"u33"},
    "6469fe74ce9c4b2b890f20d68e518958":{
      "scriptId":"u34"},
    "608d913edb7240c08afada191bb58c78":{
      "scriptId":"u35"},
    "03382a2c3418427888e40bea0a7c7e2a":{
      "scriptId":"u36"},
    "a1e382d9150f447f94cad89ab250e6d9":{
      "scriptId":"u37"},
    "84b154384e4545cdba5bc7322d886c46":{
      "scriptId":"u38"},
    "c3d2944f6c144ad4bb184f2118b7affb":{
      "scriptId":"u39"},
    "e4b16034fac647b6bba3a93050e55664":{
      "scriptId":"u40"},
    "4ee9bfae3e974f9f9ebbdff3779e2983":{
      "scriptId":"u41"},
    "c3389613ee954ba4876870330be61316":{
      "scriptId":"u42"},
    "232f6938ac234b6ab1a78665c96f3c9d":{
      "scriptId":"u43"},
    "3af82d79be77465ab186fec33a3026c5":{
      "scriptId":"u44"},
    "a276d2a7aee64b9b9a5c34703d19b6e4":{
      "scriptId":"u45"},
    "b7560c22823741c08112574c17ff3067":{
      "scriptId":"u46"},
    "c60c0f5c50f54c0e9deabd6015bdd4aa":{
      "scriptId":"u47"},
    "1f0701955221426eae484f0d904e4a18":{
      "scriptId":"u48"}}});