$axure.loadCurrentPage({
  "url":"人物转变成球动画.html",
  "generationDate":new Date(1402535714470.33),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"02f4e6c1b47e44889145c38b02195297",
    "type":"Axure:Page",
    "name":"人物转变成球动画",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"115f907faf3a4212818328ef4fb9e44d",
          "label":"手机",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":754,
              "height":1478}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49442bda98ed4a828c6bd7f705c8addd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":754,
                  "height":1478}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/手机_u0.png"}},
{
          "id":"3b9ae53e6009491eab900f8758cfb377",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":68,
              "y":263},
            "size":{
              "width":640,
              "height":960}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3233af94cb1d4e6c97e36b18dc1264e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":68,
                  "y":263},
                "size":{
                  "width":640,
                  "height":960}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 战斗界面",
                      "target":{
                        "targetType":"page",
                        "url":"战斗界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/人物转变成球动画/u2.png"}},
{
          "id":"efaae0844f514fafb94fc8f6cd154983",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":400},
            "size":{
              "width":250,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58b2210fb6c749de92ce043c49ef8c4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":400},
                "size":{
                  "width":250,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/actor_u37.png"}},
{
          "id":"65940760737e470ca335b0a0cbef8f55",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":780},
            "size":{
              "width":250,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58fa4f83efd84c82944568fb1a3888c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":780},
                "size":{
                  "width":250,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/人物转变成球动画/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "115f907faf3a4212818328ef4fb9e44d":{
      "scriptId":"u0"},
    "49442bda98ed4a828c6bd7f705c8addd":{
      "scriptId":"u1"},
    "3b9ae53e6009491eab900f8758cfb377":{
      "scriptId":"u2"},
    "3233af94cb1d4e6c97e36b18dc1264e8":{
      "scriptId":"u3"},
    "efaae0844f514fafb94fc8f6cd154983":{
      "scriptId":"u4"},
    "58b2210fb6c749de92ce043c49ef8c4a":{
      "scriptId":"u5"},
    "65940760737e470ca335b0a0cbef8f55":{
      "scriptId":"u6"},
    "58fa4f83efd84c82944568fb1a3888c6":{
      "scriptId":"u7"}}});